# Makefile generated by XPJ for ANDROID
-include Makefile.custom
ProjectName = SnippetVehicleNoDrive
SnippetVehicleNoDrive_cppfiles   += ./../../SnippetVehicleNoDrive/SnippetVehicleNoDrive.cpp
SnippetVehicleNoDrive_cppfiles   += ./../../SnippetVehicleNoDrive/SnippetVehicleNoDriveRender.cpp
SnippetVehicleNoDrive_cppfiles   += ./../../SnippetVehicleCommon/SnippetVehicle4WCreate.cpp
SnippetVehicleNoDrive_cppfiles   += ./../../SnippetVehicleCommon/SnippetVehicleCreate.cpp
SnippetVehicleNoDrive_cppfiles   += ./../../SnippetVehicleCommon/SnippetVehicleFilterShader.cpp
SnippetVehicleNoDrive_cppfiles   += ./../../SnippetVehicleCommon/SnippetVehicleNoDriveCreate.cpp
SnippetVehicleNoDrive_cppfiles   += ./../../SnippetVehicleCommon/SnippetVehicleRaycast.cpp
SnippetVehicleNoDrive_cppfiles   += ./../../SnippetVehicleCommon/SnippetVehicleTankCreate.cpp
SnippetVehicleNoDrive_cppfiles   += ./../../SnippetVehicleCommon/SnippetVehicleTireFriction.cpp

SnippetVehicleNoDrive_cpp_debug_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.debug.P, $(SnippetVehicleNoDrive_cppfiles)))))
SnippetVehicleNoDrive_c_debug_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.debug.P, $(SnippetVehicleNoDrive_cfiles)))))
SnippetVehicleNoDrive_cc_debug_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.debug.P, $(SnippetVehicleNoDrive_ccfiles)))))
SnippetVehicleNoDrive_debug_dep      = $(SnippetVehicleNoDrive_cpp_debug_dep) $(SnippetVehicleNoDrive_cc_debug_dep) $(SnippetVehicleNoDrive_c_debug_dep)
-include $(SnippetVehicleNoDrive_debug_dep)
SnippetVehicleNoDrive_cpp_checked_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.checked.P, $(SnippetVehicleNoDrive_cppfiles)))))
SnippetVehicleNoDrive_c_checked_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.checked.P, $(SnippetVehicleNoDrive_cfiles)))))
SnippetVehicleNoDrive_cc_checked_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.checked.P, $(SnippetVehicleNoDrive_ccfiles)))))
SnippetVehicleNoDrive_checked_dep      = $(SnippetVehicleNoDrive_cpp_checked_dep) $(SnippetVehicleNoDrive_cc_checked_dep) $(SnippetVehicleNoDrive_c_checked_dep)
-include $(SnippetVehicleNoDrive_checked_dep)
SnippetVehicleNoDrive_cpp_profile_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.profile.P, $(SnippetVehicleNoDrive_cppfiles)))))
SnippetVehicleNoDrive_c_profile_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.profile.P, $(SnippetVehicleNoDrive_cfiles)))))
SnippetVehicleNoDrive_cc_profile_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.profile.P, $(SnippetVehicleNoDrive_ccfiles)))))
SnippetVehicleNoDrive_profile_dep      = $(SnippetVehicleNoDrive_cpp_profile_dep) $(SnippetVehicleNoDrive_cc_profile_dep) $(SnippetVehicleNoDrive_c_profile_dep)
-include $(SnippetVehicleNoDrive_profile_dep)
SnippetVehicleNoDrive_cpp_release_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.release.P, $(SnippetVehicleNoDrive_cppfiles)))))
SnippetVehicleNoDrive_c_release_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.release.P, $(SnippetVehicleNoDrive_cfiles)))))
SnippetVehicleNoDrive_cc_release_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.release.P, $(SnippetVehicleNoDrive_ccfiles)))))
SnippetVehicleNoDrive_release_dep      = $(SnippetVehicleNoDrive_cpp_release_dep) $(SnippetVehicleNoDrive_cc_release_dep) $(SnippetVehicleNoDrive_c_release_dep)
-include $(SnippetVehicleNoDrive_release_dep)
SnippetVehicleNoDrive_debug_hpaths    := 
SnippetVehicleNoDrive_debug_hpaths    += ./../../../Source/shared/general/shared
SnippetVehicleNoDrive_debug_hpaths    += ./../../../Include
SnippetVehicleNoDrive_debug_hpaths    += ./../../../Source/foundation/include
SnippetVehicleNoDrive_debug_hpaths    += ./../../../Source/Common/src
SnippetVehicleNoDrive_debug_hpaths    += ./../../../Source/GeomUtils/src
SnippetVehicleNoDrive_debug_hpaths    += ./../../../Source/GeomUtils/headers
SnippetVehicleNoDrive_debug_hpaths    += ./../../../Source/GeomUtils/include
SnippetVehicleNoDrive_debug_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetVehicleNoDrive_debug_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetVehicleNoDrive_debug_lpaths    := 
SnippetVehicleNoDrive_debug_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetVehicleNoDrive_debug_lpaths    += ./../../../Lib/android9_neon
SnippetVehicleNoDrive_debug_defines   := $(SnippetVehicleNoDrive_custom_defines)
SnippetVehicleNoDrive_debug_defines   += ANDROID
SnippetVehicleNoDrive_debug_defines   += GLES2
SnippetVehicleNoDrive_debug_defines   += __ARM_ARCH_5__
SnippetVehicleNoDrive_debug_defines   += __ARM_ARCH_5T__
SnippetVehicleNoDrive_debug_defines   += __ARM_ARCH_5E__
SnippetVehicleNoDrive_debug_defines   += __ARM_ARCH_5TE__
SnippetVehicleNoDrive_debug_defines   += _DEBUG
SnippetVehicleNoDrive_debug_defines   += PX_DEBUG
SnippetVehicleNoDrive_debug_defines   += PX_CHECKED
SnippetVehicleNoDrive_debug_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetVehicleNoDrive_debug_defines   += PX_NVTX
SnippetVehicleNoDrive_debug_defines   += PHYSX_PROFILE_SDK
SnippetVehicleNoDrive_debug_libraries := 
SnippetVehicleNoDrive_debug_libraries += log
SnippetVehicleNoDrive_debug_libraries += gnustl_static
SnippetVehicleNoDrive_debug_libraries += supc++
SnippetVehicleNoDrive_debug_libraries += m
SnippetVehicleNoDrive_debug_libraries += c
SnippetVehicleNoDrive_debug_libraries += nvToolsExt
SnippetVehicleNoDrive_debug_libraries += PhysX3CommonCHECKED
SnippetVehicleNoDrive_debug_libraries += PvdRuntimeCHECKED
SnippetVehicleNoDrive_debug_libraries += SimulationControllerCHECKED
SnippetVehicleNoDrive_debug_libraries += SceneQueryCHECKED
SnippetVehicleNoDrive_debug_libraries += LowLevelCHECKED
SnippetVehicleNoDrive_debug_libraries += LowLevelClothCHECKED
SnippetVehicleNoDrive_debug_libraries += PhysX3CHECKED
SnippetVehicleNoDrive_debug_libraries += PhysX3VehicleCHECKED
SnippetVehicleNoDrive_debug_libraries += PhysX3CookingCHECKED
SnippetVehicleNoDrive_debug_libraries += PhysX3ExtensionsCHECKED
SnippetVehicleNoDrive_debug_libraries += PhysX3CharacterKinematicCHECKED
SnippetVehicleNoDrive_debug_libraries += PhysXProfileSDKCHECKED
SnippetVehicleNoDrive_debug_libraries += PxTaskCHECKED
SnippetVehicleNoDrive_debug_libraries += PhysXVisualDebuggerSDKCHECKED
SnippetVehicleNoDrive_debug_common_cflags	:= $(SnippetVehicleNoDrive_custom_cflags)
SnippetVehicleNoDrive_debug_common_cflags    += -MMD
SnippetVehicleNoDrive_debug_common_cflags    += $(addprefix -D, $(SnippetVehicleNoDrive_debug_defines))
SnippetVehicleNoDrive_debug_common_cflags    += $(addprefix -I, $(SnippetVehicleNoDrive_debug_hpaths))
SnippetVehicleNoDrive_debug_cflags	:= $(SnippetVehicleNoDrive_debug_common_cflags)
SnippetVehicleNoDrive_debug_cflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetVehicleNoDrive_debug_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetVehicleNoDrive_debug_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleNoDrive_debug_cflags  += -g3 -gdwarf-2
SnippetVehicleNoDrive_debug_cppflags	:= $(SnippetVehicleNoDrive_debug_common_cflags)
SnippetVehicleNoDrive_debug_cppflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetVehicleNoDrive_debug_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetVehicleNoDrive_debug_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleNoDrive_debug_cppflags  += -g3 -gdwarf-2
SnippetVehicleNoDrive_debug_lflags    := $(SnippetVehicleNoDrive_custom_lflags)
SnippetVehicleNoDrive_debug_lflags    += $(addprefix -L, $(SnippetVehicleNoDrive_debug_lpaths))
SnippetVehicleNoDrive_debug_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetVehicleNoDrive_debug_libraries)) -Wl,--end-group
SnippetVehicleNoDrive_debug_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleNoDrive_debug_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetVehicleNoDrive_debug_objsdir  = $(OBJS_DIR)/SnippetVehicleNoDrive_debug
SnippetVehicleNoDrive_debug_cpp_o    = $(addprefix $(SnippetVehicleNoDrive_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetVehicleNoDrive_cppfiles)))))
SnippetVehicleNoDrive_debug_c_o      = $(addprefix $(SnippetVehicleNoDrive_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetVehicleNoDrive_cfiles)))))
SnippetVehicleNoDrive_debug_cc_o      = $(addprefix $(SnippetVehicleNoDrive_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetVehicleNoDrive_ccfiles)))))
SnippetVehicleNoDrive_debug_obj      = $(SnippetVehicleNoDrive_debug_cpp_o) $(SnippetVehicleNoDrive_debug_cc_o) $(SnippetVehicleNoDrive_debug_c_o)
SnippetVehicleNoDrive_debug_bin      := ./../../../Bin/android9_neon/SnippetVehicleNoDriveDEBUG

clean_SnippetVehicleNoDrive_debug: 
	@$(ECHO) clean SnippetVehicleNoDrive debug
	@$(RMDIR) $(SnippetVehicleNoDrive_debug_objsdir)
	@$(RMDIR) $(SnippetVehicleNoDrive_debug_bin)

build_SnippetVehicleNoDrive_debug: postbuild_SnippetVehicleNoDrive_debug
postbuild_SnippetVehicleNoDrive_debug: mainbuild_SnippetVehicleNoDrive_debug
mainbuild_SnippetVehicleNoDrive_debug: prebuild_SnippetVehicleNoDrive_debug $(SnippetVehicleNoDrive_debug_bin)
prebuild_SnippetVehicleNoDrive_debug:

$(SnippetVehicleNoDrive_debug_bin): $(SnippetVehicleNoDrive_debug_obj) 
	@mkdir -p `dirname ./../../../Bin/android9_neon/SnippetVehicleNoDriveDEBUG`
	@$(CCLD) $(SnippetVehicleNoDrive_debug_obj) $(SnippetVehicleNoDrive_debug_lflags) -o $(SnippetVehicleNoDrive_debug_bin) 
	@$(ECHO) building $@ complete!

SnippetVehicleNoDrive_debug_DEPDIR = $(dir $(@))/$(*F)
$(SnippetVehicleNoDrive_debug_cpp_o): $(SnippetVehicleNoDrive_debug_objsdir)/%.o:
	@$(ECHO) SnippetVehicleNoDrive: compiling debug $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleNoDrive_debug_objsdir),, $@))), $(SnippetVehicleNoDrive_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetVehicleNoDrive_debug_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleNoDrive_debug_objsdir),, $@))), $(SnippetVehicleNoDrive_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleNoDrive_debug_objsdir),, $@))), $(SnippetVehicleNoDrive_cppfiles))))))
	@cp $(SnippetVehicleNoDrive_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleNoDrive_debug_objsdir),, $@))), $(SnippetVehicleNoDrive_cppfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleNoDrive_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleNoDrive_debug_objsdir),, $@))), $(SnippetVehicleNoDrive_cppfiles))))).debug.P; \
	  rm -f $(SnippetVehicleNoDrive_debug_DEPDIR).d

$(SnippetVehicleNoDrive_debug_c_o): $(SnippetVehicleNoDrive_debug_objsdir)/%.o:
	@$(ECHO) SnippetVehicleNoDrive: compiling debug $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleNoDrive_debug_objsdir),, $@))), $(SnippetVehicleNoDrive_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetVehicleNoDrive_debug_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleNoDrive_debug_objsdir),, $@))), $(SnippetVehicleNoDrive_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleNoDrive_debug_objsdir),, $@))), $(SnippetVehicleNoDrive_cfiles))))))
	@cp $(SnippetVehicleNoDrive_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleNoDrive_debug_objsdir),, $@))), $(SnippetVehicleNoDrive_cfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleNoDrive_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleNoDrive_debug_objsdir),, $@))), $(SnippetVehicleNoDrive_cfiles))))).debug.P; \
	  rm -f $(SnippetVehicleNoDrive_debug_DEPDIR).d

$(SnippetVehicleNoDrive_debug_cc_o): $(SnippetVehicleNoDrive_debug_objsdir)/%.o:
	@$(ECHO) SnippetVehicleNoDrive: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleNoDrive_debug_objsdir),, $@))), $(SnippetVehicleNoDrive_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetVehicleNoDrive_debug_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleNoDrive_debug_objsdir),, $@))), $(SnippetVehicleNoDrive_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleNoDrive_debug_objsdir),, $@))), $(SnippetVehicleNoDrive_ccfiles)))
	@cp $(SnippetVehicleNoDrive_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleNoDrive_debug_objsdir),, $@))), $(SnippetVehicleNoDrive_ccfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleNoDrive_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleNoDrive_debug_objsdir),, $@))), $(SnippetVehicleNoDrive_ccfiles))))).debug.P; \
	  rm -f $(SnippetVehicleNoDrive_debug_DEPDIR).d

SnippetVehicleNoDrive_checked_hpaths    := 
SnippetVehicleNoDrive_checked_hpaths    += ./../../../Source/shared/general/shared
SnippetVehicleNoDrive_checked_hpaths    += ./../../../Include
SnippetVehicleNoDrive_checked_hpaths    += ./../../../Source/foundation/include
SnippetVehicleNoDrive_checked_hpaths    += ./../../../Source/Common/src
SnippetVehicleNoDrive_checked_hpaths    += ./../../../Source/GeomUtils/src
SnippetVehicleNoDrive_checked_hpaths    += ./../../../Source/GeomUtils/headers
SnippetVehicleNoDrive_checked_hpaths    += ./../../../Source/GeomUtils/include
SnippetVehicleNoDrive_checked_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetVehicleNoDrive_checked_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetVehicleNoDrive_checked_lpaths    := 
SnippetVehicleNoDrive_checked_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetVehicleNoDrive_checked_lpaths    += ./../../../Lib/android9_neon
SnippetVehicleNoDrive_checked_defines   := $(SnippetVehicleNoDrive_custom_defines)
SnippetVehicleNoDrive_checked_defines   += ANDROID
SnippetVehicleNoDrive_checked_defines   += GLES2
SnippetVehicleNoDrive_checked_defines   += __ARM_ARCH_5__
SnippetVehicleNoDrive_checked_defines   += __ARM_ARCH_5T__
SnippetVehicleNoDrive_checked_defines   += __ARM_ARCH_5E__
SnippetVehicleNoDrive_checked_defines   += __ARM_ARCH_5TE__
SnippetVehicleNoDrive_checked_defines   += NDEBUG
SnippetVehicleNoDrive_checked_defines   += PX_CHECKED
SnippetVehicleNoDrive_checked_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetVehicleNoDrive_checked_defines   += PX_NVTX
SnippetVehicleNoDrive_checked_defines   += PHYSX_PROFILE_SDK
SnippetVehicleNoDrive_checked_libraries := 
SnippetVehicleNoDrive_checked_libraries += log
SnippetVehicleNoDrive_checked_libraries += gnustl_static
SnippetVehicleNoDrive_checked_libraries += supc++
SnippetVehicleNoDrive_checked_libraries += m
SnippetVehicleNoDrive_checked_libraries += c
SnippetVehicleNoDrive_checked_libraries += nvToolsExt
SnippetVehicleNoDrive_checked_libraries += PhysX3CommonCHECKED
SnippetVehicleNoDrive_checked_libraries += PvdRuntimeCHECKED
SnippetVehicleNoDrive_checked_libraries += SimulationControllerCHECKED
SnippetVehicleNoDrive_checked_libraries += SceneQueryCHECKED
SnippetVehicleNoDrive_checked_libraries += LowLevelCHECKED
SnippetVehicleNoDrive_checked_libraries += LowLevelClothCHECKED
SnippetVehicleNoDrive_checked_libraries += PhysX3CHECKED
SnippetVehicleNoDrive_checked_libraries += PhysX3VehicleCHECKED
SnippetVehicleNoDrive_checked_libraries += PhysX3CookingCHECKED
SnippetVehicleNoDrive_checked_libraries += PhysX3ExtensionsCHECKED
SnippetVehicleNoDrive_checked_libraries += PhysX3CharacterKinematicCHECKED
SnippetVehicleNoDrive_checked_libraries += PhysXProfileSDKCHECKED
SnippetVehicleNoDrive_checked_libraries += PxTaskCHECKED
SnippetVehicleNoDrive_checked_libraries += PhysXVisualDebuggerSDKCHECKED
SnippetVehicleNoDrive_checked_common_cflags	:= $(SnippetVehicleNoDrive_custom_cflags)
SnippetVehicleNoDrive_checked_common_cflags    += -MMD
SnippetVehicleNoDrive_checked_common_cflags    += $(addprefix -D, $(SnippetVehicleNoDrive_checked_defines))
SnippetVehicleNoDrive_checked_common_cflags    += $(addprefix -I, $(SnippetVehicleNoDrive_checked_hpaths))
SnippetVehicleNoDrive_checked_cflags	:= $(SnippetVehicleNoDrive_checked_common_cflags)
SnippetVehicleNoDrive_checked_cflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetVehicleNoDrive_checked_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetVehicleNoDrive_checked_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleNoDrive_checked_cflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
SnippetVehicleNoDrive_checked_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetVehicleNoDrive_checked_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetVehicleNoDrive_checked_cppflags	:= $(SnippetVehicleNoDrive_checked_common_cflags)
SnippetVehicleNoDrive_checked_cppflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetVehicleNoDrive_checked_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetVehicleNoDrive_checked_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleNoDrive_checked_cppflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
SnippetVehicleNoDrive_checked_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetVehicleNoDrive_checked_cppflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetVehicleNoDrive_checked_lflags    := $(SnippetVehicleNoDrive_custom_lflags)
SnippetVehicleNoDrive_checked_lflags    += $(addprefix -L, $(SnippetVehicleNoDrive_checked_lpaths))
SnippetVehicleNoDrive_checked_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetVehicleNoDrive_checked_libraries)) -Wl,--end-group
SnippetVehicleNoDrive_checked_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleNoDrive_checked_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetVehicleNoDrive_checked_objsdir  = $(OBJS_DIR)/SnippetVehicleNoDrive_checked
SnippetVehicleNoDrive_checked_cpp_o    = $(addprefix $(SnippetVehicleNoDrive_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetVehicleNoDrive_cppfiles)))))
SnippetVehicleNoDrive_checked_c_o      = $(addprefix $(SnippetVehicleNoDrive_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetVehicleNoDrive_cfiles)))))
SnippetVehicleNoDrive_checked_cc_o      = $(addprefix $(SnippetVehicleNoDrive_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetVehicleNoDrive_ccfiles)))))
SnippetVehicleNoDrive_checked_obj      = $(SnippetVehicleNoDrive_checked_cpp_o) $(SnippetVehicleNoDrive_checked_cc_o) $(SnippetVehicleNoDrive_checked_c_o)
SnippetVehicleNoDrive_checked_bin      := ./../../../Bin/android9_neon/SnippetVehicleNoDriveCHECKED

clean_SnippetVehicleNoDrive_checked: 
	@$(ECHO) clean SnippetVehicleNoDrive checked
	@$(RMDIR) $(SnippetVehicleNoDrive_checked_objsdir)
	@$(RMDIR) $(SnippetVehicleNoDrive_checked_bin)

build_SnippetVehicleNoDrive_checked: postbuild_SnippetVehicleNoDrive_checked
postbuild_SnippetVehicleNoDrive_checked: mainbuild_SnippetVehicleNoDrive_checked
mainbuild_SnippetVehicleNoDrive_checked: prebuild_SnippetVehicleNoDrive_checked $(SnippetVehicleNoDrive_checked_bin)
prebuild_SnippetVehicleNoDrive_checked:

$(SnippetVehicleNoDrive_checked_bin): $(SnippetVehicleNoDrive_checked_obj) 
	@mkdir -p `dirname ./../../../Bin/android9_neon/SnippetVehicleNoDriveCHECKED`
	@$(CCLD) $(SnippetVehicleNoDrive_checked_obj) $(SnippetVehicleNoDrive_checked_lflags) -o $(SnippetVehicleNoDrive_checked_bin) 
	@$(ECHO) building $@ complete!

SnippetVehicleNoDrive_checked_DEPDIR = $(dir $(@))/$(*F)
$(SnippetVehicleNoDrive_checked_cpp_o): $(SnippetVehicleNoDrive_checked_objsdir)/%.o:
	@$(ECHO) SnippetVehicleNoDrive: compiling checked $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleNoDrive_checked_objsdir),, $@))), $(SnippetVehicleNoDrive_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetVehicleNoDrive_checked_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleNoDrive_checked_objsdir),, $@))), $(SnippetVehicleNoDrive_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleNoDrive_checked_objsdir),, $@))), $(SnippetVehicleNoDrive_cppfiles))))))
	@cp $(SnippetVehicleNoDrive_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleNoDrive_checked_objsdir),, $@))), $(SnippetVehicleNoDrive_cppfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleNoDrive_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleNoDrive_checked_objsdir),, $@))), $(SnippetVehicleNoDrive_cppfiles))))).checked.P; \
	  rm -f $(SnippetVehicleNoDrive_checked_DEPDIR).d

$(SnippetVehicleNoDrive_checked_c_o): $(SnippetVehicleNoDrive_checked_objsdir)/%.o:
	@$(ECHO) SnippetVehicleNoDrive: compiling checked $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleNoDrive_checked_objsdir),, $@))), $(SnippetVehicleNoDrive_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetVehicleNoDrive_checked_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleNoDrive_checked_objsdir),, $@))), $(SnippetVehicleNoDrive_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleNoDrive_checked_objsdir),, $@))), $(SnippetVehicleNoDrive_cfiles))))))
	@cp $(SnippetVehicleNoDrive_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleNoDrive_checked_objsdir),, $@))), $(SnippetVehicleNoDrive_cfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleNoDrive_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleNoDrive_checked_objsdir),, $@))), $(SnippetVehicleNoDrive_cfiles))))).checked.P; \
	  rm -f $(SnippetVehicleNoDrive_checked_DEPDIR).d

$(SnippetVehicleNoDrive_checked_cc_o): $(SnippetVehicleNoDrive_checked_objsdir)/%.o:
	@$(ECHO) SnippetVehicleNoDrive: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleNoDrive_checked_objsdir),, $@))), $(SnippetVehicleNoDrive_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetVehicleNoDrive_checked_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleNoDrive_checked_objsdir),, $@))), $(SnippetVehicleNoDrive_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleNoDrive_checked_objsdir),, $@))), $(SnippetVehicleNoDrive_ccfiles)))
	@cp $(SnippetVehicleNoDrive_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleNoDrive_checked_objsdir),, $@))), $(SnippetVehicleNoDrive_ccfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleNoDrive_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleNoDrive_checked_objsdir),, $@))), $(SnippetVehicleNoDrive_ccfiles))))).checked.P; \
	  rm -f $(SnippetVehicleNoDrive_checked_DEPDIR).d

SnippetVehicleNoDrive_profile_hpaths    := 
SnippetVehicleNoDrive_profile_hpaths    += ./../../../Source/shared/general/shared
SnippetVehicleNoDrive_profile_hpaths    += ./../../../Include
SnippetVehicleNoDrive_profile_hpaths    += ./../../../Source/foundation/include
SnippetVehicleNoDrive_profile_hpaths    += ./../../../Source/Common/src
SnippetVehicleNoDrive_profile_hpaths    += ./../../../Source/GeomUtils/src
SnippetVehicleNoDrive_profile_hpaths    += ./../../../Source/GeomUtils/headers
SnippetVehicleNoDrive_profile_hpaths    += ./../../../Source/GeomUtils/include
SnippetVehicleNoDrive_profile_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetVehicleNoDrive_profile_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetVehicleNoDrive_profile_lpaths    := 
SnippetVehicleNoDrive_profile_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetVehicleNoDrive_profile_lpaths    += ./../../../Lib/android9_neon
SnippetVehicleNoDrive_profile_defines   := $(SnippetVehicleNoDrive_custom_defines)
SnippetVehicleNoDrive_profile_defines   += ANDROID
SnippetVehicleNoDrive_profile_defines   += GLES2
SnippetVehicleNoDrive_profile_defines   += __ARM_ARCH_5__
SnippetVehicleNoDrive_profile_defines   += __ARM_ARCH_5T__
SnippetVehicleNoDrive_profile_defines   += __ARM_ARCH_5E__
SnippetVehicleNoDrive_profile_defines   += __ARM_ARCH_5TE__
SnippetVehicleNoDrive_profile_defines   += NDEBUG
SnippetVehicleNoDrive_profile_defines   += PX_PROFILE
SnippetVehicleNoDrive_profile_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetVehicleNoDrive_profile_defines   += PX_NVTX
SnippetVehicleNoDrive_profile_defines   += PHYSX_PROFILE_SDK
SnippetVehicleNoDrive_profile_libraries := 
SnippetVehicleNoDrive_profile_libraries += log
SnippetVehicleNoDrive_profile_libraries += gnustl_static
SnippetVehicleNoDrive_profile_libraries += supc++
SnippetVehicleNoDrive_profile_libraries += m
SnippetVehicleNoDrive_profile_libraries += c
SnippetVehicleNoDrive_profile_libraries += nvToolsExt
SnippetVehicleNoDrive_profile_libraries += PhysX3CommonPROFILE
SnippetVehicleNoDrive_profile_libraries += PvdRuntimePROFILE
SnippetVehicleNoDrive_profile_libraries += SimulationControllerPROFILE
SnippetVehicleNoDrive_profile_libraries += SceneQueryPROFILE
SnippetVehicleNoDrive_profile_libraries += LowLevelPROFILE
SnippetVehicleNoDrive_profile_libraries += LowLevelClothPROFILE
SnippetVehicleNoDrive_profile_libraries += PhysX3PROFILE
SnippetVehicleNoDrive_profile_libraries += PhysX3VehiclePROFILE
SnippetVehicleNoDrive_profile_libraries += PhysX3CookingPROFILE
SnippetVehicleNoDrive_profile_libraries += PhysX3ExtensionsPROFILE
SnippetVehicleNoDrive_profile_libraries += PhysX3CharacterKinematicPROFILE
SnippetVehicleNoDrive_profile_libraries += PhysXProfileSDKPROFILE
SnippetVehicleNoDrive_profile_libraries += PxTaskPROFILE
SnippetVehicleNoDrive_profile_libraries += PhysXVisualDebuggerSDKPROFILE
SnippetVehicleNoDrive_profile_common_cflags	:= $(SnippetVehicleNoDrive_custom_cflags)
SnippetVehicleNoDrive_profile_common_cflags    += -MMD
SnippetVehicleNoDrive_profile_common_cflags    += $(addprefix -D, $(SnippetVehicleNoDrive_profile_defines))
SnippetVehicleNoDrive_profile_common_cflags    += $(addprefix -I, $(SnippetVehicleNoDrive_profile_hpaths))
SnippetVehicleNoDrive_profile_cflags	:= $(SnippetVehicleNoDrive_profile_common_cflags)
SnippetVehicleNoDrive_profile_cflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetVehicleNoDrive_profile_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetVehicleNoDrive_profile_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleNoDrive_profile_cflags  += -O3 -fno-strict-aliasing
SnippetVehicleNoDrive_profile_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetVehicleNoDrive_profile_cflags  += -fno-omit-frame-pointer -marm -funswitch-loops -finline-limit=300
SnippetVehicleNoDrive_profile_cppflags	:= $(SnippetVehicleNoDrive_profile_common_cflags)
SnippetVehicleNoDrive_profile_cppflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetVehicleNoDrive_profile_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetVehicleNoDrive_profile_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleNoDrive_profile_cppflags  += -O3 -fno-strict-aliasing
SnippetVehicleNoDrive_profile_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetVehicleNoDrive_profile_cppflags  += -fno-omit-frame-pointer -marm -funswitch-loops -finline-limit=300
SnippetVehicleNoDrive_profile_lflags    := $(SnippetVehicleNoDrive_custom_lflags)
SnippetVehicleNoDrive_profile_lflags    += $(addprefix -L, $(SnippetVehicleNoDrive_profile_lpaths))
SnippetVehicleNoDrive_profile_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetVehicleNoDrive_profile_libraries)) -Wl,--end-group
SnippetVehicleNoDrive_profile_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleNoDrive_profile_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetVehicleNoDrive_profile_objsdir  = $(OBJS_DIR)/SnippetVehicleNoDrive_profile
SnippetVehicleNoDrive_profile_cpp_o    = $(addprefix $(SnippetVehicleNoDrive_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetVehicleNoDrive_cppfiles)))))
SnippetVehicleNoDrive_profile_c_o      = $(addprefix $(SnippetVehicleNoDrive_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetVehicleNoDrive_cfiles)))))
SnippetVehicleNoDrive_profile_cc_o      = $(addprefix $(SnippetVehicleNoDrive_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetVehicleNoDrive_ccfiles)))))
SnippetVehicleNoDrive_profile_obj      = $(SnippetVehicleNoDrive_profile_cpp_o) $(SnippetVehicleNoDrive_profile_cc_o) $(SnippetVehicleNoDrive_profile_c_o)
SnippetVehicleNoDrive_profile_bin      := ./../../../Bin/android9_neon/SnippetVehicleNoDrivePROFILE

clean_SnippetVehicleNoDrive_profile: 
	@$(ECHO) clean SnippetVehicleNoDrive profile
	@$(RMDIR) $(SnippetVehicleNoDrive_profile_objsdir)
	@$(RMDIR) $(SnippetVehicleNoDrive_profile_bin)

build_SnippetVehicleNoDrive_profile: postbuild_SnippetVehicleNoDrive_profile
postbuild_SnippetVehicleNoDrive_profile: mainbuild_SnippetVehicleNoDrive_profile
mainbuild_SnippetVehicleNoDrive_profile: prebuild_SnippetVehicleNoDrive_profile $(SnippetVehicleNoDrive_profile_bin)
prebuild_SnippetVehicleNoDrive_profile:

$(SnippetVehicleNoDrive_profile_bin): $(SnippetVehicleNoDrive_profile_obj) 
	@mkdir -p `dirname ./../../../Bin/android9_neon/SnippetVehicleNoDrivePROFILE`
	@$(CCLD) $(SnippetVehicleNoDrive_profile_obj) $(SnippetVehicleNoDrive_profile_lflags) -o $(SnippetVehicleNoDrive_profile_bin) 
	@$(ECHO) building $@ complete!

SnippetVehicleNoDrive_profile_DEPDIR = $(dir $(@))/$(*F)
$(SnippetVehicleNoDrive_profile_cpp_o): $(SnippetVehicleNoDrive_profile_objsdir)/%.o:
	@$(ECHO) SnippetVehicleNoDrive: compiling profile $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleNoDrive_profile_objsdir),, $@))), $(SnippetVehicleNoDrive_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetVehicleNoDrive_profile_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleNoDrive_profile_objsdir),, $@))), $(SnippetVehicleNoDrive_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleNoDrive_profile_objsdir),, $@))), $(SnippetVehicleNoDrive_cppfiles))))))
	@cp $(SnippetVehicleNoDrive_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleNoDrive_profile_objsdir),, $@))), $(SnippetVehicleNoDrive_cppfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleNoDrive_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleNoDrive_profile_objsdir),, $@))), $(SnippetVehicleNoDrive_cppfiles))))).profile.P; \
	  rm -f $(SnippetVehicleNoDrive_profile_DEPDIR).d

$(SnippetVehicleNoDrive_profile_c_o): $(SnippetVehicleNoDrive_profile_objsdir)/%.o:
	@$(ECHO) SnippetVehicleNoDrive: compiling profile $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleNoDrive_profile_objsdir),, $@))), $(SnippetVehicleNoDrive_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetVehicleNoDrive_profile_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleNoDrive_profile_objsdir),, $@))), $(SnippetVehicleNoDrive_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleNoDrive_profile_objsdir),, $@))), $(SnippetVehicleNoDrive_cfiles))))))
	@cp $(SnippetVehicleNoDrive_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleNoDrive_profile_objsdir),, $@))), $(SnippetVehicleNoDrive_cfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleNoDrive_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleNoDrive_profile_objsdir),, $@))), $(SnippetVehicleNoDrive_cfiles))))).profile.P; \
	  rm -f $(SnippetVehicleNoDrive_profile_DEPDIR).d

$(SnippetVehicleNoDrive_profile_cc_o): $(SnippetVehicleNoDrive_profile_objsdir)/%.o:
	@$(ECHO) SnippetVehicleNoDrive: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleNoDrive_profile_objsdir),, $@))), $(SnippetVehicleNoDrive_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetVehicleNoDrive_profile_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleNoDrive_profile_objsdir),, $@))), $(SnippetVehicleNoDrive_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleNoDrive_profile_objsdir),, $@))), $(SnippetVehicleNoDrive_ccfiles)))
	@cp $(SnippetVehicleNoDrive_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleNoDrive_profile_objsdir),, $@))), $(SnippetVehicleNoDrive_ccfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleNoDrive_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleNoDrive_profile_objsdir),, $@))), $(SnippetVehicleNoDrive_ccfiles))))).profile.P; \
	  rm -f $(SnippetVehicleNoDrive_profile_DEPDIR).d

SnippetVehicleNoDrive_release_hpaths    := 
SnippetVehicleNoDrive_release_hpaths    += ./../../../Source/shared/general/shared
SnippetVehicleNoDrive_release_hpaths    += ./../../../Include
SnippetVehicleNoDrive_release_hpaths    += ./../../../Source/foundation/include
SnippetVehicleNoDrive_release_hpaths    += ./../../../Source/Common/src
SnippetVehicleNoDrive_release_hpaths    += ./../../../Source/GeomUtils/src
SnippetVehicleNoDrive_release_hpaths    += ./../../../Source/GeomUtils/headers
SnippetVehicleNoDrive_release_hpaths    += ./../../../Source/GeomUtils/include
SnippetVehicleNoDrive_release_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetVehicleNoDrive_release_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetVehicleNoDrive_release_lpaths    := 
SnippetVehicleNoDrive_release_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetVehicleNoDrive_release_lpaths    += ./../../../Lib/android9_neon
SnippetVehicleNoDrive_release_defines   := $(SnippetVehicleNoDrive_custom_defines)
SnippetVehicleNoDrive_release_defines   += ANDROID
SnippetVehicleNoDrive_release_defines   += GLES2
SnippetVehicleNoDrive_release_defines   += __ARM_ARCH_5__
SnippetVehicleNoDrive_release_defines   += __ARM_ARCH_5T__
SnippetVehicleNoDrive_release_defines   += __ARM_ARCH_5E__
SnippetVehicleNoDrive_release_defines   += __ARM_ARCH_5TE__
SnippetVehicleNoDrive_release_defines   += NDEBUG
SnippetVehicleNoDrive_release_defines   += PHYSX_PROFILE_SDK
SnippetVehicleNoDrive_release_libraries := 
SnippetVehicleNoDrive_release_libraries += log
SnippetVehicleNoDrive_release_libraries += gnustl_static
SnippetVehicleNoDrive_release_libraries += supc++
SnippetVehicleNoDrive_release_libraries += m
SnippetVehicleNoDrive_release_libraries += c
SnippetVehicleNoDrive_release_libraries += nvToolsExt
SnippetVehicleNoDrive_release_libraries += PhysX3Common
SnippetVehicleNoDrive_release_libraries += PvdRuntime
SnippetVehicleNoDrive_release_libraries += SimulationController
SnippetVehicleNoDrive_release_libraries += SceneQuery
SnippetVehicleNoDrive_release_libraries += LowLevel
SnippetVehicleNoDrive_release_libraries += LowLevelCloth
SnippetVehicleNoDrive_release_libraries += PhysX3
SnippetVehicleNoDrive_release_libraries += PhysX3Vehicle
SnippetVehicleNoDrive_release_libraries += PhysX3Cooking
SnippetVehicleNoDrive_release_libraries += PhysX3Extensions
SnippetVehicleNoDrive_release_libraries += PhysX3CharacterKinematic
SnippetVehicleNoDrive_release_libraries += PhysXProfileSDK
SnippetVehicleNoDrive_release_libraries += PxTask
SnippetVehicleNoDrive_release_libraries += PhysXVisualDebuggerSDK
SnippetVehicleNoDrive_release_common_cflags	:= $(SnippetVehicleNoDrive_custom_cflags)
SnippetVehicleNoDrive_release_common_cflags    += -MMD
SnippetVehicleNoDrive_release_common_cflags    += $(addprefix -D, $(SnippetVehicleNoDrive_release_defines))
SnippetVehicleNoDrive_release_common_cflags    += $(addprefix -I, $(SnippetVehicleNoDrive_release_hpaths))
SnippetVehicleNoDrive_release_cflags	:= $(SnippetVehicleNoDrive_release_common_cflags)
SnippetVehicleNoDrive_release_cflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetVehicleNoDrive_release_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetVehicleNoDrive_release_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleNoDrive_release_cflags  += -O3 -fno-strict-aliasing
SnippetVehicleNoDrive_release_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetVehicleNoDrive_release_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetVehicleNoDrive_release_cppflags	:= $(SnippetVehicleNoDrive_release_common_cflags)
SnippetVehicleNoDrive_release_cppflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetVehicleNoDrive_release_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetVehicleNoDrive_release_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleNoDrive_release_cppflags  += -O3 -fno-strict-aliasing
SnippetVehicleNoDrive_release_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetVehicleNoDrive_release_cppflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetVehicleNoDrive_release_lflags    := $(SnippetVehicleNoDrive_custom_lflags)
SnippetVehicleNoDrive_release_lflags    += $(addprefix -L, $(SnippetVehicleNoDrive_release_lpaths))
SnippetVehicleNoDrive_release_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetVehicleNoDrive_release_libraries)) -Wl,--end-group
SnippetVehicleNoDrive_release_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleNoDrive_release_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetVehicleNoDrive_release_objsdir  = $(OBJS_DIR)/SnippetVehicleNoDrive_release
SnippetVehicleNoDrive_release_cpp_o    = $(addprefix $(SnippetVehicleNoDrive_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetVehicleNoDrive_cppfiles)))))
SnippetVehicleNoDrive_release_c_o      = $(addprefix $(SnippetVehicleNoDrive_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetVehicleNoDrive_cfiles)))))
SnippetVehicleNoDrive_release_cc_o      = $(addprefix $(SnippetVehicleNoDrive_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetVehicleNoDrive_ccfiles)))))
SnippetVehicleNoDrive_release_obj      = $(SnippetVehicleNoDrive_release_cpp_o) $(SnippetVehicleNoDrive_release_cc_o) $(SnippetVehicleNoDrive_release_c_o)
SnippetVehicleNoDrive_release_bin      := ./../../../Bin/android9_neon/SnippetVehicleNoDrive

clean_SnippetVehicleNoDrive_release: 
	@$(ECHO) clean SnippetVehicleNoDrive release
	@$(RMDIR) $(SnippetVehicleNoDrive_release_objsdir)
	@$(RMDIR) $(SnippetVehicleNoDrive_release_bin)

build_SnippetVehicleNoDrive_release: postbuild_SnippetVehicleNoDrive_release
postbuild_SnippetVehicleNoDrive_release: mainbuild_SnippetVehicleNoDrive_release
mainbuild_SnippetVehicleNoDrive_release: prebuild_SnippetVehicleNoDrive_release $(SnippetVehicleNoDrive_release_bin)
prebuild_SnippetVehicleNoDrive_release:

$(SnippetVehicleNoDrive_release_bin): $(SnippetVehicleNoDrive_release_obj) 
	@mkdir -p `dirname ./../../../Bin/android9_neon/SnippetVehicleNoDrive`
	@$(CCLD) $(SnippetVehicleNoDrive_release_obj) $(SnippetVehicleNoDrive_release_lflags) -o $(SnippetVehicleNoDrive_release_bin) 
	@$(ECHO) building $@ complete!

SnippetVehicleNoDrive_release_DEPDIR = $(dir $(@))/$(*F)
$(SnippetVehicleNoDrive_release_cpp_o): $(SnippetVehicleNoDrive_release_objsdir)/%.o:
	@$(ECHO) SnippetVehicleNoDrive: compiling release $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleNoDrive_release_objsdir),, $@))), $(SnippetVehicleNoDrive_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetVehicleNoDrive_release_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleNoDrive_release_objsdir),, $@))), $(SnippetVehicleNoDrive_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleNoDrive_release_objsdir),, $@))), $(SnippetVehicleNoDrive_cppfiles))))))
	@cp $(SnippetVehicleNoDrive_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleNoDrive_release_objsdir),, $@))), $(SnippetVehicleNoDrive_cppfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleNoDrive_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleNoDrive_release_objsdir),, $@))), $(SnippetVehicleNoDrive_cppfiles))))).release.P; \
	  rm -f $(SnippetVehicleNoDrive_release_DEPDIR).d

$(SnippetVehicleNoDrive_release_c_o): $(SnippetVehicleNoDrive_release_objsdir)/%.o:
	@$(ECHO) SnippetVehicleNoDrive: compiling release $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleNoDrive_release_objsdir),, $@))), $(SnippetVehicleNoDrive_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetVehicleNoDrive_release_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleNoDrive_release_objsdir),, $@))), $(SnippetVehicleNoDrive_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleNoDrive_release_objsdir),, $@))), $(SnippetVehicleNoDrive_cfiles))))))
	@cp $(SnippetVehicleNoDrive_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleNoDrive_release_objsdir),, $@))), $(SnippetVehicleNoDrive_cfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleNoDrive_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleNoDrive_release_objsdir),, $@))), $(SnippetVehicleNoDrive_cfiles))))).release.P; \
	  rm -f $(SnippetVehicleNoDrive_release_DEPDIR).d

$(SnippetVehicleNoDrive_release_cc_o): $(SnippetVehicleNoDrive_release_objsdir)/%.o:
	@$(ECHO) SnippetVehicleNoDrive: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleNoDrive_release_objsdir),, $@))), $(SnippetVehicleNoDrive_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetVehicleNoDrive_release_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleNoDrive_release_objsdir),, $@))), $(SnippetVehicleNoDrive_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleNoDrive_release_objsdir),, $@))), $(SnippetVehicleNoDrive_ccfiles)))
	@cp $(SnippetVehicleNoDrive_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleNoDrive_release_objsdir),, $@))), $(SnippetVehicleNoDrive_ccfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleNoDrive_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleNoDrive_release_objsdir),, $@))), $(SnippetVehicleNoDrive_ccfiles))))).release.P; \
	  rm -f $(SnippetVehicleNoDrive_release_DEPDIR).d

clean_SnippetVehicleNoDrive:  clean_SnippetVehicleNoDrive_debug clean_SnippetVehicleNoDrive_checked clean_SnippetVehicleNoDrive_profile clean_SnippetVehicleNoDrive_release
	@rm -rf $(DEPSDIR)
