# Makefile generated by XPJ for ANDROID
-include Makefile.custom
ProjectName = SnippetExtension
SnippetExtension_cppfiles   += ./../../SnippetExtension/src/ExtPulleyJoint.cpp
SnippetExtension_cppfiles   += ./../../SnippetExtension/src/ExtPulleyJointBinaryExtension.cpp
SnippetExtension_cppfiles   += ./../../SnippetExtension/src/ExtPulleyJointPVD.cpp
SnippetExtension_cppfiles   += ./../../SnippetExtension/src/ExtPulleyJointRepXExtension.cpp
SnippetExtension_cppfiles   += ./../../SnippetExtension/src/ExtPulleyJointSolverPrep.cpp
SnippetExtension_cppfiles   += ./../../SnippetExtension/src/SnippetExtension.cpp
SnippetExtension_cppfiles   += ./../../SnippetExtension/src/PhysXMetaData/src/PxSnippetExtensionAutoGeneratedMetaDataObjects.cpp

SnippetExtension_cpp_debug_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.debug.P, $(SnippetExtension_cppfiles)))))
SnippetExtension_c_debug_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.debug.P, $(SnippetExtension_cfiles)))))
SnippetExtension_cc_debug_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.debug.P, $(SnippetExtension_ccfiles)))))
SnippetExtension_debug_dep      = $(SnippetExtension_cpp_debug_dep) $(SnippetExtension_cc_debug_dep) $(SnippetExtension_c_debug_dep)
-include $(SnippetExtension_debug_dep)
SnippetExtension_cpp_checked_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.checked.P, $(SnippetExtension_cppfiles)))))
SnippetExtension_c_checked_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.checked.P, $(SnippetExtension_cfiles)))))
SnippetExtension_cc_checked_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.checked.P, $(SnippetExtension_ccfiles)))))
SnippetExtension_checked_dep      = $(SnippetExtension_cpp_checked_dep) $(SnippetExtension_cc_checked_dep) $(SnippetExtension_c_checked_dep)
-include $(SnippetExtension_checked_dep)
SnippetExtension_cpp_profile_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.profile.P, $(SnippetExtension_cppfiles)))))
SnippetExtension_c_profile_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.profile.P, $(SnippetExtension_cfiles)))))
SnippetExtension_cc_profile_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.profile.P, $(SnippetExtension_ccfiles)))))
SnippetExtension_profile_dep      = $(SnippetExtension_cpp_profile_dep) $(SnippetExtension_cc_profile_dep) $(SnippetExtension_c_profile_dep)
-include $(SnippetExtension_profile_dep)
SnippetExtension_cpp_release_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.release.P, $(SnippetExtension_cppfiles)))))
SnippetExtension_c_release_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.release.P, $(SnippetExtension_cfiles)))))
SnippetExtension_cc_release_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.release.P, $(SnippetExtension_ccfiles)))))
SnippetExtension_release_dep      = $(SnippetExtension_cpp_release_dep) $(SnippetExtension_cc_release_dep) $(SnippetExtension_c_release_dep)
-include $(SnippetExtension_release_dep)
SnippetExtension_debug_hpaths    := 
SnippetExtension_debug_hpaths    += ./../../../Source/shared/general/shared
SnippetExtension_debug_hpaths    += ./../../../Include
SnippetExtension_debug_hpaths    += ./../../../Source/foundation/include
SnippetExtension_debug_hpaths    += ./../../../Source/Common/src
SnippetExtension_debug_hpaths    += ./../../../Source/GeomUtils/src
SnippetExtension_debug_hpaths    += ./../../../Source/GeomUtils/headers
SnippetExtension_debug_hpaths    += ./../../../Source/GeomUtils/include
SnippetExtension_debug_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetExtension_debug_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetExtension_debug_hpaths    += ./../../../Include/extensions
SnippetExtension_debug_hpaths    += ./../../../Include/foundation
SnippetExtension_debug_hpaths    += ./../../../Include/common
SnippetExtension_debug_hpaths    += ./../../../Include/pvd
SnippetExtension_debug_hpaths    += ./../../../Include/cloth
SnippetExtension_debug_hpaths    += ./../../../Include/physxvisualdebuggersdk
SnippetExtension_debug_hpaths    += ./../../../Include/physxprofilesdk
SnippetExtension_debug_hpaths    += ./../../../Include/geometry
SnippetExtension_debug_hpaths    += ./../../../Source/PvdRuntime/src
SnippetExtension_debug_hpaths    += ./../../../Source/PhysXProfileSDK
SnippetExtension_debug_hpaths    += ./../../../Source/PhysXMetaData/core/include
SnippetExtension_debug_hpaths    += ./../../../Source/PhysXMetaData/extensions/include
SnippetExtension_debug_hpaths    += ./../../../Source/PhysXExtensions/src/serialization/Xml
SnippetExtension_debug_hpaths    += ./../../../Source/PhysXExtensions/src
SnippetExtension_debug_hpaths    += ./../../SnippetExtension/include
SnippetExtension_debug_hpaths    += ./../../SnippetExtension/src
SnippetExtension_debug_hpaths    += ./../../SnippetExtension/src/PhysXMetaData/include
SnippetExtension_debug_hpaths    += ./../../SnippetExtension/src/PhysXMetaData/src
SnippetExtension_debug_hpaths    += ./../../SnippetExtension/PhysXMetaDataGenerator
SnippetExtension_debug_lpaths    := 
SnippetExtension_debug_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetExtension_debug_lpaths    += ./../../../Lib/android9_neon
SnippetExtension_debug_defines   := $(SnippetExtension_custom_defines)
SnippetExtension_debug_defines   += ANDROID
SnippetExtension_debug_defines   += GLES2
SnippetExtension_debug_defines   += __ARM_ARCH_5__
SnippetExtension_debug_defines   += __ARM_ARCH_5T__
SnippetExtension_debug_defines   += __ARM_ARCH_5E__
SnippetExtension_debug_defines   += __ARM_ARCH_5TE__
SnippetExtension_debug_defines   += _DEBUG
SnippetExtension_debug_defines   += PX_DEBUG
SnippetExtension_debug_defines   += PX_CHECKED
SnippetExtension_debug_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetExtension_debug_defines   += PX_NVTX
SnippetExtension_debug_defines   += PHYSX_PROFILE_SDK
SnippetExtension_debug_libraries := 
SnippetExtension_debug_libraries += log
SnippetExtension_debug_libraries += gnustl_static
SnippetExtension_debug_libraries += supc++
SnippetExtension_debug_libraries += m
SnippetExtension_debug_libraries += c
SnippetExtension_debug_libraries += nvToolsExt
SnippetExtension_debug_libraries += PhysX3CommonCHECKED
SnippetExtension_debug_libraries += PvdRuntimeCHECKED
SnippetExtension_debug_libraries += SimulationControllerCHECKED
SnippetExtension_debug_libraries += SceneQueryCHECKED
SnippetExtension_debug_libraries += LowLevelCHECKED
SnippetExtension_debug_libraries += LowLevelClothCHECKED
SnippetExtension_debug_libraries += PhysX3CHECKED
SnippetExtension_debug_libraries += PhysX3VehicleCHECKED
SnippetExtension_debug_libraries += PhysX3CookingCHECKED
SnippetExtension_debug_libraries += PhysX3ExtensionsCHECKED
SnippetExtension_debug_libraries += PhysX3CharacterKinematicCHECKED
SnippetExtension_debug_libraries += PhysXProfileSDKCHECKED
SnippetExtension_debug_libraries += PxTaskCHECKED
SnippetExtension_debug_libraries += PhysXVisualDebuggerSDKCHECKED
SnippetExtension_debug_common_cflags	:= $(SnippetExtension_custom_cflags)
SnippetExtension_debug_common_cflags    += -MMD
SnippetExtension_debug_common_cflags    += $(addprefix -D, $(SnippetExtension_debug_defines))
SnippetExtension_debug_common_cflags    += $(addprefix -I, $(SnippetExtension_debug_hpaths))
SnippetExtension_debug_cflags	:= $(SnippetExtension_debug_common_cflags)
SnippetExtension_debug_cflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetExtension_debug_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetExtension_debug_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetExtension_debug_cflags  += -g3 -gdwarf-2
SnippetExtension_debug_cppflags	:= $(SnippetExtension_debug_common_cflags)
SnippetExtension_debug_cppflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetExtension_debug_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetExtension_debug_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetExtension_debug_cppflags  += -g3 -gdwarf-2
SnippetExtension_debug_lflags    := $(SnippetExtension_custom_lflags)
SnippetExtension_debug_lflags    += $(addprefix -L, $(SnippetExtension_debug_lpaths))
SnippetExtension_debug_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetExtension_debug_libraries)) -Wl,--end-group
SnippetExtension_debug_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetExtension_debug_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetExtension_debug_objsdir  = $(OBJS_DIR)/SnippetExtension_debug
SnippetExtension_debug_cpp_o    = $(addprefix $(SnippetExtension_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetExtension_cppfiles)))))
SnippetExtension_debug_c_o      = $(addprefix $(SnippetExtension_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetExtension_cfiles)))))
SnippetExtension_debug_cc_o      = $(addprefix $(SnippetExtension_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetExtension_ccfiles)))))
SnippetExtension_debug_obj      = $(SnippetExtension_debug_cpp_o) $(SnippetExtension_debug_cc_o) $(SnippetExtension_debug_c_o)
SnippetExtension_debug_bin      := ./../../../Bin/android9_neon/SnippetExtensionDEBUG

clean_SnippetExtension_debug: 
	@$(ECHO) clean SnippetExtension debug
	@$(RMDIR) $(SnippetExtension_debug_objsdir)
	@$(RMDIR) $(SnippetExtension_debug_bin)

build_SnippetExtension_debug: postbuild_SnippetExtension_debug
postbuild_SnippetExtension_debug: mainbuild_SnippetExtension_debug
mainbuild_SnippetExtension_debug: prebuild_SnippetExtension_debug $(SnippetExtension_debug_bin)
prebuild_SnippetExtension_debug:

$(SnippetExtension_debug_bin): $(SnippetExtension_debug_obj) 
	@mkdir -p `dirname ./../../../Bin/android9_neon/SnippetExtensionDEBUG`
	@$(CCLD) $(SnippetExtension_debug_obj) $(SnippetExtension_debug_lflags) -o $(SnippetExtension_debug_bin) 
	@$(ECHO) building $@ complete!

SnippetExtension_debug_DEPDIR = $(dir $(@))/$(*F)
$(SnippetExtension_debug_cpp_o): $(SnippetExtension_debug_objsdir)/%.o:
	@$(ECHO) SnippetExtension: compiling debug $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetExtension_debug_objsdir),, $@))), $(SnippetExtension_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetExtension_debug_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetExtension_debug_objsdir),, $@))), $(SnippetExtension_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetExtension_debug_objsdir),, $@))), $(SnippetExtension_cppfiles))))))
	@cp $(SnippetExtension_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetExtension_debug_objsdir),, $@))), $(SnippetExtension_cppfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetExtension_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetExtension_debug_objsdir),, $@))), $(SnippetExtension_cppfiles))))).debug.P; \
	  rm -f $(SnippetExtension_debug_DEPDIR).d

$(SnippetExtension_debug_c_o): $(SnippetExtension_debug_objsdir)/%.o:
	@$(ECHO) SnippetExtension: compiling debug $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetExtension_debug_objsdir),, $@))), $(SnippetExtension_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetExtension_debug_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetExtension_debug_objsdir),, $@))), $(SnippetExtension_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetExtension_debug_objsdir),, $@))), $(SnippetExtension_cfiles))))))
	@cp $(SnippetExtension_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetExtension_debug_objsdir),, $@))), $(SnippetExtension_cfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetExtension_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetExtension_debug_objsdir),, $@))), $(SnippetExtension_cfiles))))).debug.P; \
	  rm -f $(SnippetExtension_debug_DEPDIR).d

$(SnippetExtension_debug_cc_o): $(SnippetExtension_debug_objsdir)/%.o:
	@$(ECHO) SnippetExtension: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetExtension_debug_objsdir),, $@))), $(SnippetExtension_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetExtension_debug_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetExtension_debug_objsdir),, $@))), $(SnippetExtension_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetExtension_debug_objsdir),, $@))), $(SnippetExtension_ccfiles)))
	@cp $(SnippetExtension_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetExtension_debug_objsdir),, $@))), $(SnippetExtension_ccfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetExtension_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetExtension_debug_objsdir),, $@))), $(SnippetExtension_ccfiles))))).debug.P; \
	  rm -f $(SnippetExtension_debug_DEPDIR).d

SnippetExtension_checked_hpaths    := 
SnippetExtension_checked_hpaths    += ./../../../Source/shared/general/shared
SnippetExtension_checked_hpaths    += ./../../../Include
SnippetExtension_checked_hpaths    += ./../../../Source/foundation/include
SnippetExtension_checked_hpaths    += ./../../../Source/Common/src
SnippetExtension_checked_hpaths    += ./../../../Source/GeomUtils/src
SnippetExtension_checked_hpaths    += ./../../../Source/GeomUtils/headers
SnippetExtension_checked_hpaths    += ./../../../Source/GeomUtils/include
SnippetExtension_checked_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetExtension_checked_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetExtension_checked_hpaths    += ./../../../Include/extensions
SnippetExtension_checked_hpaths    += ./../../../Include/foundation
SnippetExtension_checked_hpaths    += ./../../../Include/common
SnippetExtension_checked_hpaths    += ./../../../Include/pvd
SnippetExtension_checked_hpaths    += ./../../../Include/cloth
SnippetExtension_checked_hpaths    += ./../../../Include/physxvisualdebuggersdk
SnippetExtension_checked_hpaths    += ./../../../Include/physxprofilesdk
SnippetExtension_checked_hpaths    += ./../../../Include/geometry
SnippetExtension_checked_hpaths    += ./../../../Source/PvdRuntime/src
SnippetExtension_checked_hpaths    += ./../../../Source/PhysXProfileSDK
SnippetExtension_checked_hpaths    += ./../../../Source/PhysXMetaData/core/include
SnippetExtension_checked_hpaths    += ./../../../Source/PhysXMetaData/extensions/include
SnippetExtension_checked_hpaths    += ./../../../Source/PhysXExtensions/src/serialization/Xml
SnippetExtension_checked_hpaths    += ./../../../Source/PhysXExtensions/src
SnippetExtension_checked_hpaths    += ./../../SnippetExtension/include
SnippetExtension_checked_hpaths    += ./../../SnippetExtension/src
SnippetExtension_checked_hpaths    += ./../../SnippetExtension/src/PhysXMetaData/include
SnippetExtension_checked_hpaths    += ./../../SnippetExtension/src/PhysXMetaData/src
SnippetExtension_checked_hpaths    += ./../../SnippetExtension/PhysXMetaDataGenerator
SnippetExtension_checked_lpaths    := 
SnippetExtension_checked_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetExtension_checked_lpaths    += ./../../../Lib/android9_neon
SnippetExtension_checked_defines   := $(SnippetExtension_custom_defines)
SnippetExtension_checked_defines   += ANDROID
SnippetExtension_checked_defines   += GLES2
SnippetExtension_checked_defines   += __ARM_ARCH_5__
SnippetExtension_checked_defines   += __ARM_ARCH_5T__
SnippetExtension_checked_defines   += __ARM_ARCH_5E__
SnippetExtension_checked_defines   += __ARM_ARCH_5TE__
SnippetExtension_checked_defines   += NDEBUG
SnippetExtension_checked_defines   += PX_CHECKED
SnippetExtension_checked_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetExtension_checked_defines   += PX_NVTX
SnippetExtension_checked_defines   += PHYSX_PROFILE_SDK
SnippetExtension_checked_libraries := 
SnippetExtension_checked_libraries += log
SnippetExtension_checked_libraries += gnustl_static
SnippetExtension_checked_libraries += supc++
SnippetExtension_checked_libraries += m
SnippetExtension_checked_libraries += c
SnippetExtension_checked_libraries += nvToolsExt
SnippetExtension_checked_libraries += PhysX3CommonCHECKED
SnippetExtension_checked_libraries += PvdRuntimeCHECKED
SnippetExtension_checked_libraries += SimulationControllerCHECKED
SnippetExtension_checked_libraries += SceneQueryCHECKED
SnippetExtension_checked_libraries += LowLevelCHECKED
SnippetExtension_checked_libraries += LowLevelClothCHECKED
SnippetExtension_checked_libraries += PhysX3CHECKED
SnippetExtension_checked_libraries += PhysX3VehicleCHECKED
SnippetExtension_checked_libraries += PhysX3CookingCHECKED
SnippetExtension_checked_libraries += PhysX3ExtensionsCHECKED
SnippetExtension_checked_libraries += PhysX3CharacterKinematicCHECKED
SnippetExtension_checked_libraries += PhysXProfileSDKCHECKED
SnippetExtension_checked_libraries += PxTaskCHECKED
SnippetExtension_checked_libraries += PhysXVisualDebuggerSDKCHECKED
SnippetExtension_checked_common_cflags	:= $(SnippetExtension_custom_cflags)
SnippetExtension_checked_common_cflags    += -MMD
SnippetExtension_checked_common_cflags    += $(addprefix -D, $(SnippetExtension_checked_defines))
SnippetExtension_checked_common_cflags    += $(addprefix -I, $(SnippetExtension_checked_hpaths))
SnippetExtension_checked_cflags	:= $(SnippetExtension_checked_common_cflags)
SnippetExtension_checked_cflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetExtension_checked_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetExtension_checked_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetExtension_checked_cflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
SnippetExtension_checked_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetExtension_checked_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetExtension_checked_cppflags	:= $(SnippetExtension_checked_common_cflags)
SnippetExtension_checked_cppflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetExtension_checked_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetExtension_checked_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetExtension_checked_cppflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
SnippetExtension_checked_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetExtension_checked_cppflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetExtension_checked_lflags    := $(SnippetExtension_custom_lflags)
SnippetExtension_checked_lflags    += $(addprefix -L, $(SnippetExtension_checked_lpaths))
SnippetExtension_checked_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetExtension_checked_libraries)) -Wl,--end-group
SnippetExtension_checked_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetExtension_checked_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetExtension_checked_objsdir  = $(OBJS_DIR)/SnippetExtension_checked
SnippetExtension_checked_cpp_o    = $(addprefix $(SnippetExtension_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetExtension_cppfiles)))))
SnippetExtension_checked_c_o      = $(addprefix $(SnippetExtension_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetExtension_cfiles)))))
SnippetExtension_checked_cc_o      = $(addprefix $(SnippetExtension_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetExtension_ccfiles)))))
SnippetExtension_checked_obj      = $(SnippetExtension_checked_cpp_o) $(SnippetExtension_checked_cc_o) $(SnippetExtension_checked_c_o)
SnippetExtension_checked_bin      := ./../../../Bin/android9_neon/SnippetExtensionCHECKED

clean_SnippetExtension_checked: 
	@$(ECHO) clean SnippetExtension checked
	@$(RMDIR) $(SnippetExtension_checked_objsdir)
	@$(RMDIR) $(SnippetExtension_checked_bin)

build_SnippetExtension_checked: postbuild_SnippetExtension_checked
postbuild_SnippetExtension_checked: mainbuild_SnippetExtension_checked
mainbuild_SnippetExtension_checked: prebuild_SnippetExtension_checked $(SnippetExtension_checked_bin)
prebuild_SnippetExtension_checked:

$(SnippetExtension_checked_bin): $(SnippetExtension_checked_obj) 
	@mkdir -p `dirname ./../../../Bin/android9_neon/SnippetExtensionCHECKED`
	@$(CCLD) $(SnippetExtension_checked_obj) $(SnippetExtension_checked_lflags) -o $(SnippetExtension_checked_bin) 
	@$(ECHO) building $@ complete!

SnippetExtension_checked_DEPDIR = $(dir $(@))/$(*F)
$(SnippetExtension_checked_cpp_o): $(SnippetExtension_checked_objsdir)/%.o:
	@$(ECHO) SnippetExtension: compiling checked $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetExtension_checked_objsdir),, $@))), $(SnippetExtension_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetExtension_checked_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetExtension_checked_objsdir),, $@))), $(SnippetExtension_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetExtension_checked_objsdir),, $@))), $(SnippetExtension_cppfiles))))))
	@cp $(SnippetExtension_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetExtension_checked_objsdir),, $@))), $(SnippetExtension_cppfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetExtension_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetExtension_checked_objsdir),, $@))), $(SnippetExtension_cppfiles))))).checked.P; \
	  rm -f $(SnippetExtension_checked_DEPDIR).d

$(SnippetExtension_checked_c_o): $(SnippetExtension_checked_objsdir)/%.o:
	@$(ECHO) SnippetExtension: compiling checked $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetExtension_checked_objsdir),, $@))), $(SnippetExtension_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetExtension_checked_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetExtension_checked_objsdir),, $@))), $(SnippetExtension_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetExtension_checked_objsdir),, $@))), $(SnippetExtension_cfiles))))))
	@cp $(SnippetExtension_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetExtension_checked_objsdir),, $@))), $(SnippetExtension_cfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetExtension_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetExtension_checked_objsdir),, $@))), $(SnippetExtension_cfiles))))).checked.P; \
	  rm -f $(SnippetExtension_checked_DEPDIR).d

$(SnippetExtension_checked_cc_o): $(SnippetExtension_checked_objsdir)/%.o:
	@$(ECHO) SnippetExtension: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetExtension_checked_objsdir),, $@))), $(SnippetExtension_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetExtension_checked_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetExtension_checked_objsdir),, $@))), $(SnippetExtension_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetExtension_checked_objsdir),, $@))), $(SnippetExtension_ccfiles)))
	@cp $(SnippetExtension_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetExtension_checked_objsdir),, $@))), $(SnippetExtension_ccfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetExtension_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetExtension_checked_objsdir),, $@))), $(SnippetExtension_ccfiles))))).checked.P; \
	  rm -f $(SnippetExtension_checked_DEPDIR).d

SnippetExtension_profile_hpaths    := 
SnippetExtension_profile_hpaths    += ./../../../Source/shared/general/shared
SnippetExtension_profile_hpaths    += ./../../../Include
SnippetExtension_profile_hpaths    += ./../../../Source/foundation/include
SnippetExtension_profile_hpaths    += ./../../../Source/Common/src
SnippetExtension_profile_hpaths    += ./../../../Source/GeomUtils/src
SnippetExtension_profile_hpaths    += ./../../../Source/GeomUtils/headers
SnippetExtension_profile_hpaths    += ./../../../Source/GeomUtils/include
SnippetExtension_profile_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetExtension_profile_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetExtension_profile_hpaths    += ./../../../Include/extensions
SnippetExtension_profile_hpaths    += ./../../../Include/foundation
SnippetExtension_profile_hpaths    += ./../../../Include/common
SnippetExtension_profile_hpaths    += ./../../../Include/pvd
SnippetExtension_profile_hpaths    += ./../../../Include/cloth
SnippetExtension_profile_hpaths    += ./../../../Include/physxvisualdebuggersdk
SnippetExtension_profile_hpaths    += ./../../../Include/physxprofilesdk
SnippetExtension_profile_hpaths    += ./../../../Include/geometry
SnippetExtension_profile_hpaths    += ./../../../Source/PvdRuntime/src
SnippetExtension_profile_hpaths    += ./../../../Source/PhysXProfileSDK
SnippetExtension_profile_hpaths    += ./../../../Source/PhysXMetaData/core/include
SnippetExtension_profile_hpaths    += ./../../../Source/PhysXMetaData/extensions/include
SnippetExtension_profile_hpaths    += ./../../../Source/PhysXExtensions/src/serialization/Xml
SnippetExtension_profile_hpaths    += ./../../../Source/PhysXExtensions/src
SnippetExtension_profile_hpaths    += ./../../SnippetExtension/include
SnippetExtension_profile_hpaths    += ./../../SnippetExtension/src
SnippetExtension_profile_hpaths    += ./../../SnippetExtension/src/PhysXMetaData/include
SnippetExtension_profile_hpaths    += ./../../SnippetExtension/src/PhysXMetaData/src
SnippetExtension_profile_hpaths    += ./../../SnippetExtension/PhysXMetaDataGenerator
SnippetExtension_profile_lpaths    := 
SnippetExtension_profile_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetExtension_profile_lpaths    += ./../../../Lib/android9_neon
SnippetExtension_profile_defines   := $(SnippetExtension_custom_defines)
SnippetExtension_profile_defines   += ANDROID
SnippetExtension_profile_defines   += GLES2
SnippetExtension_profile_defines   += __ARM_ARCH_5__
SnippetExtension_profile_defines   += __ARM_ARCH_5T__
SnippetExtension_profile_defines   += __ARM_ARCH_5E__
SnippetExtension_profile_defines   += __ARM_ARCH_5TE__
SnippetExtension_profile_defines   += NDEBUG
SnippetExtension_profile_defines   += PX_PROFILE
SnippetExtension_profile_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetExtension_profile_defines   += PX_NVTX
SnippetExtension_profile_defines   += PHYSX_PROFILE_SDK
SnippetExtension_profile_libraries := 
SnippetExtension_profile_libraries += log
SnippetExtension_profile_libraries += gnustl_static
SnippetExtension_profile_libraries += supc++
SnippetExtension_profile_libraries += m
SnippetExtension_profile_libraries += c
SnippetExtension_profile_libraries += nvToolsExt
SnippetExtension_profile_libraries += PhysX3CommonPROFILE
SnippetExtension_profile_libraries += PvdRuntimePROFILE
SnippetExtension_profile_libraries += SimulationControllerPROFILE
SnippetExtension_profile_libraries += SceneQueryPROFILE
SnippetExtension_profile_libraries += LowLevelPROFILE
SnippetExtension_profile_libraries += LowLevelClothPROFILE
SnippetExtension_profile_libraries += PhysX3PROFILE
SnippetExtension_profile_libraries += PhysX3VehiclePROFILE
SnippetExtension_profile_libraries += PhysX3CookingPROFILE
SnippetExtension_profile_libraries += PhysX3ExtensionsPROFILE
SnippetExtension_profile_libraries += PhysX3CharacterKinematicPROFILE
SnippetExtension_profile_libraries += PhysXProfileSDKPROFILE
SnippetExtension_profile_libraries += PxTaskPROFILE
SnippetExtension_profile_libraries += PhysXVisualDebuggerSDKPROFILE
SnippetExtension_profile_common_cflags	:= $(SnippetExtension_custom_cflags)
SnippetExtension_profile_common_cflags    += -MMD
SnippetExtension_profile_common_cflags    += $(addprefix -D, $(SnippetExtension_profile_defines))
SnippetExtension_profile_common_cflags    += $(addprefix -I, $(SnippetExtension_profile_hpaths))
SnippetExtension_profile_cflags	:= $(SnippetExtension_profile_common_cflags)
SnippetExtension_profile_cflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetExtension_profile_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetExtension_profile_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetExtension_profile_cflags  += -O3 -fno-strict-aliasing
SnippetExtension_profile_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetExtension_profile_cflags  += -fno-omit-frame-pointer -marm -funswitch-loops -finline-limit=300
SnippetExtension_profile_cppflags	:= $(SnippetExtension_profile_common_cflags)
SnippetExtension_profile_cppflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetExtension_profile_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetExtension_profile_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetExtension_profile_cppflags  += -O3 -fno-strict-aliasing
SnippetExtension_profile_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetExtension_profile_cppflags  += -fno-omit-frame-pointer -marm -funswitch-loops -finline-limit=300
SnippetExtension_profile_lflags    := $(SnippetExtension_custom_lflags)
SnippetExtension_profile_lflags    += $(addprefix -L, $(SnippetExtension_profile_lpaths))
SnippetExtension_profile_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetExtension_profile_libraries)) -Wl,--end-group
SnippetExtension_profile_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetExtension_profile_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetExtension_profile_objsdir  = $(OBJS_DIR)/SnippetExtension_profile
SnippetExtension_profile_cpp_o    = $(addprefix $(SnippetExtension_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetExtension_cppfiles)))))
SnippetExtension_profile_c_o      = $(addprefix $(SnippetExtension_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetExtension_cfiles)))))
SnippetExtension_profile_cc_o      = $(addprefix $(SnippetExtension_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetExtension_ccfiles)))))
SnippetExtension_profile_obj      = $(SnippetExtension_profile_cpp_o) $(SnippetExtension_profile_cc_o) $(SnippetExtension_profile_c_o)
SnippetExtension_profile_bin      := ./../../../Bin/android9_neon/SnippetExtensionPROFILE

clean_SnippetExtension_profile: 
	@$(ECHO) clean SnippetExtension profile
	@$(RMDIR) $(SnippetExtension_profile_objsdir)
	@$(RMDIR) $(SnippetExtension_profile_bin)

build_SnippetExtension_profile: postbuild_SnippetExtension_profile
postbuild_SnippetExtension_profile: mainbuild_SnippetExtension_profile
mainbuild_SnippetExtension_profile: prebuild_SnippetExtension_profile $(SnippetExtension_profile_bin)
prebuild_SnippetExtension_profile:

$(SnippetExtension_profile_bin): $(SnippetExtension_profile_obj) 
	@mkdir -p `dirname ./../../../Bin/android9_neon/SnippetExtensionPROFILE`
	@$(CCLD) $(SnippetExtension_profile_obj) $(SnippetExtension_profile_lflags) -o $(SnippetExtension_profile_bin) 
	@$(ECHO) building $@ complete!

SnippetExtension_profile_DEPDIR = $(dir $(@))/$(*F)
$(SnippetExtension_profile_cpp_o): $(SnippetExtension_profile_objsdir)/%.o:
	@$(ECHO) SnippetExtension: compiling profile $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetExtension_profile_objsdir),, $@))), $(SnippetExtension_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetExtension_profile_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetExtension_profile_objsdir),, $@))), $(SnippetExtension_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetExtension_profile_objsdir),, $@))), $(SnippetExtension_cppfiles))))))
	@cp $(SnippetExtension_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetExtension_profile_objsdir),, $@))), $(SnippetExtension_cppfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetExtension_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetExtension_profile_objsdir),, $@))), $(SnippetExtension_cppfiles))))).profile.P; \
	  rm -f $(SnippetExtension_profile_DEPDIR).d

$(SnippetExtension_profile_c_o): $(SnippetExtension_profile_objsdir)/%.o:
	@$(ECHO) SnippetExtension: compiling profile $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetExtension_profile_objsdir),, $@))), $(SnippetExtension_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetExtension_profile_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetExtension_profile_objsdir),, $@))), $(SnippetExtension_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetExtension_profile_objsdir),, $@))), $(SnippetExtension_cfiles))))))
	@cp $(SnippetExtension_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetExtension_profile_objsdir),, $@))), $(SnippetExtension_cfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetExtension_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetExtension_profile_objsdir),, $@))), $(SnippetExtension_cfiles))))).profile.P; \
	  rm -f $(SnippetExtension_profile_DEPDIR).d

$(SnippetExtension_profile_cc_o): $(SnippetExtension_profile_objsdir)/%.o:
	@$(ECHO) SnippetExtension: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetExtension_profile_objsdir),, $@))), $(SnippetExtension_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetExtension_profile_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetExtension_profile_objsdir),, $@))), $(SnippetExtension_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetExtension_profile_objsdir),, $@))), $(SnippetExtension_ccfiles)))
	@cp $(SnippetExtension_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetExtension_profile_objsdir),, $@))), $(SnippetExtension_ccfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetExtension_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetExtension_profile_objsdir),, $@))), $(SnippetExtension_ccfiles))))).profile.P; \
	  rm -f $(SnippetExtension_profile_DEPDIR).d

SnippetExtension_release_hpaths    := 
SnippetExtension_release_hpaths    += ./../../../Source/shared/general/shared
SnippetExtension_release_hpaths    += ./../../../Include
SnippetExtension_release_hpaths    += ./../../../Source/foundation/include
SnippetExtension_release_hpaths    += ./../../../Source/Common/src
SnippetExtension_release_hpaths    += ./../../../Source/GeomUtils/src
SnippetExtension_release_hpaths    += ./../../../Source/GeomUtils/headers
SnippetExtension_release_hpaths    += ./../../../Source/GeomUtils/include
SnippetExtension_release_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetExtension_release_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetExtension_release_hpaths    += ./../../../Include/extensions
SnippetExtension_release_hpaths    += ./../../../Include/foundation
SnippetExtension_release_hpaths    += ./../../../Include/common
SnippetExtension_release_hpaths    += ./../../../Include/pvd
SnippetExtension_release_hpaths    += ./../../../Include/cloth
SnippetExtension_release_hpaths    += ./../../../Include/physxvisualdebuggersdk
SnippetExtension_release_hpaths    += ./../../../Include/physxprofilesdk
SnippetExtension_release_hpaths    += ./../../../Include/geometry
SnippetExtension_release_hpaths    += ./../../../Source/PvdRuntime/src
SnippetExtension_release_hpaths    += ./../../../Source/PhysXProfileSDK
SnippetExtension_release_hpaths    += ./../../../Source/PhysXMetaData/core/include
SnippetExtension_release_hpaths    += ./../../../Source/PhysXMetaData/extensions/include
SnippetExtension_release_hpaths    += ./../../../Source/PhysXExtensions/src/serialization/Xml
SnippetExtension_release_hpaths    += ./../../../Source/PhysXExtensions/src
SnippetExtension_release_hpaths    += ./../../SnippetExtension/include
SnippetExtension_release_hpaths    += ./../../SnippetExtension/src
SnippetExtension_release_hpaths    += ./../../SnippetExtension/src/PhysXMetaData/include
SnippetExtension_release_hpaths    += ./../../SnippetExtension/src/PhysXMetaData/src
SnippetExtension_release_hpaths    += ./../../SnippetExtension/PhysXMetaDataGenerator
SnippetExtension_release_lpaths    := 
SnippetExtension_release_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetExtension_release_lpaths    += ./../../../Lib/android9_neon
SnippetExtension_release_defines   := $(SnippetExtension_custom_defines)
SnippetExtension_release_defines   += ANDROID
SnippetExtension_release_defines   += GLES2
SnippetExtension_release_defines   += __ARM_ARCH_5__
SnippetExtension_release_defines   += __ARM_ARCH_5T__
SnippetExtension_release_defines   += __ARM_ARCH_5E__
SnippetExtension_release_defines   += __ARM_ARCH_5TE__
SnippetExtension_release_defines   += NDEBUG
SnippetExtension_release_defines   += PHYSX_PROFILE_SDK
SnippetExtension_release_libraries := 
SnippetExtension_release_libraries += log
SnippetExtension_release_libraries += gnustl_static
SnippetExtension_release_libraries += supc++
SnippetExtension_release_libraries += m
SnippetExtension_release_libraries += c
SnippetExtension_release_libraries += nvToolsExt
SnippetExtension_release_libraries += PhysX3Common
SnippetExtension_release_libraries += PvdRuntime
SnippetExtension_release_libraries += SimulationController
SnippetExtension_release_libraries += SceneQuery
SnippetExtension_release_libraries += LowLevel
SnippetExtension_release_libraries += LowLevelCloth
SnippetExtension_release_libraries += PhysX3
SnippetExtension_release_libraries += PhysX3Vehicle
SnippetExtension_release_libraries += PhysX3Cooking
SnippetExtension_release_libraries += PhysX3Extensions
SnippetExtension_release_libraries += PhysX3CharacterKinematic
SnippetExtension_release_libraries += PhysXProfileSDK
SnippetExtension_release_libraries += PxTask
SnippetExtension_release_libraries += PhysXVisualDebuggerSDK
SnippetExtension_release_common_cflags	:= $(SnippetExtension_custom_cflags)
SnippetExtension_release_common_cflags    += -MMD
SnippetExtension_release_common_cflags    += $(addprefix -D, $(SnippetExtension_release_defines))
SnippetExtension_release_common_cflags    += $(addprefix -I, $(SnippetExtension_release_hpaths))
SnippetExtension_release_cflags	:= $(SnippetExtension_release_common_cflags)
SnippetExtension_release_cflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetExtension_release_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetExtension_release_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetExtension_release_cflags  += -O3 -fno-strict-aliasing
SnippetExtension_release_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetExtension_release_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetExtension_release_cppflags	:= $(SnippetExtension_release_common_cflags)
SnippetExtension_release_cppflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetExtension_release_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetExtension_release_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetExtension_release_cppflags  += -O3 -fno-strict-aliasing
SnippetExtension_release_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetExtension_release_cppflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetExtension_release_lflags    := $(SnippetExtension_custom_lflags)
SnippetExtension_release_lflags    += $(addprefix -L, $(SnippetExtension_release_lpaths))
SnippetExtension_release_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetExtension_release_libraries)) -Wl,--end-group
SnippetExtension_release_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetExtension_release_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetExtension_release_objsdir  = $(OBJS_DIR)/SnippetExtension_release
SnippetExtension_release_cpp_o    = $(addprefix $(SnippetExtension_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetExtension_cppfiles)))))
SnippetExtension_release_c_o      = $(addprefix $(SnippetExtension_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetExtension_cfiles)))))
SnippetExtension_release_cc_o      = $(addprefix $(SnippetExtension_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetExtension_ccfiles)))))
SnippetExtension_release_obj      = $(SnippetExtension_release_cpp_o) $(SnippetExtension_release_cc_o) $(SnippetExtension_release_c_o)
SnippetExtension_release_bin      := ./../../../Bin/android9_neon/SnippetExtension

clean_SnippetExtension_release: 
	@$(ECHO) clean SnippetExtension release
	@$(RMDIR) $(SnippetExtension_release_objsdir)
	@$(RMDIR) $(SnippetExtension_release_bin)

build_SnippetExtension_release: postbuild_SnippetExtension_release
postbuild_SnippetExtension_release: mainbuild_SnippetExtension_release
mainbuild_SnippetExtension_release: prebuild_SnippetExtension_release $(SnippetExtension_release_bin)
prebuild_SnippetExtension_release:

$(SnippetExtension_release_bin): $(SnippetExtension_release_obj) 
	@mkdir -p `dirname ./../../../Bin/android9_neon/SnippetExtension`
	@$(CCLD) $(SnippetExtension_release_obj) $(SnippetExtension_release_lflags) -o $(SnippetExtension_release_bin) 
	@$(ECHO) building $@ complete!

SnippetExtension_release_DEPDIR = $(dir $(@))/$(*F)
$(SnippetExtension_release_cpp_o): $(SnippetExtension_release_objsdir)/%.o:
	@$(ECHO) SnippetExtension: compiling release $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetExtension_release_objsdir),, $@))), $(SnippetExtension_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetExtension_release_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetExtension_release_objsdir),, $@))), $(SnippetExtension_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetExtension_release_objsdir),, $@))), $(SnippetExtension_cppfiles))))))
	@cp $(SnippetExtension_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetExtension_release_objsdir),, $@))), $(SnippetExtension_cppfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetExtension_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetExtension_release_objsdir),, $@))), $(SnippetExtension_cppfiles))))).release.P; \
	  rm -f $(SnippetExtension_release_DEPDIR).d

$(SnippetExtension_release_c_o): $(SnippetExtension_release_objsdir)/%.o:
	@$(ECHO) SnippetExtension: compiling release $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetExtension_release_objsdir),, $@))), $(SnippetExtension_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetExtension_release_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetExtension_release_objsdir),, $@))), $(SnippetExtension_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetExtension_release_objsdir),, $@))), $(SnippetExtension_cfiles))))))
	@cp $(SnippetExtension_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetExtension_release_objsdir),, $@))), $(SnippetExtension_cfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetExtension_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetExtension_release_objsdir),, $@))), $(SnippetExtension_cfiles))))).release.P; \
	  rm -f $(SnippetExtension_release_DEPDIR).d

$(SnippetExtension_release_cc_o): $(SnippetExtension_release_objsdir)/%.o:
	@$(ECHO) SnippetExtension: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetExtension_release_objsdir),, $@))), $(SnippetExtension_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetExtension_release_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetExtension_release_objsdir),, $@))), $(SnippetExtension_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetExtension_release_objsdir),, $@))), $(SnippetExtension_ccfiles)))
	@cp $(SnippetExtension_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetExtension_release_objsdir),, $@))), $(SnippetExtension_ccfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetExtension_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetExtension_release_objsdir),, $@))), $(SnippetExtension_ccfiles))))).release.P; \
	  rm -f $(SnippetExtension_release_DEPDIR).d

clean_SnippetExtension:  clean_SnippetExtension_debug clean_SnippetExtension_checked clean_SnippetExtension_profile clean_SnippetExtension_release
	@rm -rf $(DEPSDIR)
