# Makefile generated by XPJ for ANDROID
-include Makefile.custom
ProjectName = SnippetHelloWorld
SnippetHelloWorld_cppfiles   += ./../../SnippetHelloWorld/SnippetHelloWorld.cpp
SnippetHelloWorld_cppfiles   += ./../../SnippetHelloWorld/SnippetHelloWorldRender.cpp

SnippetHelloWorld_cpp_debug_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.debug.P, $(SnippetHelloWorld_cppfiles)))))
SnippetHelloWorld_c_debug_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.debug.P, $(SnippetHelloWorld_cfiles)))))
SnippetHelloWorld_cc_debug_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.debug.P, $(SnippetHelloWorld_ccfiles)))))
SnippetHelloWorld_debug_dep      = $(SnippetHelloWorld_cpp_debug_dep) $(SnippetHelloWorld_cc_debug_dep) $(SnippetHelloWorld_c_debug_dep)
-include $(SnippetHelloWorld_debug_dep)
SnippetHelloWorld_cpp_checked_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.checked.P, $(SnippetHelloWorld_cppfiles)))))
SnippetHelloWorld_c_checked_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.checked.P, $(SnippetHelloWorld_cfiles)))))
SnippetHelloWorld_cc_checked_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.checked.P, $(SnippetHelloWorld_ccfiles)))))
SnippetHelloWorld_checked_dep      = $(SnippetHelloWorld_cpp_checked_dep) $(SnippetHelloWorld_cc_checked_dep) $(SnippetHelloWorld_c_checked_dep)
-include $(SnippetHelloWorld_checked_dep)
SnippetHelloWorld_cpp_profile_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.profile.P, $(SnippetHelloWorld_cppfiles)))))
SnippetHelloWorld_c_profile_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.profile.P, $(SnippetHelloWorld_cfiles)))))
SnippetHelloWorld_cc_profile_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.profile.P, $(SnippetHelloWorld_ccfiles)))))
SnippetHelloWorld_profile_dep      = $(SnippetHelloWorld_cpp_profile_dep) $(SnippetHelloWorld_cc_profile_dep) $(SnippetHelloWorld_c_profile_dep)
-include $(SnippetHelloWorld_profile_dep)
SnippetHelloWorld_cpp_release_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.release.P, $(SnippetHelloWorld_cppfiles)))))
SnippetHelloWorld_c_release_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.release.P, $(SnippetHelloWorld_cfiles)))))
SnippetHelloWorld_cc_release_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.release.P, $(SnippetHelloWorld_ccfiles)))))
SnippetHelloWorld_release_dep      = $(SnippetHelloWorld_cpp_release_dep) $(SnippetHelloWorld_cc_release_dep) $(SnippetHelloWorld_c_release_dep)
-include $(SnippetHelloWorld_release_dep)
SnippetHelloWorld_debug_hpaths    := 
SnippetHelloWorld_debug_hpaths    += ./../../../Source/shared/general/shared
SnippetHelloWorld_debug_hpaths    += ./../../../Include
SnippetHelloWorld_debug_hpaths    += ./../../../Source/foundation/include
SnippetHelloWorld_debug_hpaths    += ./../../../Source/Common/src
SnippetHelloWorld_debug_hpaths    += ./../../../Source/GeomUtils/src
SnippetHelloWorld_debug_hpaths    += ./../../../Source/GeomUtils/headers
SnippetHelloWorld_debug_hpaths    += ./../../../Source/GeomUtils/include
SnippetHelloWorld_debug_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetHelloWorld_debug_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetHelloWorld_debug_lpaths    := 
SnippetHelloWorld_debug_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetHelloWorld_debug_lpaths    += ./../../../Lib/android9_neon
SnippetHelloWorld_debug_defines   := $(SnippetHelloWorld_custom_defines)
SnippetHelloWorld_debug_defines   += ANDROID
SnippetHelloWorld_debug_defines   += GLES2
SnippetHelloWorld_debug_defines   += __ARM_ARCH_5__
SnippetHelloWorld_debug_defines   += __ARM_ARCH_5T__
SnippetHelloWorld_debug_defines   += __ARM_ARCH_5E__
SnippetHelloWorld_debug_defines   += __ARM_ARCH_5TE__
SnippetHelloWorld_debug_defines   += _DEBUG
SnippetHelloWorld_debug_defines   += PX_DEBUG
SnippetHelloWorld_debug_defines   += PX_CHECKED
SnippetHelloWorld_debug_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetHelloWorld_debug_defines   += PX_NVTX
SnippetHelloWorld_debug_defines   += PHYSX_PROFILE_SDK
SnippetHelloWorld_debug_libraries := 
SnippetHelloWorld_debug_libraries += log
SnippetHelloWorld_debug_libraries += gnustl_static
SnippetHelloWorld_debug_libraries += supc++
SnippetHelloWorld_debug_libraries += m
SnippetHelloWorld_debug_libraries += c
SnippetHelloWorld_debug_libraries += nvToolsExt
SnippetHelloWorld_debug_libraries += PhysX3CommonCHECKED
SnippetHelloWorld_debug_libraries += PvdRuntimeCHECKED
SnippetHelloWorld_debug_libraries += SimulationControllerCHECKED
SnippetHelloWorld_debug_libraries += SceneQueryCHECKED
SnippetHelloWorld_debug_libraries += LowLevelCHECKED
SnippetHelloWorld_debug_libraries += LowLevelClothCHECKED
SnippetHelloWorld_debug_libraries += PhysX3CHECKED
SnippetHelloWorld_debug_libraries += PhysX3VehicleCHECKED
SnippetHelloWorld_debug_libraries += PhysX3CookingCHECKED
SnippetHelloWorld_debug_libraries += PhysX3ExtensionsCHECKED
SnippetHelloWorld_debug_libraries += PhysX3CharacterKinematicCHECKED
SnippetHelloWorld_debug_libraries += PhysXProfileSDKCHECKED
SnippetHelloWorld_debug_libraries += PxTaskCHECKED
SnippetHelloWorld_debug_libraries += PhysXVisualDebuggerSDKCHECKED
SnippetHelloWorld_debug_common_cflags	:= $(SnippetHelloWorld_custom_cflags)
SnippetHelloWorld_debug_common_cflags    += -MMD
SnippetHelloWorld_debug_common_cflags    += $(addprefix -D, $(SnippetHelloWorld_debug_defines))
SnippetHelloWorld_debug_common_cflags    += $(addprefix -I, $(SnippetHelloWorld_debug_hpaths))
SnippetHelloWorld_debug_cflags	:= $(SnippetHelloWorld_debug_common_cflags)
SnippetHelloWorld_debug_cflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetHelloWorld_debug_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetHelloWorld_debug_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetHelloWorld_debug_cflags  += -g3 -gdwarf-2
SnippetHelloWorld_debug_cppflags	:= $(SnippetHelloWorld_debug_common_cflags)
SnippetHelloWorld_debug_cppflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetHelloWorld_debug_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetHelloWorld_debug_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetHelloWorld_debug_cppflags  += -g3 -gdwarf-2
SnippetHelloWorld_debug_lflags    := $(SnippetHelloWorld_custom_lflags)
SnippetHelloWorld_debug_lflags    += $(addprefix -L, $(SnippetHelloWorld_debug_lpaths))
SnippetHelloWorld_debug_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetHelloWorld_debug_libraries)) -Wl,--end-group
SnippetHelloWorld_debug_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetHelloWorld_debug_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetHelloWorld_debug_objsdir  = $(OBJS_DIR)/SnippetHelloWorld_debug
SnippetHelloWorld_debug_cpp_o    = $(addprefix $(SnippetHelloWorld_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetHelloWorld_cppfiles)))))
SnippetHelloWorld_debug_c_o      = $(addprefix $(SnippetHelloWorld_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetHelloWorld_cfiles)))))
SnippetHelloWorld_debug_cc_o      = $(addprefix $(SnippetHelloWorld_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetHelloWorld_ccfiles)))))
SnippetHelloWorld_debug_obj      = $(SnippetHelloWorld_debug_cpp_o) $(SnippetHelloWorld_debug_cc_o) $(SnippetHelloWorld_debug_c_o)
SnippetHelloWorld_debug_bin      := ./../../../Bin/android9_neon/SnippetHelloWorldDEBUG

clean_SnippetHelloWorld_debug: 
	@$(ECHO) clean SnippetHelloWorld debug
	@$(RMDIR) $(SnippetHelloWorld_debug_objsdir)
	@$(RMDIR) $(SnippetHelloWorld_debug_bin)

build_SnippetHelloWorld_debug: postbuild_SnippetHelloWorld_debug
postbuild_SnippetHelloWorld_debug: mainbuild_SnippetHelloWorld_debug
mainbuild_SnippetHelloWorld_debug: prebuild_SnippetHelloWorld_debug $(SnippetHelloWorld_debug_bin)
prebuild_SnippetHelloWorld_debug:

$(SnippetHelloWorld_debug_bin): $(SnippetHelloWorld_debug_obj) 
	@mkdir -p `dirname ./../../../Bin/android9_neon/SnippetHelloWorldDEBUG`
	@$(CCLD) $(SnippetHelloWorld_debug_obj) $(SnippetHelloWorld_debug_lflags) -o $(SnippetHelloWorld_debug_bin) 
	@$(ECHO) building $@ complete!

SnippetHelloWorld_debug_DEPDIR = $(dir $(@))/$(*F)
$(SnippetHelloWorld_debug_cpp_o): $(SnippetHelloWorld_debug_objsdir)/%.o:
	@$(ECHO) SnippetHelloWorld: compiling debug $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetHelloWorld_debug_objsdir),, $@))), $(SnippetHelloWorld_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetHelloWorld_debug_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetHelloWorld_debug_objsdir),, $@))), $(SnippetHelloWorld_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetHelloWorld_debug_objsdir),, $@))), $(SnippetHelloWorld_cppfiles))))))
	@cp $(SnippetHelloWorld_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetHelloWorld_debug_objsdir),, $@))), $(SnippetHelloWorld_cppfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetHelloWorld_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetHelloWorld_debug_objsdir),, $@))), $(SnippetHelloWorld_cppfiles))))).debug.P; \
	  rm -f $(SnippetHelloWorld_debug_DEPDIR).d

$(SnippetHelloWorld_debug_c_o): $(SnippetHelloWorld_debug_objsdir)/%.o:
	@$(ECHO) SnippetHelloWorld: compiling debug $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetHelloWorld_debug_objsdir),, $@))), $(SnippetHelloWorld_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetHelloWorld_debug_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetHelloWorld_debug_objsdir),, $@))), $(SnippetHelloWorld_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetHelloWorld_debug_objsdir),, $@))), $(SnippetHelloWorld_cfiles))))))
	@cp $(SnippetHelloWorld_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetHelloWorld_debug_objsdir),, $@))), $(SnippetHelloWorld_cfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetHelloWorld_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetHelloWorld_debug_objsdir),, $@))), $(SnippetHelloWorld_cfiles))))).debug.P; \
	  rm -f $(SnippetHelloWorld_debug_DEPDIR).d

$(SnippetHelloWorld_debug_cc_o): $(SnippetHelloWorld_debug_objsdir)/%.o:
	@$(ECHO) SnippetHelloWorld: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetHelloWorld_debug_objsdir),, $@))), $(SnippetHelloWorld_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetHelloWorld_debug_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetHelloWorld_debug_objsdir),, $@))), $(SnippetHelloWorld_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetHelloWorld_debug_objsdir),, $@))), $(SnippetHelloWorld_ccfiles)))
	@cp $(SnippetHelloWorld_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetHelloWorld_debug_objsdir),, $@))), $(SnippetHelloWorld_ccfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetHelloWorld_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetHelloWorld_debug_objsdir),, $@))), $(SnippetHelloWorld_ccfiles))))).debug.P; \
	  rm -f $(SnippetHelloWorld_debug_DEPDIR).d

SnippetHelloWorld_checked_hpaths    := 
SnippetHelloWorld_checked_hpaths    += ./../../../Source/shared/general/shared
SnippetHelloWorld_checked_hpaths    += ./../../../Include
SnippetHelloWorld_checked_hpaths    += ./../../../Source/foundation/include
SnippetHelloWorld_checked_hpaths    += ./../../../Source/Common/src
SnippetHelloWorld_checked_hpaths    += ./../../../Source/GeomUtils/src
SnippetHelloWorld_checked_hpaths    += ./../../../Source/GeomUtils/headers
SnippetHelloWorld_checked_hpaths    += ./../../../Source/GeomUtils/include
SnippetHelloWorld_checked_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetHelloWorld_checked_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetHelloWorld_checked_lpaths    := 
SnippetHelloWorld_checked_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetHelloWorld_checked_lpaths    += ./../../../Lib/android9_neon
SnippetHelloWorld_checked_defines   := $(SnippetHelloWorld_custom_defines)
SnippetHelloWorld_checked_defines   += ANDROID
SnippetHelloWorld_checked_defines   += GLES2
SnippetHelloWorld_checked_defines   += __ARM_ARCH_5__
SnippetHelloWorld_checked_defines   += __ARM_ARCH_5T__
SnippetHelloWorld_checked_defines   += __ARM_ARCH_5E__
SnippetHelloWorld_checked_defines   += __ARM_ARCH_5TE__
SnippetHelloWorld_checked_defines   += NDEBUG
SnippetHelloWorld_checked_defines   += PX_CHECKED
SnippetHelloWorld_checked_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetHelloWorld_checked_defines   += PX_NVTX
SnippetHelloWorld_checked_defines   += PHYSX_PROFILE_SDK
SnippetHelloWorld_checked_libraries := 
SnippetHelloWorld_checked_libraries += log
SnippetHelloWorld_checked_libraries += gnustl_static
SnippetHelloWorld_checked_libraries += supc++
SnippetHelloWorld_checked_libraries += m
SnippetHelloWorld_checked_libraries += c
SnippetHelloWorld_checked_libraries += nvToolsExt
SnippetHelloWorld_checked_libraries += PhysX3CommonCHECKED
SnippetHelloWorld_checked_libraries += PvdRuntimeCHECKED
SnippetHelloWorld_checked_libraries += SimulationControllerCHECKED
SnippetHelloWorld_checked_libraries += SceneQueryCHECKED
SnippetHelloWorld_checked_libraries += LowLevelCHECKED
SnippetHelloWorld_checked_libraries += LowLevelClothCHECKED
SnippetHelloWorld_checked_libraries += PhysX3CHECKED
SnippetHelloWorld_checked_libraries += PhysX3VehicleCHECKED
SnippetHelloWorld_checked_libraries += PhysX3CookingCHECKED
SnippetHelloWorld_checked_libraries += PhysX3ExtensionsCHECKED
SnippetHelloWorld_checked_libraries += PhysX3CharacterKinematicCHECKED
SnippetHelloWorld_checked_libraries += PhysXProfileSDKCHECKED
SnippetHelloWorld_checked_libraries += PxTaskCHECKED
SnippetHelloWorld_checked_libraries += PhysXVisualDebuggerSDKCHECKED
SnippetHelloWorld_checked_common_cflags	:= $(SnippetHelloWorld_custom_cflags)
SnippetHelloWorld_checked_common_cflags    += -MMD
SnippetHelloWorld_checked_common_cflags    += $(addprefix -D, $(SnippetHelloWorld_checked_defines))
SnippetHelloWorld_checked_common_cflags    += $(addprefix -I, $(SnippetHelloWorld_checked_hpaths))
SnippetHelloWorld_checked_cflags	:= $(SnippetHelloWorld_checked_common_cflags)
SnippetHelloWorld_checked_cflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetHelloWorld_checked_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetHelloWorld_checked_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetHelloWorld_checked_cflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
SnippetHelloWorld_checked_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetHelloWorld_checked_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetHelloWorld_checked_cppflags	:= $(SnippetHelloWorld_checked_common_cflags)
SnippetHelloWorld_checked_cppflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetHelloWorld_checked_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetHelloWorld_checked_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetHelloWorld_checked_cppflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
SnippetHelloWorld_checked_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetHelloWorld_checked_cppflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetHelloWorld_checked_lflags    := $(SnippetHelloWorld_custom_lflags)
SnippetHelloWorld_checked_lflags    += $(addprefix -L, $(SnippetHelloWorld_checked_lpaths))
SnippetHelloWorld_checked_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetHelloWorld_checked_libraries)) -Wl,--end-group
SnippetHelloWorld_checked_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetHelloWorld_checked_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetHelloWorld_checked_objsdir  = $(OBJS_DIR)/SnippetHelloWorld_checked
SnippetHelloWorld_checked_cpp_o    = $(addprefix $(SnippetHelloWorld_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetHelloWorld_cppfiles)))))
SnippetHelloWorld_checked_c_o      = $(addprefix $(SnippetHelloWorld_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetHelloWorld_cfiles)))))
SnippetHelloWorld_checked_cc_o      = $(addprefix $(SnippetHelloWorld_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetHelloWorld_ccfiles)))))
SnippetHelloWorld_checked_obj      = $(SnippetHelloWorld_checked_cpp_o) $(SnippetHelloWorld_checked_cc_o) $(SnippetHelloWorld_checked_c_o)
SnippetHelloWorld_checked_bin      := ./../../../Bin/android9_neon/SnippetHelloWorldCHECKED

clean_SnippetHelloWorld_checked: 
	@$(ECHO) clean SnippetHelloWorld checked
	@$(RMDIR) $(SnippetHelloWorld_checked_objsdir)
	@$(RMDIR) $(SnippetHelloWorld_checked_bin)

build_SnippetHelloWorld_checked: postbuild_SnippetHelloWorld_checked
postbuild_SnippetHelloWorld_checked: mainbuild_SnippetHelloWorld_checked
mainbuild_SnippetHelloWorld_checked: prebuild_SnippetHelloWorld_checked $(SnippetHelloWorld_checked_bin)
prebuild_SnippetHelloWorld_checked:

$(SnippetHelloWorld_checked_bin): $(SnippetHelloWorld_checked_obj) 
	@mkdir -p `dirname ./../../../Bin/android9_neon/SnippetHelloWorldCHECKED`
	@$(CCLD) $(SnippetHelloWorld_checked_obj) $(SnippetHelloWorld_checked_lflags) -o $(SnippetHelloWorld_checked_bin) 
	@$(ECHO) building $@ complete!

SnippetHelloWorld_checked_DEPDIR = $(dir $(@))/$(*F)
$(SnippetHelloWorld_checked_cpp_o): $(SnippetHelloWorld_checked_objsdir)/%.o:
	@$(ECHO) SnippetHelloWorld: compiling checked $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetHelloWorld_checked_objsdir),, $@))), $(SnippetHelloWorld_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetHelloWorld_checked_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetHelloWorld_checked_objsdir),, $@))), $(SnippetHelloWorld_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetHelloWorld_checked_objsdir),, $@))), $(SnippetHelloWorld_cppfiles))))))
	@cp $(SnippetHelloWorld_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetHelloWorld_checked_objsdir),, $@))), $(SnippetHelloWorld_cppfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetHelloWorld_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetHelloWorld_checked_objsdir),, $@))), $(SnippetHelloWorld_cppfiles))))).checked.P; \
	  rm -f $(SnippetHelloWorld_checked_DEPDIR).d

$(SnippetHelloWorld_checked_c_o): $(SnippetHelloWorld_checked_objsdir)/%.o:
	@$(ECHO) SnippetHelloWorld: compiling checked $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetHelloWorld_checked_objsdir),, $@))), $(SnippetHelloWorld_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetHelloWorld_checked_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetHelloWorld_checked_objsdir),, $@))), $(SnippetHelloWorld_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetHelloWorld_checked_objsdir),, $@))), $(SnippetHelloWorld_cfiles))))))
	@cp $(SnippetHelloWorld_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetHelloWorld_checked_objsdir),, $@))), $(SnippetHelloWorld_cfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetHelloWorld_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetHelloWorld_checked_objsdir),, $@))), $(SnippetHelloWorld_cfiles))))).checked.P; \
	  rm -f $(SnippetHelloWorld_checked_DEPDIR).d

$(SnippetHelloWorld_checked_cc_o): $(SnippetHelloWorld_checked_objsdir)/%.o:
	@$(ECHO) SnippetHelloWorld: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetHelloWorld_checked_objsdir),, $@))), $(SnippetHelloWorld_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetHelloWorld_checked_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetHelloWorld_checked_objsdir),, $@))), $(SnippetHelloWorld_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetHelloWorld_checked_objsdir),, $@))), $(SnippetHelloWorld_ccfiles)))
	@cp $(SnippetHelloWorld_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetHelloWorld_checked_objsdir),, $@))), $(SnippetHelloWorld_ccfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetHelloWorld_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetHelloWorld_checked_objsdir),, $@))), $(SnippetHelloWorld_ccfiles))))).checked.P; \
	  rm -f $(SnippetHelloWorld_checked_DEPDIR).d

SnippetHelloWorld_profile_hpaths    := 
SnippetHelloWorld_profile_hpaths    += ./../../../Source/shared/general/shared
SnippetHelloWorld_profile_hpaths    += ./../../../Include
SnippetHelloWorld_profile_hpaths    += ./../../../Source/foundation/include
SnippetHelloWorld_profile_hpaths    += ./../../../Source/Common/src
SnippetHelloWorld_profile_hpaths    += ./../../../Source/GeomUtils/src
SnippetHelloWorld_profile_hpaths    += ./../../../Source/GeomUtils/headers
SnippetHelloWorld_profile_hpaths    += ./../../../Source/GeomUtils/include
SnippetHelloWorld_profile_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetHelloWorld_profile_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetHelloWorld_profile_lpaths    := 
SnippetHelloWorld_profile_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetHelloWorld_profile_lpaths    += ./../../../Lib/android9_neon
SnippetHelloWorld_profile_defines   := $(SnippetHelloWorld_custom_defines)
SnippetHelloWorld_profile_defines   += ANDROID
SnippetHelloWorld_profile_defines   += GLES2
SnippetHelloWorld_profile_defines   += __ARM_ARCH_5__
SnippetHelloWorld_profile_defines   += __ARM_ARCH_5T__
SnippetHelloWorld_profile_defines   += __ARM_ARCH_5E__
SnippetHelloWorld_profile_defines   += __ARM_ARCH_5TE__
SnippetHelloWorld_profile_defines   += NDEBUG
SnippetHelloWorld_profile_defines   += PX_PROFILE
SnippetHelloWorld_profile_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetHelloWorld_profile_defines   += PX_NVTX
SnippetHelloWorld_profile_defines   += PHYSX_PROFILE_SDK
SnippetHelloWorld_profile_libraries := 
SnippetHelloWorld_profile_libraries += log
SnippetHelloWorld_profile_libraries += gnustl_static
SnippetHelloWorld_profile_libraries += supc++
SnippetHelloWorld_profile_libraries += m
SnippetHelloWorld_profile_libraries += c
SnippetHelloWorld_profile_libraries += nvToolsExt
SnippetHelloWorld_profile_libraries += PhysX3CommonPROFILE
SnippetHelloWorld_profile_libraries += PvdRuntimePROFILE
SnippetHelloWorld_profile_libraries += SimulationControllerPROFILE
SnippetHelloWorld_profile_libraries += SceneQueryPROFILE
SnippetHelloWorld_profile_libraries += LowLevelPROFILE
SnippetHelloWorld_profile_libraries += LowLevelClothPROFILE
SnippetHelloWorld_profile_libraries += PhysX3PROFILE
SnippetHelloWorld_profile_libraries += PhysX3VehiclePROFILE
SnippetHelloWorld_profile_libraries += PhysX3CookingPROFILE
SnippetHelloWorld_profile_libraries += PhysX3ExtensionsPROFILE
SnippetHelloWorld_profile_libraries += PhysX3CharacterKinematicPROFILE
SnippetHelloWorld_profile_libraries += PhysXProfileSDKPROFILE
SnippetHelloWorld_profile_libraries += PxTaskPROFILE
SnippetHelloWorld_profile_libraries += PhysXVisualDebuggerSDKPROFILE
SnippetHelloWorld_profile_common_cflags	:= $(SnippetHelloWorld_custom_cflags)
SnippetHelloWorld_profile_common_cflags    += -MMD
SnippetHelloWorld_profile_common_cflags    += $(addprefix -D, $(SnippetHelloWorld_profile_defines))
SnippetHelloWorld_profile_common_cflags    += $(addprefix -I, $(SnippetHelloWorld_profile_hpaths))
SnippetHelloWorld_profile_cflags	:= $(SnippetHelloWorld_profile_common_cflags)
SnippetHelloWorld_profile_cflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetHelloWorld_profile_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetHelloWorld_profile_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetHelloWorld_profile_cflags  += -O3 -fno-strict-aliasing
SnippetHelloWorld_profile_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetHelloWorld_profile_cflags  += -fno-omit-frame-pointer -marm -funswitch-loops -finline-limit=300
SnippetHelloWorld_profile_cppflags	:= $(SnippetHelloWorld_profile_common_cflags)
SnippetHelloWorld_profile_cppflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetHelloWorld_profile_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetHelloWorld_profile_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetHelloWorld_profile_cppflags  += -O3 -fno-strict-aliasing
SnippetHelloWorld_profile_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetHelloWorld_profile_cppflags  += -fno-omit-frame-pointer -marm -funswitch-loops -finline-limit=300
SnippetHelloWorld_profile_lflags    := $(SnippetHelloWorld_custom_lflags)
SnippetHelloWorld_profile_lflags    += $(addprefix -L, $(SnippetHelloWorld_profile_lpaths))
SnippetHelloWorld_profile_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetHelloWorld_profile_libraries)) -Wl,--end-group
SnippetHelloWorld_profile_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetHelloWorld_profile_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetHelloWorld_profile_objsdir  = $(OBJS_DIR)/SnippetHelloWorld_profile
SnippetHelloWorld_profile_cpp_o    = $(addprefix $(SnippetHelloWorld_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetHelloWorld_cppfiles)))))
SnippetHelloWorld_profile_c_o      = $(addprefix $(SnippetHelloWorld_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetHelloWorld_cfiles)))))
SnippetHelloWorld_profile_cc_o      = $(addprefix $(SnippetHelloWorld_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetHelloWorld_ccfiles)))))
SnippetHelloWorld_profile_obj      = $(SnippetHelloWorld_profile_cpp_o) $(SnippetHelloWorld_profile_cc_o) $(SnippetHelloWorld_profile_c_o)
SnippetHelloWorld_profile_bin      := ./../../../Bin/android9_neon/SnippetHelloWorldPROFILE

clean_SnippetHelloWorld_profile: 
	@$(ECHO) clean SnippetHelloWorld profile
	@$(RMDIR) $(SnippetHelloWorld_profile_objsdir)
	@$(RMDIR) $(SnippetHelloWorld_profile_bin)

build_SnippetHelloWorld_profile: postbuild_SnippetHelloWorld_profile
postbuild_SnippetHelloWorld_profile: mainbuild_SnippetHelloWorld_profile
mainbuild_SnippetHelloWorld_profile: prebuild_SnippetHelloWorld_profile $(SnippetHelloWorld_profile_bin)
prebuild_SnippetHelloWorld_profile:

$(SnippetHelloWorld_profile_bin): $(SnippetHelloWorld_profile_obj) 
	@mkdir -p `dirname ./../../../Bin/android9_neon/SnippetHelloWorldPROFILE`
	@$(CCLD) $(SnippetHelloWorld_profile_obj) $(SnippetHelloWorld_profile_lflags) -o $(SnippetHelloWorld_profile_bin) 
	@$(ECHO) building $@ complete!

SnippetHelloWorld_profile_DEPDIR = $(dir $(@))/$(*F)
$(SnippetHelloWorld_profile_cpp_o): $(SnippetHelloWorld_profile_objsdir)/%.o:
	@$(ECHO) SnippetHelloWorld: compiling profile $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetHelloWorld_profile_objsdir),, $@))), $(SnippetHelloWorld_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetHelloWorld_profile_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetHelloWorld_profile_objsdir),, $@))), $(SnippetHelloWorld_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetHelloWorld_profile_objsdir),, $@))), $(SnippetHelloWorld_cppfiles))))))
	@cp $(SnippetHelloWorld_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetHelloWorld_profile_objsdir),, $@))), $(SnippetHelloWorld_cppfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetHelloWorld_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetHelloWorld_profile_objsdir),, $@))), $(SnippetHelloWorld_cppfiles))))).profile.P; \
	  rm -f $(SnippetHelloWorld_profile_DEPDIR).d

$(SnippetHelloWorld_profile_c_o): $(SnippetHelloWorld_profile_objsdir)/%.o:
	@$(ECHO) SnippetHelloWorld: compiling profile $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetHelloWorld_profile_objsdir),, $@))), $(SnippetHelloWorld_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetHelloWorld_profile_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetHelloWorld_profile_objsdir),, $@))), $(SnippetHelloWorld_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetHelloWorld_profile_objsdir),, $@))), $(SnippetHelloWorld_cfiles))))))
	@cp $(SnippetHelloWorld_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetHelloWorld_profile_objsdir),, $@))), $(SnippetHelloWorld_cfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetHelloWorld_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetHelloWorld_profile_objsdir),, $@))), $(SnippetHelloWorld_cfiles))))).profile.P; \
	  rm -f $(SnippetHelloWorld_profile_DEPDIR).d

$(SnippetHelloWorld_profile_cc_o): $(SnippetHelloWorld_profile_objsdir)/%.o:
	@$(ECHO) SnippetHelloWorld: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetHelloWorld_profile_objsdir),, $@))), $(SnippetHelloWorld_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetHelloWorld_profile_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetHelloWorld_profile_objsdir),, $@))), $(SnippetHelloWorld_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetHelloWorld_profile_objsdir),, $@))), $(SnippetHelloWorld_ccfiles)))
	@cp $(SnippetHelloWorld_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetHelloWorld_profile_objsdir),, $@))), $(SnippetHelloWorld_ccfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetHelloWorld_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetHelloWorld_profile_objsdir),, $@))), $(SnippetHelloWorld_ccfiles))))).profile.P; \
	  rm -f $(SnippetHelloWorld_profile_DEPDIR).d

SnippetHelloWorld_release_hpaths    := 
SnippetHelloWorld_release_hpaths    += ./../../../Source/shared/general/shared
SnippetHelloWorld_release_hpaths    += ./../../../Include
SnippetHelloWorld_release_hpaths    += ./../../../Source/foundation/include
SnippetHelloWorld_release_hpaths    += ./../../../Source/Common/src
SnippetHelloWorld_release_hpaths    += ./../../../Source/GeomUtils/src
SnippetHelloWorld_release_hpaths    += ./../../../Source/GeomUtils/headers
SnippetHelloWorld_release_hpaths    += ./../../../Source/GeomUtils/include
SnippetHelloWorld_release_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetHelloWorld_release_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetHelloWorld_release_lpaths    := 
SnippetHelloWorld_release_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetHelloWorld_release_lpaths    += ./../../../Lib/android9_neon
SnippetHelloWorld_release_defines   := $(SnippetHelloWorld_custom_defines)
SnippetHelloWorld_release_defines   += ANDROID
SnippetHelloWorld_release_defines   += GLES2
SnippetHelloWorld_release_defines   += __ARM_ARCH_5__
SnippetHelloWorld_release_defines   += __ARM_ARCH_5T__
SnippetHelloWorld_release_defines   += __ARM_ARCH_5E__
SnippetHelloWorld_release_defines   += __ARM_ARCH_5TE__
SnippetHelloWorld_release_defines   += NDEBUG
SnippetHelloWorld_release_defines   += PHYSX_PROFILE_SDK
SnippetHelloWorld_release_libraries := 
SnippetHelloWorld_release_libraries += log
SnippetHelloWorld_release_libraries += gnustl_static
SnippetHelloWorld_release_libraries += supc++
SnippetHelloWorld_release_libraries += m
SnippetHelloWorld_release_libraries += c
SnippetHelloWorld_release_libraries += nvToolsExt
SnippetHelloWorld_release_libraries += PhysX3Common
SnippetHelloWorld_release_libraries += PvdRuntime
SnippetHelloWorld_release_libraries += SimulationController
SnippetHelloWorld_release_libraries += SceneQuery
SnippetHelloWorld_release_libraries += LowLevel
SnippetHelloWorld_release_libraries += LowLevelCloth
SnippetHelloWorld_release_libraries += PhysX3
SnippetHelloWorld_release_libraries += PhysX3Vehicle
SnippetHelloWorld_release_libraries += PhysX3Cooking
SnippetHelloWorld_release_libraries += PhysX3Extensions
SnippetHelloWorld_release_libraries += PhysX3CharacterKinematic
SnippetHelloWorld_release_libraries += PhysXProfileSDK
SnippetHelloWorld_release_libraries += PxTask
SnippetHelloWorld_release_libraries += PhysXVisualDebuggerSDK
SnippetHelloWorld_release_common_cflags	:= $(SnippetHelloWorld_custom_cflags)
SnippetHelloWorld_release_common_cflags    += -MMD
SnippetHelloWorld_release_common_cflags    += $(addprefix -D, $(SnippetHelloWorld_release_defines))
SnippetHelloWorld_release_common_cflags    += $(addprefix -I, $(SnippetHelloWorld_release_hpaths))
SnippetHelloWorld_release_cflags	:= $(SnippetHelloWorld_release_common_cflags)
SnippetHelloWorld_release_cflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetHelloWorld_release_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetHelloWorld_release_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetHelloWorld_release_cflags  += -O3 -fno-strict-aliasing
SnippetHelloWorld_release_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetHelloWorld_release_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetHelloWorld_release_cppflags	:= $(SnippetHelloWorld_release_common_cflags)
SnippetHelloWorld_release_cppflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetHelloWorld_release_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetHelloWorld_release_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetHelloWorld_release_cppflags  += -O3 -fno-strict-aliasing
SnippetHelloWorld_release_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetHelloWorld_release_cppflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetHelloWorld_release_lflags    := $(SnippetHelloWorld_custom_lflags)
SnippetHelloWorld_release_lflags    += $(addprefix -L, $(SnippetHelloWorld_release_lpaths))
SnippetHelloWorld_release_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetHelloWorld_release_libraries)) -Wl,--end-group
SnippetHelloWorld_release_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetHelloWorld_release_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetHelloWorld_release_objsdir  = $(OBJS_DIR)/SnippetHelloWorld_release
SnippetHelloWorld_release_cpp_o    = $(addprefix $(SnippetHelloWorld_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetHelloWorld_cppfiles)))))
SnippetHelloWorld_release_c_o      = $(addprefix $(SnippetHelloWorld_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetHelloWorld_cfiles)))))
SnippetHelloWorld_release_cc_o      = $(addprefix $(SnippetHelloWorld_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetHelloWorld_ccfiles)))))
SnippetHelloWorld_release_obj      = $(SnippetHelloWorld_release_cpp_o) $(SnippetHelloWorld_release_cc_o) $(SnippetHelloWorld_release_c_o)
SnippetHelloWorld_release_bin      := ./../../../Bin/android9_neon/SnippetHelloWorld

clean_SnippetHelloWorld_release: 
	@$(ECHO) clean SnippetHelloWorld release
	@$(RMDIR) $(SnippetHelloWorld_release_objsdir)
	@$(RMDIR) $(SnippetHelloWorld_release_bin)

build_SnippetHelloWorld_release: postbuild_SnippetHelloWorld_release
postbuild_SnippetHelloWorld_release: mainbuild_SnippetHelloWorld_release
mainbuild_SnippetHelloWorld_release: prebuild_SnippetHelloWorld_release $(SnippetHelloWorld_release_bin)
prebuild_SnippetHelloWorld_release:

$(SnippetHelloWorld_release_bin): $(SnippetHelloWorld_release_obj) 
	@mkdir -p `dirname ./../../../Bin/android9_neon/SnippetHelloWorld`
	@$(CCLD) $(SnippetHelloWorld_release_obj) $(SnippetHelloWorld_release_lflags) -o $(SnippetHelloWorld_release_bin) 
	@$(ECHO) building $@ complete!

SnippetHelloWorld_release_DEPDIR = $(dir $(@))/$(*F)
$(SnippetHelloWorld_release_cpp_o): $(SnippetHelloWorld_release_objsdir)/%.o:
	@$(ECHO) SnippetHelloWorld: compiling release $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetHelloWorld_release_objsdir),, $@))), $(SnippetHelloWorld_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetHelloWorld_release_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetHelloWorld_release_objsdir),, $@))), $(SnippetHelloWorld_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetHelloWorld_release_objsdir),, $@))), $(SnippetHelloWorld_cppfiles))))))
	@cp $(SnippetHelloWorld_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetHelloWorld_release_objsdir),, $@))), $(SnippetHelloWorld_cppfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetHelloWorld_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetHelloWorld_release_objsdir),, $@))), $(SnippetHelloWorld_cppfiles))))).release.P; \
	  rm -f $(SnippetHelloWorld_release_DEPDIR).d

$(SnippetHelloWorld_release_c_o): $(SnippetHelloWorld_release_objsdir)/%.o:
	@$(ECHO) SnippetHelloWorld: compiling release $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetHelloWorld_release_objsdir),, $@))), $(SnippetHelloWorld_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetHelloWorld_release_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetHelloWorld_release_objsdir),, $@))), $(SnippetHelloWorld_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetHelloWorld_release_objsdir),, $@))), $(SnippetHelloWorld_cfiles))))))
	@cp $(SnippetHelloWorld_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetHelloWorld_release_objsdir),, $@))), $(SnippetHelloWorld_cfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetHelloWorld_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetHelloWorld_release_objsdir),, $@))), $(SnippetHelloWorld_cfiles))))).release.P; \
	  rm -f $(SnippetHelloWorld_release_DEPDIR).d

$(SnippetHelloWorld_release_cc_o): $(SnippetHelloWorld_release_objsdir)/%.o:
	@$(ECHO) SnippetHelloWorld: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetHelloWorld_release_objsdir),, $@))), $(SnippetHelloWorld_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetHelloWorld_release_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetHelloWorld_release_objsdir),, $@))), $(SnippetHelloWorld_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetHelloWorld_release_objsdir),, $@))), $(SnippetHelloWorld_ccfiles)))
	@cp $(SnippetHelloWorld_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetHelloWorld_release_objsdir),, $@))), $(SnippetHelloWorld_ccfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetHelloWorld_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetHelloWorld_release_objsdir),, $@))), $(SnippetHelloWorld_ccfiles))))).release.P; \
	  rm -f $(SnippetHelloWorld_release_DEPDIR).d

clean_SnippetHelloWorld:  clean_SnippetHelloWorld_debug clean_SnippetHelloWorld_checked clean_SnippetHelloWorld_profile clean_SnippetHelloWorld_release
	@rm -rf $(DEPSDIR)
