# Makefile generated by XPJ for ANDROID
-include Makefile.custom
ProjectName = SnippetSerialization
SnippetSerialization_cppfiles   += ./../../SnippetSerialization/SnippetSerialization.cpp
SnippetSerialization_cppfiles   += ./../../SnippetSerialization/SnippetSerializationRender.cpp

SnippetSerialization_cpp_debug_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.debug.P, $(SnippetSerialization_cppfiles)))))
SnippetSerialization_c_debug_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.debug.P, $(SnippetSerialization_cfiles)))))
SnippetSerialization_cc_debug_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.debug.P, $(SnippetSerialization_ccfiles)))))
SnippetSerialization_debug_dep      = $(SnippetSerialization_cpp_debug_dep) $(SnippetSerialization_cc_debug_dep) $(SnippetSerialization_c_debug_dep)
-include $(SnippetSerialization_debug_dep)
SnippetSerialization_cpp_checked_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.checked.P, $(SnippetSerialization_cppfiles)))))
SnippetSerialization_c_checked_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.checked.P, $(SnippetSerialization_cfiles)))))
SnippetSerialization_cc_checked_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.checked.P, $(SnippetSerialization_ccfiles)))))
SnippetSerialization_checked_dep      = $(SnippetSerialization_cpp_checked_dep) $(SnippetSerialization_cc_checked_dep) $(SnippetSerialization_c_checked_dep)
-include $(SnippetSerialization_checked_dep)
SnippetSerialization_cpp_profile_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.profile.P, $(SnippetSerialization_cppfiles)))))
SnippetSerialization_c_profile_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.profile.P, $(SnippetSerialization_cfiles)))))
SnippetSerialization_cc_profile_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.profile.P, $(SnippetSerialization_ccfiles)))))
SnippetSerialization_profile_dep      = $(SnippetSerialization_cpp_profile_dep) $(SnippetSerialization_cc_profile_dep) $(SnippetSerialization_c_profile_dep)
-include $(SnippetSerialization_profile_dep)
SnippetSerialization_cpp_release_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.release.P, $(SnippetSerialization_cppfiles)))))
SnippetSerialization_c_release_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.release.P, $(SnippetSerialization_cfiles)))))
SnippetSerialization_cc_release_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.release.P, $(SnippetSerialization_ccfiles)))))
SnippetSerialization_release_dep      = $(SnippetSerialization_cpp_release_dep) $(SnippetSerialization_cc_release_dep) $(SnippetSerialization_c_release_dep)
-include $(SnippetSerialization_release_dep)
SnippetSerialization_debug_hpaths    := 
SnippetSerialization_debug_hpaths    += ./../../../Source/shared/general/shared
SnippetSerialization_debug_hpaths    += ./../../../Include
SnippetSerialization_debug_hpaths    += ./../../../Source/foundation/include
SnippetSerialization_debug_hpaths    += ./../../../Source/Common/src
SnippetSerialization_debug_hpaths    += ./../../../Source/GeomUtils/src
SnippetSerialization_debug_hpaths    += ./../../../Source/GeomUtils/headers
SnippetSerialization_debug_hpaths    += ./../../../Source/GeomUtils/include
SnippetSerialization_debug_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetSerialization_debug_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetSerialization_debug_lpaths    := 
SnippetSerialization_debug_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetSerialization_debug_lpaths    += ./../../../Lib/android9_neon
SnippetSerialization_debug_defines   := $(SnippetSerialization_custom_defines)
SnippetSerialization_debug_defines   += ANDROID
SnippetSerialization_debug_defines   += GLES2
SnippetSerialization_debug_defines   += __ARM_ARCH_5__
SnippetSerialization_debug_defines   += __ARM_ARCH_5T__
SnippetSerialization_debug_defines   += __ARM_ARCH_5E__
SnippetSerialization_debug_defines   += __ARM_ARCH_5TE__
SnippetSerialization_debug_defines   += _DEBUG
SnippetSerialization_debug_defines   += PX_DEBUG
SnippetSerialization_debug_defines   += PX_CHECKED
SnippetSerialization_debug_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetSerialization_debug_defines   += PX_NVTX
SnippetSerialization_debug_defines   += PHYSX_PROFILE_SDK
SnippetSerialization_debug_libraries := 
SnippetSerialization_debug_libraries += log
SnippetSerialization_debug_libraries += gnustl_static
SnippetSerialization_debug_libraries += supc++
SnippetSerialization_debug_libraries += m
SnippetSerialization_debug_libraries += c
SnippetSerialization_debug_libraries += nvToolsExt
SnippetSerialization_debug_libraries += PhysX3CommonCHECKED
SnippetSerialization_debug_libraries += PvdRuntimeCHECKED
SnippetSerialization_debug_libraries += SimulationControllerCHECKED
SnippetSerialization_debug_libraries += SceneQueryCHECKED
SnippetSerialization_debug_libraries += LowLevelCHECKED
SnippetSerialization_debug_libraries += LowLevelClothCHECKED
SnippetSerialization_debug_libraries += PhysX3CHECKED
SnippetSerialization_debug_libraries += PhysX3VehicleCHECKED
SnippetSerialization_debug_libraries += PhysX3CookingCHECKED
SnippetSerialization_debug_libraries += PhysX3ExtensionsCHECKED
SnippetSerialization_debug_libraries += PhysX3CharacterKinematicCHECKED
SnippetSerialization_debug_libraries += PhysXProfileSDKCHECKED
SnippetSerialization_debug_libraries += PxTaskCHECKED
SnippetSerialization_debug_libraries += PhysXVisualDebuggerSDKCHECKED
SnippetSerialization_debug_common_cflags	:= $(SnippetSerialization_custom_cflags)
SnippetSerialization_debug_common_cflags    += -MMD
SnippetSerialization_debug_common_cflags    += $(addprefix -D, $(SnippetSerialization_debug_defines))
SnippetSerialization_debug_common_cflags    += $(addprefix -I, $(SnippetSerialization_debug_hpaths))
SnippetSerialization_debug_cflags	:= $(SnippetSerialization_debug_common_cflags)
SnippetSerialization_debug_cflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetSerialization_debug_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetSerialization_debug_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetSerialization_debug_cflags  += -g3 -gdwarf-2
SnippetSerialization_debug_cppflags	:= $(SnippetSerialization_debug_common_cflags)
SnippetSerialization_debug_cppflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetSerialization_debug_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetSerialization_debug_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetSerialization_debug_cppflags  += -g3 -gdwarf-2
SnippetSerialization_debug_lflags    := $(SnippetSerialization_custom_lflags)
SnippetSerialization_debug_lflags    += $(addprefix -L, $(SnippetSerialization_debug_lpaths))
SnippetSerialization_debug_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetSerialization_debug_libraries)) -Wl,--end-group
SnippetSerialization_debug_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetSerialization_debug_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetSerialization_debug_objsdir  = $(OBJS_DIR)/SnippetSerialization_debug
SnippetSerialization_debug_cpp_o    = $(addprefix $(SnippetSerialization_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetSerialization_cppfiles)))))
SnippetSerialization_debug_c_o      = $(addprefix $(SnippetSerialization_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetSerialization_cfiles)))))
SnippetSerialization_debug_cc_o      = $(addprefix $(SnippetSerialization_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetSerialization_ccfiles)))))
SnippetSerialization_debug_obj      = $(SnippetSerialization_debug_cpp_o) $(SnippetSerialization_debug_cc_o) $(SnippetSerialization_debug_c_o)
SnippetSerialization_debug_bin      := ./../../../Bin/android9_neon/SnippetSerializationDEBUG

clean_SnippetSerialization_debug: 
	@$(ECHO) clean SnippetSerialization debug
	@$(RMDIR) $(SnippetSerialization_debug_objsdir)
	@$(RMDIR) $(SnippetSerialization_debug_bin)

build_SnippetSerialization_debug: postbuild_SnippetSerialization_debug
postbuild_SnippetSerialization_debug: mainbuild_SnippetSerialization_debug
mainbuild_SnippetSerialization_debug: prebuild_SnippetSerialization_debug $(SnippetSerialization_debug_bin)
prebuild_SnippetSerialization_debug:

$(SnippetSerialization_debug_bin): $(SnippetSerialization_debug_obj) 
	@mkdir -p `dirname ./../../../Bin/android9_neon/SnippetSerializationDEBUG`
	@$(CCLD) $(SnippetSerialization_debug_obj) $(SnippetSerialization_debug_lflags) -o $(SnippetSerialization_debug_bin) 
	@$(ECHO) building $@ complete!

SnippetSerialization_debug_DEPDIR = $(dir $(@))/$(*F)
$(SnippetSerialization_debug_cpp_o): $(SnippetSerialization_debug_objsdir)/%.o:
	@$(ECHO) SnippetSerialization: compiling debug $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetSerialization_debug_objsdir),, $@))), $(SnippetSerialization_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetSerialization_debug_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetSerialization_debug_objsdir),, $@))), $(SnippetSerialization_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetSerialization_debug_objsdir),, $@))), $(SnippetSerialization_cppfiles))))))
	@cp $(SnippetSerialization_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetSerialization_debug_objsdir),, $@))), $(SnippetSerialization_cppfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetSerialization_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetSerialization_debug_objsdir),, $@))), $(SnippetSerialization_cppfiles))))).debug.P; \
	  rm -f $(SnippetSerialization_debug_DEPDIR).d

$(SnippetSerialization_debug_c_o): $(SnippetSerialization_debug_objsdir)/%.o:
	@$(ECHO) SnippetSerialization: compiling debug $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetSerialization_debug_objsdir),, $@))), $(SnippetSerialization_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetSerialization_debug_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetSerialization_debug_objsdir),, $@))), $(SnippetSerialization_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetSerialization_debug_objsdir),, $@))), $(SnippetSerialization_cfiles))))))
	@cp $(SnippetSerialization_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetSerialization_debug_objsdir),, $@))), $(SnippetSerialization_cfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetSerialization_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetSerialization_debug_objsdir),, $@))), $(SnippetSerialization_cfiles))))).debug.P; \
	  rm -f $(SnippetSerialization_debug_DEPDIR).d

$(SnippetSerialization_debug_cc_o): $(SnippetSerialization_debug_objsdir)/%.o:
	@$(ECHO) SnippetSerialization: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetSerialization_debug_objsdir),, $@))), $(SnippetSerialization_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetSerialization_debug_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetSerialization_debug_objsdir),, $@))), $(SnippetSerialization_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetSerialization_debug_objsdir),, $@))), $(SnippetSerialization_ccfiles)))
	@cp $(SnippetSerialization_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetSerialization_debug_objsdir),, $@))), $(SnippetSerialization_ccfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetSerialization_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetSerialization_debug_objsdir),, $@))), $(SnippetSerialization_ccfiles))))).debug.P; \
	  rm -f $(SnippetSerialization_debug_DEPDIR).d

SnippetSerialization_checked_hpaths    := 
SnippetSerialization_checked_hpaths    += ./../../../Source/shared/general/shared
SnippetSerialization_checked_hpaths    += ./../../../Include
SnippetSerialization_checked_hpaths    += ./../../../Source/foundation/include
SnippetSerialization_checked_hpaths    += ./../../../Source/Common/src
SnippetSerialization_checked_hpaths    += ./../../../Source/GeomUtils/src
SnippetSerialization_checked_hpaths    += ./../../../Source/GeomUtils/headers
SnippetSerialization_checked_hpaths    += ./../../../Source/GeomUtils/include
SnippetSerialization_checked_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetSerialization_checked_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetSerialization_checked_lpaths    := 
SnippetSerialization_checked_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetSerialization_checked_lpaths    += ./../../../Lib/android9_neon
SnippetSerialization_checked_defines   := $(SnippetSerialization_custom_defines)
SnippetSerialization_checked_defines   += ANDROID
SnippetSerialization_checked_defines   += GLES2
SnippetSerialization_checked_defines   += __ARM_ARCH_5__
SnippetSerialization_checked_defines   += __ARM_ARCH_5T__
SnippetSerialization_checked_defines   += __ARM_ARCH_5E__
SnippetSerialization_checked_defines   += __ARM_ARCH_5TE__
SnippetSerialization_checked_defines   += NDEBUG
SnippetSerialization_checked_defines   += PX_CHECKED
SnippetSerialization_checked_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetSerialization_checked_defines   += PX_NVTX
SnippetSerialization_checked_defines   += PHYSX_PROFILE_SDK
SnippetSerialization_checked_libraries := 
SnippetSerialization_checked_libraries += log
SnippetSerialization_checked_libraries += gnustl_static
SnippetSerialization_checked_libraries += supc++
SnippetSerialization_checked_libraries += m
SnippetSerialization_checked_libraries += c
SnippetSerialization_checked_libraries += nvToolsExt
SnippetSerialization_checked_libraries += PhysX3CommonCHECKED
SnippetSerialization_checked_libraries += PvdRuntimeCHECKED
SnippetSerialization_checked_libraries += SimulationControllerCHECKED
SnippetSerialization_checked_libraries += SceneQueryCHECKED
SnippetSerialization_checked_libraries += LowLevelCHECKED
SnippetSerialization_checked_libraries += LowLevelClothCHECKED
SnippetSerialization_checked_libraries += PhysX3CHECKED
SnippetSerialization_checked_libraries += PhysX3VehicleCHECKED
SnippetSerialization_checked_libraries += PhysX3CookingCHECKED
SnippetSerialization_checked_libraries += PhysX3ExtensionsCHECKED
SnippetSerialization_checked_libraries += PhysX3CharacterKinematicCHECKED
SnippetSerialization_checked_libraries += PhysXProfileSDKCHECKED
SnippetSerialization_checked_libraries += PxTaskCHECKED
SnippetSerialization_checked_libraries += PhysXVisualDebuggerSDKCHECKED
SnippetSerialization_checked_common_cflags	:= $(SnippetSerialization_custom_cflags)
SnippetSerialization_checked_common_cflags    += -MMD
SnippetSerialization_checked_common_cflags    += $(addprefix -D, $(SnippetSerialization_checked_defines))
SnippetSerialization_checked_common_cflags    += $(addprefix -I, $(SnippetSerialization_checked_hpaths))
SnippetSerialization_checked_cflags	:= $(SnippetSerialization_checked_common_cflags)
SnippetSerialization_checked_cflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetSerialization_checked_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetSerialization_checked_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetSerialization_checked_cflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
SnippetSerialization_checked_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetSerialization_checked_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetSerialization_checked_cppflags	:= $(SnippetSerialization_checked_common_cflags)
SnippetSerialization_checked_cppflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetSerialization_checked_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetSerialization_checked_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetSerialization_checked_cppflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
SnippetSerialization_checked_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetSerialization_checked_cppflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetSerialization_checked_lflags    := $(SnippetSerialization_custom_lflags)
SnippetSerialization_checked_lflags    += $(addprefix -L, $(SnippetSerialization_checked_lpaths))
SnippetSerialization_checked_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetSerialization_checked_libraries)) -Wl,--end-group
SnippetSerialization_checked_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetSerialization_checked_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetSerialization_checked_objsdir  = $(OBJS_DIR)/SnippetSerialization_checked
SnippetSerialization_checked_cpp_o    = $(addprefix $(SnippetSerialization_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetSerialization_cppfiles)))))
SnippetSerialization_checked_c_o      = $(addprefix $(SnippetSerialization_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetSerialization_cfiles)))))
SnippetSerialization_checked_cc_o      = $(addprefix $(SnippetSerialization_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetSerialization_ccfiles)))))
SnippetSerialization_checked_obj      = $(SnippetSerialization_checked_cpp_o) $(SnippetSerialization_checked_cc_o) $(SnippetSerialization_checked_c_o)
SnippetSerialization_checked_bin      := ./../../../Bin/android9_neon/SnippetSerializationCHECKED

clean_SnippetSerialization_checked: 
	@$(ECHO) clean SnippetSerialization checked
	@$(RMDIR) $(SnippetSerialization_checked_objsdir)
	@$(RMDIR) $(SnippetSerialization_checked_bin)

build_SnippetSerialization_checked: postbuild_SnippetSerialization_checked
postbuild_SnippetSerialization_checked: mainbuild_SnippetSerialization_checked
mainbuild_SnippetSerialization_checked: prebuild_SnippetSerialization_checked $(SnippetSerialization_checked_bin)
prebuild_SnippetSerialization_checked:

$(SnippetSerialization_checked_bin): $(SnippetSerialization_checked_obj) 
	@mkdir -p `dirname ./../../../Bin/android9_neon/SnippetSerializationCHECKED`
	@$(CCLD) $(SnippetSerialization_checked_obj) $(SnippetSerialization_checked_lflags) -o $(SnippetSerialization_checked_bin) 
	@$(ECHO) building $@ complete!

SnippetSerialization_checked_DEPDIR = $(dir $(@))/$(*F)
$(SnippetSerialization_checked_cpp_o): $(SnippetSerialization_checked_objsdir)/%.o:
	@$(ECHO) SnippetSerialization: compiling checked $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetSerialization_checked_objsdir),, $@))), $(SnippetSerialization_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetSerialization_checked_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetSerialization_checked_objsdir),, $@))), $(SnippetSerialization_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetSerialization_checked_objsdir),, $@))), $(SnippetSerialization_cppfiles))))))
	@cp $(SnippetSerialization_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetSerialization_checked_objsdir),, $@))), $(SnippetSerialization_cppfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetSerialization_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetSerialization_checked_objsdir),, $@))), $(SnippetSerialization_cppfiles))))).checked.P; \
	  rm -f $(SnippetSerialization_checked_DEPDIR).d

$(SnippetSerialization_checked_c_o): $(SnippetSerialization_checked_objsdir)/%.o:
	@$(ECHO) SnippetSerialization: compiling checked $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetSerialization_checked_objsdir),, $@))), $(SnippetSerialization_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetSerialization_checked_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetSerialization_checked_objsdir),, $@))), $(SnippetSerialization_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetSerialization_checked_objsdir),, $@))), $(SnippetSerialization_cfiles))))))
	@cp $(SnippetSerialization_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetSerialization_checked_objsdir),, $@))), $(SnippetSerialization_cfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetSerialization_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetSerialization_checked_objsdir),, $@))), $(SnippetSerialization_cfiles))))).checked.P; \
	  rm -f $(SnippetSerialization_checked_DEPDIR).d

$(SnippetSerialization_checked_cc_o): $(SnippetSerialization_checked_objsdir)/%.o:
	@$(ECHO) SnippetSerialization: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetSerialization_checked_objsdir),, $@))), $(SnippetSerialization_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetSerialization_checked_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetSerialization_checked_objsdir),, $@))), $(SnippetSerialization_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetSerialization_checked_objsdir),, $@))), $(SnippetSerialization_ccfiles)))
	@cp $(SnippetSerialization_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetSerialization_checked_objsdir),, $@))), $(SnippetSerialization_ccfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetSerialization_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetSerialization_checked_objsdir),, $@))), $(SnippetSerialization_ccfiles))))).checked.P; \
	  rm -f $(SnippetSerialization_checked_DEPDIR).d

SnippetSerialization_profile_hpaths    := 
SnippetSerialization_profile_hpaths    += ./../../../Source/shared/general/shared
SnippetSerialization_profile_hpaths    += ./../../../Include
SnippetSerialization_profile_hpaths    += ./../../../Source/foundation/include
SnippetSerialization_profile_hpaths    += ./../../../Source/Common/src
SnippetSerialization_profile_hpaths    += ./../../../Source/GeomUtils/src
SnippetSerialization_profile_hpaths    += ./../../../Source/GeomUtils/headers
SnippetSerialization_profile_hpaths    += ./../../../Source/GeomUtils/include
SnippetSerialization_profile_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetSerialization_profile_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetSerialization_profile_lpaths    := 
SnippetSerialization_profile_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetSerialization_profile_lpaths    += ./../../../Lib/android9_neon
SnippetSerialization_profile_defines   := $(SnippetSerialization_custom_defines)
SnippetSerialization_profile_defines   += ANDROID
SnippetSerialization_profile_defines   += GLES2
SnippetSerialization_profile_defines   += __ARM_ARCH_5__
SnippetSerialization_profile_defines   += __ARM_ARCH_5T__
SnippetSerialization_profile_defines   += __ARM_ARCH_5E__
SnippetSerialization_profile_defines   += __ARM_ARCH_5TE__
SnippetSerialization_profile_defines   += NDEBUG
SnippetSerialization_profile_defines   += PX_PROFILE
SnippetSerialization_profile_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetSerialization_profile_defines   += PX_NVTX
SnippetSerialization_profile_defines   += PHYSX_PROFILE_SDK
SnippetSerialization_profile_libraries := 
SnippetSerialization_profile_libraries += log
SnippetSerialization_profile_libraries += gnustl_static
SnippetSerialization_profile_libraries += supc++
SnippetSerialization_profile_libraries += m
SnippetSerialization_profile_libraries += c
SnippetSerialization_profile_libraries += nvToolsExt
SnippetSerialization_profile_libraries += PhysX3CommonPROFILE
SnippetSerialization_profile_libraries += PvdRuntimePROFILE
SnippetSerialization_profile_libraries += SimulationControllerPROFILE
SnippetSerialization_profile_libraries += SceneQueryPROFILE
SnippetSerialization_profile_libraries += LowLevelPROFILE
SnippetSerialization_profile_libraries += LowLevelClothPROFILE
SnippetSerialization_profile_libraries += PhysX3PROFILE
SnippetSerialization_profile_libraries += PhysX3VehiclePROFILE
SnippetSerialization_profile_libraries += PhysX3CookingPROFILE
SnippetSerialization_profile_libraries += PhysX3ExtensionsPROFILE
SnippetSerialization_profile_libraries += PhysX3CharacterKinematicPROFILE
SnippetSerialization_profile_libraries += PhysXProfileSDKPROFILE
SnippetSerialization_profile_libraries += PxTaskPROFILE
SnippetSerialization_profile_libraries += PhysXVisualDebuggerSDKPROFILE
SnippetSerialization_profile_common_cflags	:= $(SnippetSerialization_custom_cflags)
SnippetSerialization_profile_common_cflags    += -MMD
SnippetSerialization_profile_common_cflags    += $(addprefix -D, $(SnippetSerialization_profile_defines))
SnippetSerialization_profile_common_cflags    += $(addprefix -I, $(SnippetSerialization_profile_hpaths))
SnippetSerialization_profile_cflags	:= $(SnippetSerialization_profile_common_cflags)
SnippetSerialization_profile_cflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetSerialization_profile_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetSerialization_profile_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetSerialization_profile_cflags  += -O3 -fno-strict-aliasing
SnippetSerialization_profile_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetSerialization_profile_cflags  += -fno-omit-frame-pointer -marm -funswitch-loops -finline-limit=300
SnippetSerialization_profile_cppflags	:= $(SnippetSerialization_profile_common_cflags)
SnippetSerialization_profile_cppflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetSerialization_profile_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetSerialization_profile_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetSerialization_profile_cppflags  += -O3 -fno-strict-aliasing
SnippetSerialization_profile_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetSerialization_profile_cppflags  += -fno-omit-frame-pointer -marm -funswitch-loops -finline-limit=300
SnippetSerialization_profile_lflags    := $(SnippetSerialization_custom_lflags)
SnippetSerialization_profile_lflags    += $(addprefix -L, $(SnippetSerialization_profile_lpaths))
SnippetSerialization_profile_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetSerialization_profile_libraries)) -Wl,--end-group
SnippetSerialization_profile_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetSerialization_profile_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetSerialization_profile_objsdir  = $(OBJS_DIR)/SnippetSerialization_profile
SnippetSerialization_profile_cpp_o    = $(addprefix $(SnippetSerialization_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetSerialization_cppfiles)))))
SnippetSerialization_profile_c_o      = $(addprefix $(SnippetSerialization_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetSerialization_cfiles)))))
SnippetSerialization_profile_cc_o      = $(addprefix $(SnippetSerialization_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetSerialization_ccfiles)))))
SnippetSerialization_profile_obj      = $(SnippetSerialization_profile_cpp_o) $(SnippetSerialization_profile_cc_o) $(SnippetSerialization_profile_c_o)
SnippetSerialization_profile_bin      := ./../../../Bin/android9_neon/SnippetSerializationPROFILE

clean_SnippetSerialization_profile: 
	@$(ECHO) clean SnippetSerialization profile
	@$(RMDIR) $(SnippetSerialization_profile_objsdir)
	@$(RMDIR) $(SnippetSerialization_profile_bin)

build_SnippetSerialization_profile: postbuild_SnippetSerialization_profile
postbuild_SnippetSerialization_profile: mainbuild_SnippetSerialization_profile
mainbuild_SnippetSerialization_profile: prebuild_SnippetSerialization_profile $(SnippetSerialization_profile_bin)
prebuild_SnippetSerialization_profile:

$(SnippetSerialization_profile_bin): $(SnippetSerialization_profile_obj) 
	@mkdir -p `dirname ./../../../Bin/android9_neon/SnippetSerializationPROFILE`
	@$(CCLD) $(SnippetSerialization_profile_obj) $(SnippetSerialization_profile_lflags) -o $(SnippetSerialization_profile_bin) 
	@$(ECHO) building $@ complete!

SnippetSerialization_profile_DEPDIR = $(dir $(@))/$(*F)
$(SnippetSerialization_profile_cpp_o): $(SnippetSerialization_profile_objsdir)/%.o:
	@$(ECHO) SnippetSerialization: compiling profile $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetSerialization_profile_objsdir),, $@))), $(SnippetSerialization_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetSerialization_profile_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetSerialization_profile_objsdir),, $@))), $(SnippetSerialization_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetSerialization_profile_objsdir),, $@))), $(SnippetSerialization_cppfiles))))))
	@cp $(SnippetSerialization_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetSerialization_profile_objsdir),, $@))), $(SnippetSerialization_cppfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetSerialization_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetSerialization_profile_objsdir),, $@))), $(SnippetSerialization_cppfiles))))).profile.P; \
	  rm -f $(SnippetSerialization_profile_DEPDIR).d

$(SnippetSerialization_profile_c_o): $(SnippetSerialization_profile_objsdir)/%.o:
	@$(ECHO) SnippetSerialization: compiling profile $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetSerialization_profile_objsdir),, $@))), $(SnippetSerialization_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetSerialization_profile_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetSerialization_profile_objsdir),, $@))), $(SnippetSerialization_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetSerialization_profile_objsdir),, $@))), $(SnippetSerialization_cfiles))))))
	@cp $(SnippetSerialization_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetSerialization_profile_objsdir),, $@))), $(SnippetSerialization_cfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetSerialization_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetSerialization_profile_objsdir),, $@))), $(SnippetSerialization_cfiles))))).profile.P; \
	  rm -f $(SnippetSerialization_profile_DEPDIR).d

$(SnippetSerialization_profile_cc_o): $(SnippetSerialization_profile_objsdir)/%.o:
	@$(ECHO) SnippetSerialization: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetSerialization_profile_objsdir),, $@))), $(SnippetSerialization_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetSerialization_profile_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetSerialization_profile_objsdir),, $@))), $(SnippetSerialization_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetSerialization_profile_objsdir),, $@))), $(SnippetSerialization_ccfiles)))
	@cp $(SnippetSerialization_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetSerialization_profile_objsdir),, $@))), $(SnippetSerialization_ccfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetSerialization_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetSerialization_profile_objsdir),, $@))), $(SnippetSerialization_ccfiles))))).profile.P; \
	  rm -f $(SnippetSerialization_profile_DEPDIR).d

SnippetSerialization_release_hpaths    := 
SnippetSerialization_release_hpaths    += ./../../../Source/shared/general/shared
SnippetSerialization_release_hpaths    += ./../../../Include
SnippetSerialization_release_hpaths    += ./../../../Source/foundation/include
SnippetSerialization_release_hpaths    += ./../../../Source/Common/src
SnippetSerialization_release_hpaths    += ./../../../Source/GeomUtils/src
SnippetSerialization_release_hpaths    += ./../../../Source/GeomUtils/headers
SnippetSerialization_release_hpaths    += ./../../../Source/GeomUtils/include
SnippetSerialization_release_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetSerialization_release_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetSerialization_release_lpaths    := 
SnippetSerialization_release_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetSerialization_release_lpaths    += ./../../../Lib/android9_neon
SnippetSerialization_release_defines   := $(SnippetSerialization_custom_defines)
SnippetSerialization_release_defines   += ANDROID
SnippetSerialization_release_defines   += GLES2
SnippetSerialization_release_defines   += __ARM_ARCH_5__
SnippetSerialization_release_defines   += __ARM_ARCH_5T__
SnippetSerialization_release_defines   += __ARM_ARCH_5E__
SnippetSerialization_release_defines   += __ARM_ARCH_5TE__
SnippetSerialization_release_defines   += NDEBUG
SnippetSerialization_release_defines   += PHYSX_PROFILE_SDK
SnippetSerialization_release_libraries := 
SnippetSerialization_release_libraries += log
SnippetSerialization_release_libraries += gnustl_static
SnippetSerialization_release_libraries += supc++
SnippetSerialization_release_libraries += m
SnippetSerialization_release_libraries += c
SnippetSerialization_release_libraries += nvToolsExt
SnippetSerialization_release_libraries += PhysX3Common
SnippetSerialization_release_libraries += PvdRuntime
SnippetSerialization_release_libraries += SimulationController
SnippetSerialization_release_libraries += SceneQuery
SnippetSerialization_release_libraries += LowLevel
SnippetSerialization_release_libraries += LowLevelCloth
SnippetSerialization_release_libraries += PhysX3
SnippetSerialization_release_libraries += PhysX3Vehicle
SnippetSerialization_release_libraries += PhysX3Cooking
SnippetSerialization_release_libraries += PhysX3Extensions
SnippetSerialization_release_libraries += PhysX3CharacterKinematic
SnippetSerialization_release_libraries += PhysXProfileSDK
SnippetSerialization_release_libraries += PxTask
SnippetSerialization_release_libraries += PhysXVisualDebuggerSDK
SnippetSerialization_release_common_cflags	:= $(SnippetSerialization_custom_cflags)
SnippetSerialization_release_common_cflags    += -MMD
SnippetSerialization_release_common_cflags    += $(addprefix -D, $(SnippetSerialization_release_defines))
SnippetSerialization_release_common_cflags    += $(addprefix -I, $(SnippetSerialization_release_hpaths))
SnippetSerialization_release_cflags	:= $(SnippetSerialization_release_common_cflags)
SnippetSerialization_release_cflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetSerialization_release_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetSerialization_release_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetSerialization_release_cflags  += -O3 -fno-strict-aliasing
SnippetSerialization_release_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetSerialization_release_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetSerialization_release_cppflags	:= $(SnippetSerialization_release_common_cflags)
SnippetSerialization_release_cppflags  += -fpic -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetSerialization_release_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetSerialization_release_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetSerialization_release_cppflags  += -O3 -fno-strict-aliasing
SnippetSerialization_release_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetSerialization_release_cppflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetSerialization_release_lflags    := $(SnippetSerialization_custom_lflags)
SnippetSerialization_release_lflags    += $(addprefix -L, $(SnippetSerialization_release_lpaths))
SnippetSerialization_release_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetSerialization_release_libraries)) -Wl,--end-group
SnippetSerialization_release_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetSerialization_release_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetSerialization_release_objsdir  = $(OBJS_DIR)/SnippetSerialization_release
SnippetSerialization_release_cpp_o    = $(addprefix $(SnippetSerialization_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetSerialization_cppfiles)))))
SnippetSerialization_release_c_o      = $(addprefix $(SnippetSerialization_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetSerialization_cfiles)))))
SnippetSerialization_release_cc_o      = $(addprefix $(SnippetSerialization_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetSerialization_ccfiles)))))
SnippetSerialization_release_obj      = $(SnippetSerialization_release_cpp_o) $(SnippetSerialization_release_cc_o) $(SnippetSerialization_release_c_o)
SnippetSerialization_release_bin      := ./../../../Bin/android9_neon/SnippetSerialization

clean_SnippetSerialization_release: 
	@$(ECHO) clean SnippetSerialization release
	@$(RMDIR) $(SnippetSerialization_release_objsdir)
	@$(RMDIR) $(SnippetSerialization_release_bin)

build_SnippetSerialization_release: postbuild_SnippetSerialization_release
postbuild_SnippetSerialization_release: mainbuild_SnippetSerialization_release
mainbuild_SnippetSerialization_release: prebuild_SnippetSerialization_release $(SnippetSerialization_release_bin)
prebuild_SnippetSerialization_release:

$(SnippetSerialization_release_bin): $(SnippetSerialization_release_obj) 
	@mkdir -p `dirname ./../../../Bin/android9_neon/SnippetSerialization`
	@$(CCLD) $(SnippetSerialization_release_obj) $(SnippetSerialization_release_lflags) -o $(SnippetSerialization_release_bin) 
	@$(ECHO) building $@ complete!

SnippetSerialization_release_DEPDIR = $(dir $(@))/$(*F)
$(SnippetSerialization_release_cpp_o): $(SnippetSerialization_release_objsdir)/%.o:
	@$(ECHO) SnippetSerialization: compiling release $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetSerialization_release_objsdir),, $@))), $(SnippetSerialization_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetSerialization_release_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetSerialization_release_objsdir),, $@))), $(SnippetSerialization_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetSerialization_release_objsdir),, $@))), $(SnippetSerialization_cppfiles))))))
	@cp $(SnippetSerialization_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetSerialization_release_objsdir),, $@))), $(SnippetSerialization_cppfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetSerialization_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetSerialization_release_objsdir),, $@))), $(SnippetSerialization_cppfiles))))).release.P; \
	  rm -f $(SnippetSerialization_release_DEPDIR).d

$(SnippetSerialization_release_c_o): $(SnippetSerialization_release_objsdir)/%.o:
	@$(ECHO) SnippetSerialization: compiling release $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetSerialization_release_objsdir),, $@))), $(SnippetSerialization_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetSerialization_release_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetSerialization_release_objsdir),, $@))), $(SnippetSerialization_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetSerialization_release_objsdir),, $@))), $(SnippetSerialization_cfiles))))))
	@cp $(SnippetSerialization_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetSerialization_release_objsdir),, $@))), $(SnippetSerialization_cfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetSerialization_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetSerialization_release_objsdir),, $@))), $(SnippetSerialization_cfiles))))).release.P; \
	  rm -f $(SnippetSerialization_release_DEPDIR).d

$(SnippetSerialization_release_cc_o): $(SnippetSerialization_release_objsdir)/%.o:
	@$(ECHO) SnippetSerialization: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetSerialization_release_objsdir),, $@))), $(SnippetSerialization_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetSerialization_release_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetSerialization_release_objsdir),, $@))), $(SnippetSerialization_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetSerialization_release_objsdir),, $@))), $(SnippetSerialization_ccfiles)))
	@cp $(SnippetSerialization_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetSerialization_release_objsdir),, $@))), $(SnippetSerialization_ccfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetSerialization_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetSerialization_release_objsdir),, $@))), $(SnippetSerialization_ccfiles))))).release.P; \
	  rm -f $(SnippetSerialization_release_DEPDIR).d

clean_SnippetSerialization:  clean_SnippetSerialization_debug clean_SnippetSerialization_checked clean_SnippetSerialization_profile clean_SnippetSerialization_release
	@rm -rf $(DEPSDIR)
