# Makefile generated by XPJ for ANDROID
-include Makefile.custom
ProjectName = PhysXCharacterKinematic
PhysXCharacterKinematic_cppfiles   += ./../../PhysXCharacterKinematic/src/CctBoxController.cpp
PhysXCharacterKinematic_cppfiles   += ./../../PhysXCharacterKinematic/src/CctCapsuleController.cpp
PhysXCharacterKinematic_cppfiles   += ./../../PhysXCharacterKinematic/src/CctCharacterController.cpp
PhysXCharacterKinematic_cppfiles   += ./../../PhysXCharacterKinematic/src/CctCharacterControllerCallbacks.cpp
PhysXCharacterKinematic_cppfiles   += ./../../PhysXCharacterKinematic/src/CctCharacterControllerManager.cpp
PhysXCharacterKinematic_cppfiles   += ./../../PhysXCharacterKinematic/src/CctController.cpp
PhysXCharacterKinematic_cppfiles   += ./../../PhysXCharacterKinematic/src/CctObstacleContext.cpp
PhysXCharacterKinematic_cppfiles   += ./../../PhysXCharacterKinematic/src/CctSweptBox.cpp
PhysXCharacterKinematic_cppfiles   += ./../../PhysXCharacterKinematic/src/CctSweptCapsule.cpp
PhysXCharacterKinematic_cppfiles   += ./../../PhysXCharacterKinematic/src/CctSweptVolume.cpp

PhysXCharacterKinematic_cpp_checked_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.checked.P, $(PhysXCharacterKinematic_cppfiles)))))
PhysXCharacterKinematic_c_checked_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.checked.P, $(PhysXCharacterKinematic_cfiles)))))
PhysXCharacterKinematic_cc_checked_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.checked.P, $(PhysXCharacterKinematic_ccfiles)))))
PhysXCharacterKinematic_checked_dep      = $(PhysXCharacterKinematic_cpp_checked_dep) $(PhysXCharacterKinematic_cc_checked_dep) $(PhysXCharacterKinematic_c_checked_dep)
-include $(PhysXCharacterKinematic_checked_dep)
PhysXCharacterKinematic_cpp_profile_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.profile.P, $(PhysXCharacterKinematic_cppfiles)))))
PhysXCharacterKinematic_c_profile_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.profile.P, $(PhysXCharacterKinematic_cfiles)))))
PhysXCharacterKinematic_cc_profile_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.profile.P, $(PhysXCharacterKinematic_ccfiles)))))
PhysXCharacterKinematic_profile_dep      = $(PhysXCharacterKinematic_cpp_profile_dep) $(PhysXCharacterKinematic_cc_profile_dep) $(PhysXCharacterKinematic_c_profile_dep)
-include $(PhysXCharacterKinematic_profile_dep)
PhysXCharacterKinematic_cpp_release_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.release.P, $(PhysXCharacterKinematic_cppfiles)))))
PhysXCharacterKinematic_c_release_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.release.P, $(PhysXCharacterKinematic_cfiles)))))
PhysXCharacterKinematic_cc_release_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.release.P, $(PhysXCharacterKinematic_ccfiles)))))
PhysXCharacterKinematic_release_dep      = $(PhysXCharacterKinematic_cpp_release_dep) $(PhysXCharacterKinematic_cc_release_dep) $(PhysXCharacterKinematic_c_release_dep)
-include $(PhysXCharacterKinematic_release_dep)
PhysXCharacterKinematic_checked_hpaths    := 
PhysXCharacterKinematic_checked_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
PhysXCharacterKinematic_checked_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
PhysXCharacterKinematic_checked_hpaths    += ./../../../Include/foundation
PhysXCharacterKinematic_checked_hpaths    += ./../../foundation/include
PhysXCharacterKinematic_checked_hpaths    += ./../../../Include/physxprofilesdk
PhysXCharacterKinematic_checked_hpaths    += ./../../../Include/physxvisualdebuggersdk
PhysXCharacterKinematic_checked_hpaths    += ./../../../Include/characterkinematic
PhysXCharacterKinematic_checked_hpaths    += ./../../../Include/common
PhysXCharacterKinematic_checked_hpaths    += ./../../../Include/geometry
PhysXCharacterKinematic_checked_hpaths    += ./../../../Include/extensions
PhysXCharacterKinematic_checked_hpaths    += ./../../../Include/pxtask
PhysXCharacterKinematic_checked_hpaths    += ./../../../Include
PhysXCharacterKinematic_checked_hpaths    += ./../../GeomUtils/headers
PhysXCharacterKinematic_checked_hpaths    += ./../../Common/src
PhysXCharacterKinematic_checked_lpaths    := 
PhysXCharacterKinematic_checked_lpaths    += ./../../../Lib/android8
PhysXCharacterKinematic_checked_defines   := $(PhysXCharacterKinematic_custom_defines)
PhysXCharacterKinematic_checked_defines   += ANDROID
PhysXCharacterKinematic_checked_defines   += GLES2
PhysXCharacterKinematic_checked_defines   += __ARM_ARCH_5__
PhysXCharacterKinematic_checked_defines   += __ARM_ARCH_5T__
PhysXCharacterKinematic_checked_defines   += __ARM_ARCH_5E__
PhysXCharacterKinematic_checked_defines   += __ARM_ARCH_5TE__
PhysXCharacterKinematic_checked_defines   += PX_PHYSX_STATIC_LIB
PhysXCharacterKinematic_checked_defines   += NDEBUG
PhysXCharacterKinematic_checked_defines   += PX_CHECKED
PhysXCharacterKinematic_checked_defines   += PX_SUPPORT_VISUAL_DEBUGGER
PhysXCharacterKinematic_checked_defines   += PX_NVTX
PhysXCharacterKinematic_checked_libraries := 
PhysXCharacterKinematic_checked_libraries += PhysX3ExtensionsCHECKED
PhysXCharacterKinematic_checked_common_cflags	:= $(PhysXCharacterKinematic_custom_cflags)
PhysXCharacterKinematic_checked_common_cflags    += -MMD
PhysXCharacterKinematic_checked_common_cflags    += $(addprefix -D, $(PhysXCharacterKinematic_checked_defines))
PhysXCharacterKinematic_checked_common_cflags    += $(addprefix -I, $(PhysXCharacterKinematic_checked_hpaths))
PhysXCharacterKinematic_checked_cflags	:= $(PhysXCharacterKinematic_checked_common_cflags)
PhysXCharacterKinematic_checked_cflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
PhysXCharacterKinematic_checked_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
PhysXCharacterKinematic_checked_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-8/arch-arm
PhysXCharacterKinematic_checked_cflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
PhysXCharacterKinematic_checked_cflags  += -ffunction-sections -funwind-tables -fstack-protector
PhysXCharacterKinematic_checked_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
PhysXCharacterKinematic_checked_cppflags	:= $(PhysXCharacterKinematic_checked_common_cflags)
PhysXCharacterKinematic_checked_cppflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
PhysXCharacterKinematic_checked_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
PhysXCharacterKinematic_checked_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-8/arch-arm
PhysXCharacterKinematic_checked_cppflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
PhysXCharacterKinematic_checked_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
PhysXCharacterKinematic_checked_cppflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
PhysXCharacterKinematic_checked_lflags    := $(PhysXCharacterKinematic_custom_lflags)
PhysXCharacterKinematic_checked_lflags    += $(addprefix -L, $(PhysXCharacterKinematic_checked_lpaths))
PhysXCharacterKinematic_checked_lflags    += -Wl,--start-group $(addprefix -l, $(PhysXCharacterKinematic_checked_libraries)) -Wl,--end-group
PhysXCharacterKinematic_checked_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-8/arch-arm
PhysXCharacterKinematic_checked_objsdir  = $(OBJS_DIR)/PhysXCharacterKinematic_checked
PhysXCharacterKinematic_checked_cpp_o    = $(addprefix $(PhysXCharacterKinematic_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(PhysXCharacterKinematic_cppfiles)))))
PhysXCharacterKinematic_checked_c_o      = $(addprefix $(PhysXCharacterKinematic_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(PhysXCharacterKinematic_cfiles)))))
PhysXCharacterKinematic_checked_cc_o      = $(addprefix $(PhysXCharacterKinematic_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(PhysXCharacterKinematic_ccfiles)))))
PhysXCharacterKinematic_checked_obj      = $(PhysXCharacterKinematic_checked_cpp_o) $(PhysXCharacterKinematic_checked_cc_o) $(PhysXCharacterKinematic_checked_c_o)
PhysXCharacterKinematic_checked_bin      := ./../../../Lib/android8/libPhysX3CharacterKinematicCHECKED.a

clean_PhysXCharacterKinematic_checked: 
	@$(ECHO) clean PhysXCharacterKinematic checked
	@$(RMDIR) $(PhysXCharacterKinematic_checked_objsdir)
	@$(RMDIR) $(PhysXCharacterKinematic_checked_bin)

build_PhysXCharacterKinematic_checked: postbuild_PhysXCharacterKinematic_checked
postbuild_PhysXCharacterKinematic_checked: mainbuild_PhysXCharacterKinematic_checked
mainbuild_PhysXCharacterKinematic_checked: prebuild_PhysXCharacterKinematic_checked $(PhysXCharacterKinematic_checked_bin)
prebuild_PhysXCharacterKinematic_checked:

$(PhysXCharacterKinematic_checked_bin): $(PhysXCharacterKinematic_checked_obj) build_PhysXExtensions_checked 
	@mkdir -p `dirname ./../../../Lib/android8/libPhysX3CharacterKinematicCHECKED.a`
	@$(AR) rcs $(PhysXCharacterKinematic_checked_bin) $(PhysXCharacterKinematic_checked_obj)
	@$(ECHO) building $@ complete!

PhysXCharacterKinematic_checked_DEPDIR = $(dir $(@))/$(*F)
$(PhysXCharacterKinematic_checked_cpp_o): $(PhysXCharacterKinematic_checked_objsdir)/%.o:
	@$(ECHO) PhysXCharacterKinematic: compiling checked $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCharacterKinematic_checked_objsdir),, $@))), $(PhysXCharacterKinematic_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(PhysXCharacterKinematic_checked_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCharacterKinematic_checked_objsdir),, $@))), $(PhysXCharacterKinematic_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCharacterKinematic_checked_objsdir),, $@))), $(PhysXCharacterKinematic_cppfiles))))))
	@cp $(PhysXCharacterKinematic_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCharacterKinematic_checked_objsdir),, $@))), $(PhysXCharacterKinematic_cppfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXCharacterKinematic_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCharacterKinematic_checked_objsdir),, $@))), $(PhysXCharacterKinematic_cppfiles))))).checked.P; \
	  rm -f $(PhysXCharacterKinematic_checked_DEPDIR).d

$(PhysXCharacterKinematic_checked_c_o): $(PhysXCharacterKinematic_checked_objsdir)/%.o:
	@$(ECHO) PhysXCharacterKinematic: compiling checked $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCharacterKinematic_checked_objsdir),, $@))), $(PhysXCharacterKinematic_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(PhysXCharacterKinematic_checked_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCharacterKinematic_checked_objsdir),, $@))), $(PhysXCharacterKinematic_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCharacterKinematic_checked_objsdir),, $@))), $(PhysXCharacterKinematic_cfiles))))))
	@cp $(PhysXCharacterKinematic_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCharacterKinematic_checked_objsdir),, $@))), $(PhysXCharacterKinematic_cfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXCharacterKinematic_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCharacterKinematic_checked_objsdir),, $@))), $(PhysXCharacterKinematic_cfiles))))).checked.P; \
	  rm -f $(PhysXCharacterKinematic_checked_DEPDIR).d

$(PhysXCharacterKinematic_checked_cc_o): $(PhysXCharacterKinematic_checked_objsdir)/%.o:
	@$(ECHO) PhysXCharacterKinematic: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCharacterKinematic_checked_objsdir),, $@))), $(PhysXCharacterKinematic_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(PhysXCharacterKinematic_checked_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCharacterKinematic_checked_objsdir),, $@))), $(PhysXCharacterKinematic_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCharacterKinematic_checked_objsdir),, $@))), $(PhysXCharacterKinematic_ccfiles)))
	@cp $(PhysXCharacterKinematic_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCharacterKinematic_checked_objsdir),, $@))), $(PhysXCharacterKinematic_ccfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXCharacterKinematic_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCharacterKinematic_checked_objsdir),, $@))), $(PhysXCharacterKinematic_ccfiles))))).checked.P; \
	  rm -f $(PhysXCharacterKinematic_checked_DEPDIR).d

PhysXCharacterKinematic_profile_hpaths    := 
PhysXCharacterKinematic_profile_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
PhysXCharacterKinematic_profile_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
PhysXCharacterKinematic_profile_hpaths    += ./../../../Include/foundation
PhysXCharacterKinematic_profile_hpaths    += ./../../foundation/include
PhysXCharacterKinematic_profile_hpaths    += ./../../../Include/physxprofilesdk
PhysXCharacterKinematic_profile_hpaths    += ./../../../Include/physxvisualdebuggersdk
PhysXCharacterKinematic_profile_hpaths    += ./../../../Include/characterkinematic
PhysXCharacterKinematic_profile_hpaths    += ./../../../Include/common
PhysXCharacterKinematic_profile_hpaths    += ./../../../Include/geometry
PhysXCharacterKinematic_profile_hpaths    += ./../../../Include/extensions
PhysXCharacterKinematic_profile_hpaths    += ./../../../Include/pxtask
PhysXCharacterKinematic_profile_hpaths    += ./../../../Include
PhysXCharacterKinematic_profile_hpaths    += ./../../GeomUtils/headers
PhysXCharacterKinematic_profile_hpaths    += ./../../Common/src
PhysXCharacterKinematic_profile_lpaths    := 
PhysXCharacterKinematic_profile_lpaths    += ./../../../Lib/android8
PhysXCharacterKinematic_profile_defines   := $(PhysXCharacterKinematic_custom_defines)
PhysXCharacterKinematic_profile_defines   += ANDROID
PhysXCharacterKinematic_profile_defines   += GLES2
PhysXCharacterKinematic_profile_defines   += __ARM_ARCH_5__
PhysXCharacterKinematic_profile_defines   += __ARM_ARCH_5T__
PhysXCharacterKinematic_profile_defines   += __ARM_ARCH_5E__
PhysXCharacterKinematic_profile_defines   += __ARM_ARCH_5TE__
PhysXCharacterKinematic_profile_defines   += PX_PHYSX_STATIC_LIB
PhysXCharacterKinematic_profile_defines   += NDEBUG
PhysXCharacterKinematic_profile_defines   += PX_PROFILE
PhysXCharacterKinematic_profile_defines   += PX_SUPPORT_VISUAL_DEBUGGER
PhysXCharacterKinematic_profile_defines   += PX_NVTX
PhysXCharacterKinematic_profile_libraries := 
PhysXCharacterKinematic_profile_libraries += PhysX3ExtensionsPROFILE
PhysXCharacterKinematic_profile_common_cflags	:= $(PhysXCharacterKinematic_custom_cflags)
PhysXCharacterKinematic_profile_common_cflags    += -MMD
PhysXCharacterKinematic_profile_common_cflags    += $(addprefix -D, $(PhysXCharacterKinematic_profile_defines))
PhysXCharacterKinematic_profile_common_cflags    += $(addprefix -I, $(PhysXCharacterKinematic_profile_hpaths))
PhysXCharacterKinematic_profile_cflags	:= $(PhysXCharacterKinematic_profile_common_cflags)
PhysXCharacterKinematic_profile_cflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
PhysXCharacterKinematic_profile_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
PhysXCharacterKinematic_profile_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-8/arch-arm
PhysXCharacterKinematic_profile_cflags  += -O3 -fno-strict-aliasing
PhysXCharacterKinematic_profile_cflags  += -ffunction-sections -funwind-tables -fstack-protector
PhysXCharacterKinematic_profile_cflags  += -fno-omit-frame-pointer -marm -funswitch-loops -finline-limit=300
PhysXCharacterKinematic_profile_cppflags	:= $(PhysXCharacterKinematic_profile_common_cflags)
PhysXCharacterKinematic_profile_cppflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
PhysXCharacterKinematic_profile_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
PhysXCharacterKinematic_profile_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-8/arch-arm
PhysXCharacterKinematic_profile_cppflags  += -O3 -fno-strict-aliasing
PhysXCharacterKinematic_profile_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
PhysXCharacterKinematic_profile_cppflags  += -fno-omit-frame-pointer -marm -funswitch-loops -finline-limit=300
PhysXCharacterKinematic_profile_lflags    := $(PhysXCharacterKinematic_custom_lflags)
PhysXCharacterKinematic_profile_lflags    += $(addprefix -L, $(PhysXCharacterKinematic_profile_lpaths))
PhysXCharacterKinematic_profile_lflags    += -Wl,--start-group $(addprefix -l, $(PhysXCharacterKinematic_profile_libraries)) -Wl,--end-group
PhysXCharacterKinematic_profile_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-8/arch-arm
PhysXCharacterKinematic_profile_objsdir  = $(OBJS_DIR)/PhysXCharacterKinematic_profile
PhysXCharacterKinematic_profile_cpp_o    = $(addprefix $(PhysXCharacterKinematic_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(PhysXCharacterKinematic_cppfiles)))))
PhysXCharacterKinematic_profile_c_o      = $(addprefix $(PhysXCharacterKinematic_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(PhysXCharacterKinematic_cfiles)))))
PhysXCharacterKinematic_profile_cc_o      = $(addprefix $(PhysXCharacterKinematic_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(PhysXCharacterKinematic_ccfiles)))))
PhysXCharacterKinematic_profile_obj      = $(PhysXCharacterKinematic_profile_cpp_o) $(PhysXCharacterKinematic_profile_cc_o) $(PhysXCharacterKinematic_profile_c_o)
PhysXCharacterKinematic_profile_bin      := ./../../../Lib/android8/libPhysX3CharacterKinematicPROFILE.a

clean_PhysXCharacterKinematic_profile: 
	@$(ECHO) clean PhysXCharacterKinematic profile
	@$(RMDIR) $(PhysXCharacterKinematic_profile_objsdir)
	@$(RMDIR) $(PhysXCharacterKinematic_profile_bin)

build_PhysXCharacterKinematic_profile: postbuild_PhysXCharacterKinematic_profile
postbuild_PhysXCharacterKinematic_profile: mainbuild_PhysXCharacterKinematic_profile
mainbuild_PhysXCharacterKinematic_profile: prebuild_PhysXCharacterKinematic_profile $(PhysXCharacterKinematic_profile_bin)
prebuild_PhysXCharacterKinematic_profile:

$(PhysXCharacterKinematic_profile_bin): $(PhysXCharacterKinematic_profile_obj) build_PhysXExtensions_profile 
	@mkdir -p `dirname ./../../../Lib/android8/libPhysX3CharacterKinematicPROFILE.a`
	@$(AR) rcs $(PhysXCharacterKinematic_profile_bin) $(PhysXCharacterKinematic_profile_obj)
	@$(ECHO) building $@ complete!

PhysXCharacterKinematic_profile_DEPDIR = $(dir $(@))/$(*F)
$(PhysXCharacterKinematic_profile_cpp_o): $(PhysXCharacterKinematic_profile_objsdir)/%.o:
	@$(ECHO) PhysXCharacterKinematic: compiling profile $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCharacterKinematic_profile_objsdir),, $@))), $(PhysXCharacterKinematic_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(PhysXCharacterKinematic_profile_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCharacterKinematic_profile_objsdir),, $@))), $(PhysXCharacterKinematic_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCharacterKinematic_profile_objsdir),, $@))), $(PhysXCharacterKinematic_cppfiles))))))
	@cp $(PhysXCharacterKinematic_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCharacterKinematic_profile_objsdir),, $@))), $(PhysXCharacterKinematic_cppfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXCharacterKinematic_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCharacterKinematic_profile_objsdir),, $@))), $(PhysXCharacterKinematic_cppfiles))))).profile.P; \
	  rm -f $(PhysXCharacterKinematic_profile_DEPDIR).d

$(PhysXCharacterKinematic_profile_c_o): $(PhysXCharacterKinematic_profile_objsdir)/%.o:
	@$(ECHO) PhysXCharacterKinematic: compiling profile $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCharacterKinematic_profile_objsdir),, $@))), $(PhysXCharacterKinematic_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(PhysXCharacterKinematic_profile_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCharacterKinematic_profile_objsdir),, $@))), $(PhysXCharacterKinematic_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCharacterKinematic_profile_objsdir),, $@))), $(PhysXCharacterKinematic_cfiles))))))
	@cp $(PhysXCharacterKinematic_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCharacterKinematic_profile_objsdir),, $@))), $(PhysXCharacterKinematic_cfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXCharacterKinematic_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCharacterKinematic_profile_objsdir),, $@))), $(PhysXCharacterKinematic_cfiles))))).profile.P; \
	  rm -f $(PhysXCharacterKinematic_profile_DEPDIR).d

$(PhysXCharacterKinematic_profile_cc_o): $(PhysXCharacterKinematic_profile_objsdir)/%.o:
	@$(ECHO) PhysXCharacterKinematic: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCharacterKinematic_profile_objsdir),, $@))), $(PhysXCharacterKinematic_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(PhysXCharacterKinematic_profile_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCharacterKinematic_profile_objsdir),, $@))), $(PhysXCharacterKinematic_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCharacterKinematic_profile_objsdir),, $@))), $(PhysXCharacterKinematic_ccfiles)))
	@cp $(PhysXCharacterKinematic_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCharacterKinematic_profile_objsdir),, $@))), $(PhysXCharacterKinematic_ccfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXCharacterKinematic_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCharacterKinematic_profile_objsdir),, $@))), $(PhysXCharacterKinematic_ccfiles))))).profile.P; \
	  rm -f $(PhysXCharacterKinematic_profile_DEPDIR).d

PhysXCharacterKinematic_release_hpaths    := 
PhysXCharacterKinematic_release_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
PhysXCharacterKinematic_release_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
PhysXCharacterKinematic_release_hpaths    += ./../../../Include/foundation
PhysXCharacterKinematic_release_hpaths    += ./../../foundation/include
PhysXCharacterKinematic_release_hpaths    += ./../../../Include/physxprofilesdk
PhysXCharacterKinematic_release_hpaths    += ./../../../Include/physxvisualdebuggersdk
PhysXCharacterKinematic_release_hpaths    += ./../../../Include/characterkinematic
PhysXCharacterKinematic_release_hpaths    += ./../../../Include/common
PhysXCharacterKinematic_release_hpaths    += ./../../../Include/geometry
PhysXCharacterKinematic_release_hpaths    += ./../../../Include/extensions
PhysXCharacterKinematic_release_hpaths    += ./../../../Include/pxtask
PhysXCharacterKinematic_release_hpaths    += ./../../../Include
PhysXCharacterKinematic_release_hpaths    += ./../../GeomUtils/headers
PhysXCharacterKinematic_release_hpaths    += ./../../Common/src
PhysXCharacterKinematic_release_lpaths    := 
PhysXCharacterKinematic_release_lpaths    += ./../../../Lib/android8
PhysXCharacterKinematic_release_defines   := $(PhysXCharacterKinematic_custom_defines)
PhysXCharacterKinematic_release_defines   += ANDROID
PhysXCharacterKinematic_release_defines   += GLES2
PhysXCharacterKinematic_release_defines   += __ARM_ARCH_5__
PhysXCharacterKinematic_release_defines   += __ARM_ARCH_5T__
PhysXCharacterKinematic_release_defines   += __ARM_ARCH_5E__
PhysXCharacterKinematic_release_defines   += __ARM_ARCH_5TE__
PhysXCharacterKinematic_release_defines   += PX_PHYSX_STATIC_LIB
PhysXCharacterKinematic_release_defines   += NDEBUG
PhysXCharacterKinematic_release_libraries := 
PhysXCharacterKinematic_release_libraries += PhysX3Extensions
PhysXCharacterKinematic_release_common_cflags	:= $(PhysXCharacterKinematic_custom_cflags)
PhysXCharacterKinematic_release_common_cflags    += -MMD
PhysXCharacterKinematic_release_common_cflags    += $(addprefix -D, $(PhysXCharacterKinematic_release_defines))
PhysXCharacterKinematic_release_common_cflags    += $(addprefix -I, $(PhysXCharacterKinematic_release_hpaths))
PhysXCharacterKinematic_release_cflags	:= $(PhysXCharacterKinematic_release_common_cflags)
PhysXCharacterKinematic_release_cflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
PhysXCharacterKinematic_release_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
PhysXCharacterKinematic_release_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-8/arch-arm
PhysXCharacterKinematic_release_cflags  += -O3 -fno-strict-aliasing
PhysXCharacterKinematic_release_cflags  += -ffunction-sections -funwind-tables -fstack-protector
PhysXCharacterKinematic_release_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
PhysXCharacterKinematic_release_cppflags	:= $(PhysXCharacterKinematic_release_common_cflags)
PhysXCharacterKinematic_release_cppflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
PhysXCharacterKinematic_release_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
PhysXCharacterKinematic_release_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-8/arch-arm
PhysXCharacterKinematic_release_cppflags  += -O3 -fno-strict-aliasing
PhysXCharacterKinematic_release_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
PhysXCharacterKinematic_release_cppflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
PhysXCharacterKinematic_release_lflags    := $(PhysXCharacterKinematic_custom_lflags)
PhysXCharacterKinematic_release_lflags    += $(addprefix -L, $(PhysXCharacterKinematic_release_lpaths))
PhysXCharacterKinematic_release_lflags    += -Wl,--start-group $(addprefix -l, $(PhysXCharacterKinematic_release_libraries)) -Wl,--end-group
PhysXCharacterKinematic_release_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-8/arch-arm
PhysXCharacterKinematic_release_objsdir  = $(OBJS_DIR)/PhysXCharacterKinematic_release
PhysXCharacterKinematic_release_cpp_o    = $(addprefix $(PhysXCharacterKinematic_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(PhysXCharacterKinematic_cppfiles)))))
PhysXCharacterKinematic_release_c_o      = $(addprefix $(PhysXCharacterKinematic_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(PhysXCharacterKinematic_cfiles)))))
PhysXCharacterKinematic_release_cc_o      = $(addprefix $(PhysXCharacterKinematic_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(PhysXCharacterKinematic_ccfiles)))))
PhysXCharacterKinematic_release_obj      = $(PhysXCharacterKinematic_release_cpp_o) $(PhysXCharacterKinematic_release_cc_o) $(PhysXCharacterKinematic_release_c_o)
PhysXCharacterKinematic_release_bin      := ./../../../Lib/android8/libPhysX3CharacterKinematic.a

clean_PhysXCharacterKinematic_release: 
	@$(ECHO) clean PhysXCharacterKinematic release
	@$(RMDIR) $(PhysXCharacterKinematic_release_objsdir)
	@$(RMDIR) $(PhysXCharacterKinematic_release_bin)

build_PhysXCharacterKinematic_release: postbuild_PhysXCharacterKinematic_release
postbuild_PhysXCharacterKinematic_release: mainbuild_PhysXCharacterKinematic_release
mainbuild_PhysXCharacterKinematic_release: prebuild_PhysXCharacterKinematic_release $(PhysXCharacterKinematic_release_bin)
prebuild_PhysXCharacterKinematic_release:

$(PhysXCharacterKinematic_release_bin): $(PhysXCharacterKinematic_release_obj) build_PhysXExtensions_release 
	@mkdir -p `dirname ./../../../Lib/android8/libPhysX3CharacterKinematic.a`
	@$(AR) rcs $(PhysXCharacterKinematic_release_bin) $(PhysXCharacterKinematic_release_obj)
	@$(ECHO) building $@ complete!

PhysXCharacterKinematic_release_DEPDIR = $(dir $(@))/$(*F)
$(PhysXCharacterKinematic_release_cpp_o): $(PhysXCharacterKinematic_release_objsdir)/%.o:
	@$(ECHO) PhysXCharacterKinematic: compiling release $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCharacterKinematic_release_objsdir),, $@))), $(PhysXCharacterKinematic_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(PhysXCharacterKinematic_release_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCharacterKinematic_release_objsdir),, $@))), $(PhysXCharacterKinematic_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCharacterKinematic_release_objsdir),, $@))), $(PhysXCharacterKinematic_cppfiles))))))
	@cp $(PhysXCharacterKinematic_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCharacterKinematic_release_objsdir),, $@))), $(PhysXCharacterKinematic_cppfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXCharacterKinematic_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCharacterKinematic_release_objsdir),, $@))), $(PhysXCharacterKinematic_cppfiles))))).release.P; \
	  rm -f $(PhysXCharacterKinematic_release_DEPDIR).d

$(PhysXCharacterKinematic_release_c_o): $(PhysXCharacterKinematic_release_objsdir)/%.o:
	@$(ECHO) PhysXCharacterKinematic: compiling release $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCharacterKinematic_release_objsdir),, $@))), $(PhysXCharacterKinematic_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(PhysXCharacterKinematic_release_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCharacterKinematic_release_objsdir),, $@))), $(PhysXCharacterKinematic_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCharacterKinematic_release_objsdir),, $@))), $(PhysXCharacterKinematic_cfiles))))))
	@cp $(PhysXCharacterKinematic_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCharacterKinematic_release_objsdir),, $@))), $(PhysXCharacterKinematic_cfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXCharacterKinematic_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCharacterKinematic_release_objsdir),, $@))), $(PhysXCharacterKinematic_cfiles))))).release.P; \
	  rm -f $(PhysXCharacterKinematic_release_DEPDIR).d

$(PhysXCharacterKinematic_release_cc_o): $(PhysXCharacterKinematic_release_objsdir)/%.o:
	@$(ECHO) PhysXCharacterKinematic: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCharacterKinematic_release_objsdir),, $@))), $(PhysXCharacterKinematic_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(PhysXCharacterKinematic_release_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCharacterKinematic_release_objsdir),, $@))), $(PhysXCharacterKinematic_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCharacterKinematic_release_objsdir),, $@))), $(PhysXCharacterKinematic_ccfiles)))
	@cp $(PhysXCharacterKinematic_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCharacterKinematic_release_objsdir),, $@))), $(PhysXCharacterKinematic_ccfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXCharacterKinematic_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCharacterKinematic_release_objsdir),, $@))), $(PhysXCharacterKinematic_ccfiles))))).release.P; \
	  rm -f $(PhysXCharacterKinematic_release_DEPDIR).d

clean_PhysXCharacterKinematic:  clean_PhysXCharacterKinematic_checked clean_PhysXCharacterKinematic_profile clean_PhysXCharacterKinematic_release
	@rm -rf $(DEPSDIR)
