# Makefile generated by XPJ for ANDROID
-include Makefile.custom
ProjectName = SnippetVehicleScale
SnippetVehicleScale_cppfiles   += ./../../SnippetVehicleScale/SnippetVehicleScale.cpp
SnippetVehicleScale_cppfiles   += ./../../SnippetVehicleScale/SnippetVehicleScaleRender.cpp
SnippetVehicleScale_cppfiles   += ./../../SnippetVehicleCommon/SnippetVehicle4WCreate.cpp
SnippetVehicleScale_cppfiles   += ./../../SnippetVehicleCommon/SnippetVehicleCreate.cpp
SnippetVehicleScale_cppfiles   += ./../../SnippetVehicleCommon/SnippetVehicleFilterShader.cpp
SnippetVehicleScale_cppfiles   += ./../../SnippetVehicleCommon/SnippetVehicleNoDriveCreate.cpp
SnippetVehicleScale_cppfiles   += ./../../SnippetVehicleCommon/SnippetVehicleRaycast.cpp
SnippetVehicleScale_cppfiles   += ./../../SnippetVehicleCommon/SnippetVehicleTankCreate.cpp
SnippetVehicleScale_cppfiles   += ./../../SnippetVehicleCommon/SnippetVehicleTireFriction.cpp

SnippetVehicleScale_cpp_debug_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.debug.P, $(SnippetVehicleScale_cppfiles)))))
SnippetVehicleScale_c_debug_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.debug.P, $(SnippetVehicleScale_cfiles)))))
SnippetVehicleScale_cc_debug_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.debug.P, $(SnippetVehicleScale_ccfiles)))))
SnippetVehicleScale_debug_dep      = $(SnippetVehicleScale_cpp_debug_dep) $(SnippetVehicleScale_cc_debug_dep) $(SnippetVehicleScale_c_debug_dep)
-include $(SnippetVehicleScale_debug_dep)
SnippetVehicleScale_cpp_checked_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.checked.P, $(SnippetVehicleScale_cppfiles)))))
SnippetVehicleScale_c_checked_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.checked.P, $(SnippetVehicleScale_cfiles)))))
SnippetVehicleScale_cc_checked_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.checked.P, $(SnippetVehicleScale_ccfiles)))))
SnippetVehicleScale_checked_dep      = $(SnippetVehicleScale_cpp_checked_dep) $(SnippetVehicleScale_cc_checked_dep) $(SnippetVehicleScale_c_checked_dep)
-include $(SnippetVehicleScale_checked_dep)
SnippetVehicleScale_cpp_profile_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.profile.P, $(SnippetVehicleScale_cppfiles)))))
SnippetVehicleScale_c_profile_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.profile.P, $(SnippetVehicleScale_cfiles)))))
SnippetVehicleScale_cc_profile_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.profile.P, $(SnippetVehicleScale_ccfiles)))))
SnippetVehicleScale_profile_dep      = $(SnippetVehicleScale_cpp_profile_dep) $(SnippetVehicleScale_cc_profile_dep) $(SnippetVehicleScale_c_profile_dep)
-include $(SnippetVehicleScale_profile_dep)
SnippetVehicleScale_cpp_release_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.release.P, $(SnippetVehicleScale_cppfiles)))))
SnippetVehicleScale_c_release_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.release.P, $(SnippetVehicleScale_cfiles)))))
SnippetVehicleScale_cc_release_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.release.P, $(SnippetVehicleScale_ccfiles)))))
SnippetVehicleScale_release_dep      = $(SnippetVehicleScale_cpp_release_dep) $(SnippetVehicleScale_cc_release_dep) $(SnippetVehicleScale_c_release_dep)
-include $(SnippetVehicleScale_release_dep)
SnippetVehicleScale_debug_hpaths    := 
SnippetVehicleScale_debug_hpaths    += ./../../../Source/shared/general/shared
SnippetVehicleScale_debug_hpaths    += ./../../../Include
SnippetVehicleScale_debug_hpaths    += ./../../../Source/foundation/include
SnippetVehicleScale_debug_hpaths    += ./../../../Source/Common/src
SnippetVehicleScale_debug_hpaths    += ./../../../Source/GeomUtils/src
SnippetVehicleScale_debug_hpaths    += ./../../../Source/GeomUtils/headers
SnippetVehicleScale_debug_hpaths    += ./../../../Source/GeomUtils/include
SnippetVehicleScale_debug_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetVehicleScale_debug_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetVehicleScale_debug_lpaths    := 
SnippetVehicleScale_debug_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetVehicleScale_debug_lpaths    += ./../../../Lib/android9
SnippetVehicleScale_debug_defines   := $(SnippetVehicleScale_custom_defines)
SnippetVehicleScale_debug_defines   += ANDROID
SnippetVehicleScale_debug_defines   += GLES2
SnippetVehicleScale_debug_defines   += __ARM_ARCH_5__
SnippetVehicleScale_debug_defines   += __ARM_ARCH_5T__
SnippetVehicleScale_debug_defines   += __ARM_ARCH_5E__
SnippetVehicleScale_debug_defines   += __ARM_ARCH_5TE__
SnippetVehicleScale_debug_defines   += _DEBUG
SnippetVehicleScale_debug_defines   += PX_DEBUG
SnippetVehicleScale_debug_defines   += PX_CHECKED
SnippetVehicleScale_debug_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetVehicleScale_debug_defines   += PX_NVTX
SnippetVehicleScale_debug_defines   += PHYSX_PROFILE_SDK
SnippetVehicleScale_debug_libraries := 
SnippetVehicleScale_debug_libraries += log
SnippetVehicleScale_debug_libraries += gnustl_static
SnippetVehicleScale_debug_libraries += supc++
SnippetVehicleScale_debug_libraries += m
SnippetVehicleScale_debug_libraries += c
SnippetVehicleScale_debug_libraries += nvToolsExt
SnippetVehicleScale_debug_libraries += PhysX3CommonCHECKED
SnippetVehicleScale_debug_libraries += PvdRuntimeCHECKED
SnippetVehicleScale_debug_libraries += SimulationControllerCHECKED
SnippetVehicleScale_debug_libraries += SceneQueryCHECKED
SnippetVehicleScale_debug_libraries += LowLevelCHECKED
SnippetVehicleScale_debug_libraries += LowLevelClothCHECKED
SnippetVehicleScale_debug_libraries += PhysX3CHECKED
SnippetVehicleScale_debug_libraries += PhysX3VehicleCHECKED
SnippetVehicleScale_debug_libraries += PhysX3CookingCHECKED
SnippetVehicleScale_debug_libraries += PhysX3ExtensionsCHECKED
SnippetVehicleScale_debug_libraries += PhysX3CharacterKinematicCHECKED
SnippetVehicleScale_debug_libraries += PhysXProfileSDKCHECKED
SnippetVehicleScale_debug_libraries += PxTaskCHECKED
SnippetVehicleScale_debug_libraries += PhysXVisualDebuggerSDKCHECKED
SnippetVehicleScale_debug_common_cflags	:= $(SnippetVehicleScale_custom_cflags)
SnippetVehicleScale_debug_common_cflags    += -MMD
SnippetVehicleScale_debug_common_cflags    += $(addprefix -D, $(SnippetVehicleScale_debug_defines))
SnippetVehicleScale_debug_common_cflags    += $(addprefix -I, $(SnippetVehicleScale_debug_hpaths))
SnippetVehicleScale_debug_cflags	:= $(SnippetVehicleScale_debug_common_cflags)
SnippetVehicleScale_debug_cflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetVehicleScale_debug_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetVehicleScale_debug_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleScale_debug_cflags  += -g3 -gdwarf-2
SnippetVehicleScale_debug_cppflags	:= $(SnippetVehicleScale_debug_common_cflags)
SnippetVehicleScale_debug_cppflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetVehicleScale_debug_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetVehicleScale_debug_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleScale_debug_cppflags  += -g3 -gdwarf-2
SnippetVehicleScale_debug_lflags    := $(SnippetVehicleScale_custom_lflags)
SnippetVehicleScale_debug_lflags    += $(addprefix -L, $(SnippetVehicleScale_debug_lpaths))
SnippetVehicleScale_debug_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetVehicleScale_debug_libraries)) -Wl,--end-group
SnippetVehicleScale_debug_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleScale_debug_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetVehicleScale_debug_objsdir  = $(OBJS_DIR)/SnippetVehicleScale_debug
SnippetVehicleScale_debug_cpp_o    = $(addprefix $(SnippetVehicleScale_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetVehicleScale_cppfiles)))))
SnippetVehicleScale_debug_c_o      = $(addprefix $(SnippetVehicleScale_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetVehicleScale_cfiles)))))
SnippetVehicleScale_debug_cc_o      = $(addprefix $(SnippetVehicleScale_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetVehicleScale_ccfiles)))))
SnippetVehicleScale_debug_obj      = $(SnippetVehicleScale_debug_cpp_o) $(SnippetVehicleScale_debug_cc_o) $(SnippetVehicleScale_debug_c_o)
SnippetVehicleScale_debug_bin      := ./../../../Bin/android9/SnippetVehicleScaleDEBUG

clean_SnippetVehicleScale_debug: 
	@$(ECHO) clean SnippetVehicleScale debug
	@$(RMDIR) $(SnippetVehicleScale_debug_objsdir)
	@$(RMDIR) $(SnippetVehicleScale_debug_bin)

build_SnippetVehicleScale_debug: postbuild_SnippetVehicleScale_debug
postbuild_SnippetVehicleScale_debug: mainbuild_SnippetVehicleScale_debug
mainbuild_SnippetVehicleScale_debug: prebuild_SnippetVehicleScale_debug $(SnippetVehicleScale_debug_bin)
prebuild_SnippetVehicleScale_debug:

$(SnippetVehicleScale_debug_bin): $(SnippetVehicleScale_debug_obj) 
	@mkdir -p `dirname ./../../../Bin/android9/SnippetVehicleScaleDEBUG`
	@$(CCLD) $(SnippetVehicleScale_debug_obj) $(SnippetVehicleScale_debug_lflags) -o $(SnippetVehicleScale_debug_bin) 
	@$(ECHO) building $@ complete!

SnippetVehicleScale_debug_DEPDIR = $(dir $(@))/$(*F)
$(SnippetVehicleScale_debug_cpp_o): $(SnippetVehicleScale_debug_objsdir)/%.o:
	@$(ECHO) SnippetVehicleScale: compiling debug $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetVehicleScale_debug_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))))
	@cp $(SnippetVehicleScale_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))).debug.P; \
	  rm -f $(SnippetVehicleScale_debug_DEPDIR).d

$(SnippetVehicleScale_debug_c_o): $(SnippetVehicleScale_debug_objsdir)/%.o:
	@$(ECHO) SnippetVehicleScale: compiling debug $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetVehicleScale_debug_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))))
	@cp $(SnippetVehicleScale_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))).debug.P; \
	  rm -f $(SnippetVehicleScale_debug_DEPDIR).d

$(SnippetVehicleScale_debug_cc_o): $(SnippetVehicleScale_debug_objsdir)/%.o:
	@$(ECHO) SnippetVehicleScale: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetVehicleScale_debug_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_ccfiles)))
	@cp $(SnippetVehicleScale_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))))).debug.P; \
	  rm -f $(SnippetVehicleScale_debug_DEPDIR).d

SnippetVehicleScale_checked_hpaths    := 
SnippetVehicleScale_checked_hpaths    += ./../../../Source/shared/general/shared
SnippetVehicleScale_checked_hpaths    += ./../../../Include
SnippetVehicleScale_checked_hpaths    += ./../../../Source/foundation/include
SnippetVehicleScale_checked_hpaths    += ./../../../Source/Common/src
SnippetVehicleScale_checked_hpaths    += ./../../../Source/GeomUtils/src
SnippetVehicleScale_checked_hpaths    += ./../../../Source/GeomUtils/headers
SnippetVehicleScale_checked_hpaths    += ./../../../Source/GeomUtils/include
SnippetVehicleScale_checked_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetVehicleScale_checked_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetVehicleScale_checked_lpaths    := 
SnippetVehicleScale_checked_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetVehicleScale_checked_lpaths    += ./../../../Lib/android9
SnippetVehicleScale_checked_defines   := $(SnippetVehicleScale_custom_defines)
SnippetVehicleScale_checked_defines   += ANDROID
SnippetVehicleScale_checked_defines   += GLES2
SnippetVehicleScale_checked_defines   += __ARM_ARCH_5__
SnippetVehicleScale_checked_defines   += __ARM_ARCH_5T__
SnippetVehicleScale_checked_defines   += __ARM_ARCH_5E__
SnippetVehicleScale_checked_defines   += __ARM_ARCH_5TE__
SnippetVehicleScale_checked_defines   += NDEBUG
SnippetVehicleScale_checked_defines   += PX_CHECKED
SnippetVehicleScale_checked_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetVehicleScale_checked_defines   += PX_NVTX
SnippetVehicleScale_checked_defines   += PHYSX_PROFILE_SDK
SnippetVehicleScale_checked_libraries := 
SnippetVehicleScale_checked_libraries += log
SnippetVehicleScale_checked_libraries += gnustl_static
SnippetVehicleScale_checked_libraries += supc++
SnippetVehicleScale_checked_libraries += m
SnippetVehicleScale_checked_libraries += c
SnippetVehicleScale_checked_libraries += nvToolsExt
SnippetVehicleScale_checked_libraries += PhysX3CommonCHECKED
SnippetVehicleScale_checked_libraries += PvdRuntimeCHECKED
SnippetVehicleScale_checked_libraries += SimulationControllerCHECKED
SnippetVehicleScale_checked_libraries += SceneQueryCHECKED
SnippetVehicleScale_checked_libraries += LowLevelCHECKED
SnippetVehicleScale_checked_libraries += LowLevelClothCHECKED
SnippetVehicleScale_checked_libraries += PhysX3CHECKED
SnippetVehicleScale_checked_libraries += PhysX3VehicleCHECKED
SnippetVehicleScale_checked_libraries += PhysX3CookingCHECKED
SnippetVehicleScale_checked_libraries += PhysX3ExtensionsCHECKED
SnippetVehicleScale_checked_libraries += PhysX3CharacterKinematicCHECKED
SnippetVehicleScale_checked_libraries += PhysXProfileSDKCHECKED
SnippetVehicleScale_checked_libraries += PxTaskCHECKED
SnippetVehicleScale_checked_libraries += PhysXVisualDebuggerSDKCHECKED
SnippetVehicleScale_checked_common_cflags	:= $(SnippetVehicleScale_custom_cflags)
SnippetVehicleScale_checked_common_cflags    += -MMD
SnippetVehicleScale_checked_common_cflags    += $(addprefix -D, $(SnippetVehicleScale_checked_defines))
SnippetVehicleScale_checked_common_cflags    += $(addprefix -I, $(SnippetVehicleScale_checked_hpaths))
SnippetVehicleScale_checked_cflags	:= $(SnippetVehicleScale_checked_common_cflags)
SnippetVehicleScale_checked_cflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetVehicleScale_checked_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetVehicleScale_checked_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleScale_checked_cflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
SnippetVehicleScale_checked_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetVehicleScale_checked_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetVehicleScale_checked_cppflags	:= $(SnippetVehicleScale_checked_common_cflags)
SnippetVehicleScale_checked_cppflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetVehicleScale_checked_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetVehicleScale_checked_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleScale_checked_cppflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
SnippetVehicleScale_checked_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetVehicleScale_checked_cppflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetVehicleScale_checked_lflags    := $(SnippetVehicleScale_custom_lflags)
SnippetVehicleScale_checked_lflags    += $(addprefix -L, $(SnippetVehicleScale_checked_lpaths))
SnippetVehicleScale_checked_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetVehicleScale_checked_libraries)) -Wl,--end-group
SnippetVehicleScale_checked_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleScale_checked_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetVehicleScale_checked_objsdir  = $(OBJS_DIR)/SnippetVehicleScale_checked
SnippetVehicleScale_checked_cpp_o    = $(addprefix $(SnippetVehicleScale_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetVehicleScale_cppfiles)))))
SnippetVehicleScale_checked_c_o      = $(addprefix $(SnippetVehicleScale_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetVehicleScale_cfiles)))))
SnippetVehicleScale_checked_cc_o      = $(addprefix $(SnippetVehicleScale_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetVehicleScale_ccfiles)))))
SnippetVehicleScale_checked_obj      = $(SnippetVehicleScale_checked_cpp_o) $(SnippetVehicleScale_checked_cc_o) $(SnippetVehicleScale_checked_c_o)
SnippetVehicleScale_checked_bin      := ./../../../Bin/android9/SnippetVehicleScaleCHECKED

clean_SnippetVehicleScale_checked: 
	@$(ECHO) clean SnippetVehicleScale checked
	@$(RMDIR) $(SnippetVehicleScale_checked_objsdir)
	@$(RMDIR) $(SnippetVehicleScale_checked_bin)

build_SnippetVehicleScale_checked: postbuild_SnippetVehicleScale_checked
postbuild_SnippetVehicleScale_checked: mainbuild_SnippetVehicleScale_checked
mainbuild_SnippetVehicleScale_checked: prebuild_SnippetVehicleScale_checked $(SnippetVehicleScale_checked_bin)
prebuild_SnippetVehicleScale_checked:

$(SnippetVehicleScale_checked_bin): $(SnippetVehicleScale_checked_obj) 
	@mkdir -p `dirname ./../../../Bin/android9/SnippetVehicleScaleCHECKED`
	@$(CCLD) $(SnippetVehicleScale_checked_obj) $(SnippetVehicleScale_checked_lflags) -o $(SnippetVehicleScale_checked_bin) 
	@$(ECHO) building $@ complete!

SnippetVehicleScale_checked_DEPDIR = $(dir $(@))/$(*F)
$(SnippetVehicleScale_checked_cpp_o): $(SnippetVehicleScale_checked_objsdir)/%.o:
	@$(ECHO) SnippetVehicleScale: compiling checked $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetVehicleScale_checked_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))))
	@cp $(SnippetVehicleScale_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))).checked.P; \
	  rm -f $(SnippetVehicleScale_checked_DEPDIR).d

$(SnippetVehicleScale_checked_c_o): $(SnippetVehicleScale_checked_objsdir)/%.o:
	@$(ECHO) SnippetVehicleScale: compiling checked $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetVehicleScale_checked_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))))
	@cp $(SnippetVehicleScale_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))).checked.P; \
	  rm -f $(SnippetVehicleScale_checked_DEPDIR).d

$(SnippetVehicleScale_checked_cc_o): $(SnippetVehicleScale_checked_objsdir)/%.o:
	@$(ECHO) SnippetVehicleScale: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetVehicleScale_checked_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_ccfiles)))
	@cp $(SnippetVehicleScale_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))))).checked.P; \
	  rm -f $(SnippetVehicleScale_checked_DEPDIR).d

SnippetVehicleScale_profile_hpaths    := 
SnippetVehicleScale_profile_hpaths    += ./../../../Source/shared/general/shared
SnippetVehicleScale_profile_hpaths    += ./../../../Include
SnippetVehicleScale_profile_hpaths    += ./../../../Source/foundation/include
SnippetVehicleScale_profile_hpaths    += ./../../../Source/Common/src
SnippetVehicleScale_profile_hpaths    += ./../../../Source/GeomUtils/src
SnippetVehicleScale_profile_hpaths    += ./../../../Source/GeomUtils/headers
SnippetVehicleScale_profile_hpaths    += ./../../../Source/GeomUtils/include
SnippetVehicleScale_profile_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetVehicleScale_profile_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetVehicleScale_profile_lpaths    := 
SnippetVehicleScale_profile_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetVehicleScale_profile_lpaths    += ./../../../Lib/android9
SnippetVehicleScale_profile_defines   := $(SnippetVehicleScale_custom_defines)
SnippetVehicleScale_profile_defines   += ANDROID
SnippetVehicleScale_profile_defines   += GLES2
SnippetVehicleScale_profile_defines   += __ARM_ARCH_5__
SnippetVehicleScale_profile_defines   += __ARM_ARCH_5T__
SnippetVehicleScale_profile_defines   += __ARM_ARCH_5E__
SnippetVehicleScale_profile_defines   += __ARM_ARCH_5TE__
SnippetVehicleScale_profile_defines   += NDEBUG
SnippetVehicleScale_profile_defines   += PX_PROFILE
SnippetVehicleScale_profile_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetVehicleScale_profile_defines   += PX_NVTX
SnippetVehicleScale_profile_defines   += PHYSX_PROFILE_SDK
SnippetVehicleScale_profile_libraries := 
SnippetVehicleScale_profile_libraries += log
SnippetVehicleScale_profile_libraries += gnustl_static
SnippetVehicleScale_profile_libraries += supc++
SnippetVehicleScale_profile_libraries += m
SnippetVehicleScale_profile_libraries += c
SnippetVehicleScale_profile_libraries += nvToolsExt
SnippetVehicleScale_profile_libraries += PhysX3CommonPROFILE
SnippetVehicleScale_profile_libraries += PvdRuntimePROFILE
SnippetVehicleScale_profile_libraries += SimulationControllerPROFILE
SnippetVehicleScale_profile_libraries += SceneQueryPROFILE
SnippetVehicleScale_profile_libraries += LowLevelPROFILE
SnippetVehicleScale_profile_libraries += LowLevelClothPROFILE
SnippetVehicleScale_profile_libraries += PhysX3PROFILE
SnippetVehicleScale_profile_libraries += PhysX3VehiclePROFILE
SnippetVehicleScale_profile_libraries += PhysX3CookingPROFILE
SnippetVehicleScale_profile_libraries += PhysX3ExtensionsPROFILE
SnippetVehicleScale_profile_libraries += PhysX3CharacterKinematicPROFILE
SnippetVehicleScale_profile_libraries += PhysXProfileSDKPROFILE
SnippetVehicleScale_profile_libraries += PxTaskPROFILE
SnippetVehicleScale_profile_libraries += PhysXVisualDebuggerSDKPROFILE
SnippetVehicleScale_profile_common_cflags	:= $(SnippetVehicleScale_custom_cflags)
SnippetVehicleScale_profile_common_cflags    += -MMD
SnippetVehicleScale_profile_common_cflags    += $(addprefix -D, $(SnippetVehicleScale_profile_defines))
SnippetVehicleScale_profile_common_cflags    += $(addprefix -I, $(SnippetVehicleScale_profile_hpaths))
SnippetVehicleScale_profile_cflags	:= $(SnippetVehicleScale_profile_common_cflags)
SnippetVehicleScale_profile_cflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetVehicleScale_profile_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetVehicleScale_profile_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleScale_profile_cflags  += -O3 -fno-strict-aliasing
SnippetVehicleScale_profile_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetVehicleScale_profile_cflags  += -fno-omit-frame-pointer -marm -funswitch-loops -finline-limit=300
SnippetVehicleScale_profile_cppflags	:= $(SnippetVehicleScale_profile_common_cflags)
SnippetVehicleScale_profile_cppflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetVehicleScale_profile_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetVehicleScale_profile_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleScale_profile_cppflags  += -O3 -fno-strict-aliasing
SnippetVehicleScale_profile_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetVehicleScale_profile_cppflags  += -fno-omit-frame-pointer -marm -funswitch-loops -finline-limit=300
SnippetVehicleScale_profile_lflags    := $(SnippetVehicleScale_custom_lflags)
SnippetVehicleScale_profile_lflags    += $(addprefix -L, $(SnippetVehicleScale_profile_lpaths))
SnippetVehicleScale_profile_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetVehicleScale_profile_libraries)) -Wl,--end-group
SnippetVehicleScale_profile_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleScale_profile_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetVehicleScale_profile_objsdir  = $(OBJS_DIR)/SnippetVehicleScale_profile
SnippetVehicleScale_profile_cpp_o    = $(addprefix $(SnippetVehicleScale_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetVehicleScale_cppfiles)))))
SnippetVehicleScale_profile_c_o      = $(addprefix $(SnippetVehicleScale_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetVehicleScale_cfiles)))))
SnippetVehicleScale_profile_cc_o      = $(addprefix $(SnippetVehicleScale_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetVehicleScale_ccfiles)))))
SnippetVehicleScale_profile_obj      = $(SnippetVehicleScale_profile_cpp_o) $(SnippetVehicleScale_profile_cc_o) $(SnippetVehicleScale_profile_c_o)
SnippetVehicleScale_profile_bin      := ./../../../Bin/android9/SnippetVehicleScalePROFILE

clean_SnippetVehicleScale_profile: 
	@$(ECHO) clean SnippetVehicleScale profile
	@$(RMDIR) $(SnippetVehicleScale_profile_objsdir)
	@$(RMDIR) $(SnippetVehicleScale_profile_bin)

build_SnippetVehicleScale_profile: postbuild_SnippetVehicleScale_profile
postbuild_SnippetVehicleScale_profile: mainbuild_SnippetVehicleScale_profile
mainbuild_SnippetVehicleScale_profile: prebuild_SnippetVehicleScale_profile $(SnippetVehicleScale_profile_bin)
prebuild_SnippetVehicleScale_profile:

$(SnippetVehicleScale_profile_bin): $(SnippetVehicleScale_profile_obj) 
	@mkdir -p `dirname ./../../../Bin/android9/SnippetVehicleScalePROFILE`
	@$(CCLD) $(SnippetVehicleScale_profile_obj) $(SnippetVehicleScale_profile_lflags) -o $(SnippetVehicleScale_profile_bin) 
	@$(ECHO) building $@ complete!

SnippetVehicleScale_profile_DEPDIR = $(dir $(@))/$(*F)
$(SnippetVehicleScale_profile_cpp_o): $(SnippetVehicleScale_profile_objsdir)/%.o:
	@$(ECHO) SnippetVehicleScale: compiling profile $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetVehicleScale_profile_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))))
	@cp $(SnippetVehicleScale_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))).profile.P; \
	  rm -f $(SnippetVehicleScale_profile_DEPDIR).d

$(SnippetVehicleScale_profile_c_o): $(SnippetVehicleScale_profile_objsdir)/%.o:
	@$(ECHO) SnippetVehicleScale: compiling profile $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetVehicleScale_profile_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))))
	@cp $(SnippetVehicleScale_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))).profile.P; \
	  rm -f $(SnippetVehicleScale_profile_DEPDIR).d

$(SnippetVehicleScale_profile_cc_o): $(SnippetVehicleScale_profile_objsdir)/%.o:
	@$(ECHO) SnippetVehicleScale: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetVehicleScale_profile_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_ccfiles)))
	@cp $(SnippetVehicleScale_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))))).profile.P; \
	  rm -f $(SnippetVehicleScale_profile_DEPDIR).d

SnippetVehicleScale_release_hpaths    := 
SnippetVehicleScale_release_hpaths    += ./../../../Source/shared/general/shared
SnippetVehicleScale_release_hpaths    += ./../../../Include
SnippetVehicleScale_release_hpaths    += ./../../../Source/foundation/include
SnippetVehicleScale_release_hpaths    += ./../../../Source/Common/src
SnippetVehicleScale_release_hpaths    += ./../../../Source/GeomUtils/src
SnippetVehicleScale_release_hpaths    += ./../../../Source/GeomUtils/headers
SnippetVehicleScale_release_hpaths    += ./../../../Source/GeomUtils/include
SnippetVehicleScale_release_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetVehicleScale_release_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetVehicleScale_release_lpaths    := 
SnippetVehicleScale_release_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetVehicleScale_release_lpaths    += ./../../../Lib/android9
SnippetVehicleScale_release_defines   := $(SnippetVehicleScale_custom_defines)
SnippetVehicleScale_release_defines   += ANDROID
SnippetVehicleScale_release_defines   += GLES2
SnippetVehicleScale_release_defines   += __ARM_ARCH_5__
SnippetVehicleScale_release_defines   += __ARM_ARCH_5T__
SnippetVehicleScale_release_defines   += __ARM_ARCH_5E__
SnippetVehicleScale_release_defines   += __ARM_ARCH_5TE__
SnippetVehicleScale_release_defines   += NDEBUG
SnippetVehicleScale_release_defines   += PHYSX_PROFILE_SDK
SnippetVehicleScale_release_libraries := 
SnippetVehicleScale_release_libraries += log
SnippetVehicleScale_release_libraries += gnustl_static
SnippetVehicleScale_release_libraries += supc++
SnippetVehicleScale_release_libraries += m
SnippetVehicleScale_release_libraries += c
SnippetVehicleScale_release_libraries += nvToolsExt
SnippetVehicleScale_release_libraries += PhysX3Common
SnippetVehicleScale_release_libraries += PvdRuntime
SnippetVehicleScale_release_libraries += SimulationController
SnippetVehicleScale_release_libraries += SceneQuery
SnippetVehicleScale_release_libraries += LowLevel
SnippetVehicleScale_release_libraries += LowLevelCloth
SnippetVehicleScale_release_libraries += PhysX3
SnippetVehicleScale_release_libraries += PhysX3Vehicle
SnippetVehicleScale_release_libraries += PhysX3Cooking
SnippetVehicleScale_release_libraries += PhysX3Extensions
SnippetVehicleScale_release_libraries += PhysX3CharacterKinematic
SnippetVehicleScale_release_libraries += PhysXProfileSDK
SnippetVehicleScale_release_libraries += PxTask
SnippetVehicleScale_release_libraries += PhysXVisualDebuggerSDK
SnippetVehicleScale_release_common_cflags	:= $(SnippetVehicleScale_custom_cflags)
SnippetVehicleScale_release_common_cflags    += -MMD
SnippetVehicleScale_release_common_cflags    += $(addprefix -D, $(SnippetVehicleScale_release_defines))
SnippetVehicleScale_release_common_cflags    += $(addprefix -I, $(SnippetVehicleScale_release_hpaths))
SnippetVehicleScale_release_cflags	:= $(SnippetVehicleScale_release_common_cflags)
SnippetVehicleScale_release_cflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetVehicleScale_release_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetVehicleScale_release_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleScale_release_cflags  += -O3 -fno-strict-aliasing
SnippetVehicleScale_release_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetVehicleScale_release_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetVehicleScale_release_cppflags	:= $(SnippetVehicleScale_release_common_cflags)
SnippetVehicleScale_release_cppflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetVehicleScale_release_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetVehicleScale_release_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleScale_release_cppflags  += -O3 -fno-strict-aliasing
SnippetVehicleScale_release_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetVehicleScale_release_cppflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetVehicleScale_release_lflags    := $(SnippetVehicleScale_custom_lflags)
SnippetVehicleScale_release_lflags    += $(addprefix -L, $(SnippetVehicleScale_release_lpaths))
SnippetVehicleScale_release_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetVehicleScale_release_libraries)) -Wl,--end-group
SnippetVehicleScale_release_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetVehicleScale_release_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetVehicleScale_release_objsdir  = $(OBJS_DIR)/SnippetVehicleScale_release
SnippetVehicleScale_release_cpp_o    = $(addprefix $(SnippetVehicleScale_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetVehicleScale_cppfiles)))))
SnippetVehicleScale_release_c_o      = $(addprefix $(SnippetVehicleScale_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetVehicleScale_cfiles)))))
SnippetVehicleScale_release_cc_o      = $(addprefix $(SnippetVehicleScale_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetVehicleScale_ccfiles)))))
SnippetVehicleScale_release_obj      = $(SnippetVehicleScale_release_cpp_o) $(SnippetVehicleScale_release_cc_o) $(SnippetVehicleScale_release_c_o)
SnippetVehicleScale_release_bin      := ./../../../Bin/android9/SnippetVehicleScale

clean_SnippetVehicleScale_release: 
	@$(ECHO) clean SnippetVehicleScale release
	@$(RMDIR) $(SnippetVehicleScale_release_objsdir)
	@$(RMDIR) $(SnippetVehicleScale_release_bin)

build_SnippetVehicleScale_release: postbuild_SnippetVehicleScale_release
postbuild_SnippetVehicleScale_release: mainbuild_SnippetVehicleScale_release
mainbuild_SnippetVehicleScale_release: prebuild_SnippetVehicleScale_release $(SnippetVehicleScale_release_bin)
prebuild_SnippetVehicleScale_release:

$(SnippetVehicleScale_release_bin): $(SnippetVehicleScale_release_obj) 
	@mkdir -p `dirname ./../../../Bin/android9/SnippetVehicleScale`
	@$(CCLD) $(SnippetVehicleScale_release_obj) $(SnippetVehicleScale_release_lflags) -o $(SnippetVehicleScale_release_bin) 
	@$(ECHO) building $@ complete!

SnippetVehicleScale_release_DEPDIR = $(dir $(@))/$(*F)
$(SnippetVehicleScale_release_cpp_o): $(SnippetVehicleScale_release_objsdir)/%.o:
	@$(ECHO) SnippetVehicleScale: compiling release $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetVehicleScale_release_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))))
	@cp $(SnippetVehicleScale_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))).release.P; \
	  rm -f $(SnippetVehicleScale_release_DEPDIR).d

$(SnippetVehicleScale_release_c_o): $(SnippetVehicleScale_release_objsdir)/%.o:
	@$(ECHO) SnippetVehicleScale: compiling release $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetVehicleScale_release_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))))
	@cp $(SnippetVehicleScale_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))).release.P; \
	  rm -f $(SnippetVehicleScale_release_DEPDIR).d

$(SnippetVehicleScale_release_cc_o): $(SnippetVehicleScale_release_objsdir)/%.o:
	@$(ECHO) SnippetVehicleScale: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetVehicleScale_release_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_ccfiles)))
	@cp $(SnippetVehicleScale_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))))).release.P; \
	  rm -f $(SnippetVehicleScale_release_DEPDIR).d

clean_SnippetVehicleScale:  clean_SnippetVehicleScale_debug clean_SnippetVehicleScale_checked clean_SnippetVehicleScale_profile clean_SnippetVehicleScale_release
	@rm -rf $(DEPSDIR)
