# Makefile generated by XPJ for ANDROID
-include Makefile.custom
ProjectName = SnippetContactReport
SnippetContactReport_cppfiles   += ./../../SnippetContactReport/SnippetContactReport.cpp
SnippetContactReport_cppfiles   += ./../../SnippetContactReport/SnippetContactReportRender.cpp

SnippetContactReport_cpp_debug_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.debug.P, $(SnippetContactReport_cppfiles)))))
SnippetContactReport_c_debug_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.debug.P, $(SnippetContactReport_cfiles)))))
SnippetContactReport_cc_debug_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.debug.P, $(SnippetContactReport_ccfiles)))))
SnippetContactReport_debug_dep      = $(SnippetContactReport_cpp_debug_dep) $(SnippetContactReport_cc_debug_dep) $(SnippetContactReport_c_debug_dep)
-include $(SnippetContactReport_debug_dep)
SnippetContactReport_cpp_checked_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.checked.P, $(SnippetContactReport_cppfiles)))))
SnippetContactReport_c_checked_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.checked.P, $(SnippetContactReport_cfiles)))))
SnippetContactReport_cc_checked_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.checked.P, $(SnippetContactReport_ccfiles)))))
SnippetContactReport_checked_dep      = $(SnippetContactReport_cpp_checked_dep) $(SnippetContactReport_cc_checked_dep) $(SnippetContactReport_c_checked_dep)
-include $(SnippetContactReport_checked_dep)
SnippetContactReport_cpp_profile_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.profile.P, $(SnippetContactReport_cppfiles)))))
SnippetContactReport_c_profile_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.profile.P, $(SnippetContactReport_cfiles)))))
SnippetContactReport_cc_profile_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.profile.P, $(SnippetContactReport_ccfiles)))))
SnippetContactReport_profile_dep      = $(SnippetContactReport_cpp_profile_dep) $(SnippetContactReport_cc_profile_dep) $(SnippetContactReport_c_profile_dep)
-include $(SnippetContactReport_profile_dep)
SnippetContactReport_cpp_release_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.release.P, $(SnippetContactReport_cppfiles)))))
SnippetContactReport_c_release_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.release.P, $(SnippetContactReport_cfiles)))))
SnippetContactReport_cc_release_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.release.P, $(SnippetContactReport_ccfiles)))))
SnippetContactReport_release_dep      = $(SnippetContactReport_cpp_release_dep) $(SnippetContactReport_cc_release_dep) $(SnippetContactReport_c_release_dep)
-include $(SnippetContactReport_release_dep)
SnippetContactReport_debug_hpaths    := 
SnippetContactReport_debug_hpaths    += ./../../../Source/shared/general/shared
SnippetContactReport_debug_hpaths    += ./../../../Include
SnippetContactReport_debug_hpaths    += ./../../../Source/foundation/include
SnippetContactReport_debug_hpaths    += ./../../../Source/Common/src
SnippetContactReport_debug_hpaths    += ./../../../Source/GeomUtils/src
SnippetContactReport_debug_hpaths    += ./../../../Source/GeomUtils/headers
SnippetContactReport_debug_hpaths    += ./../../../Source/GeomUtils/include
SnippetContactReport_debug_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetContactReport_debug_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetContactReport_debug_lpaths    := 
SnippetContactReport_debug_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetContactReport_debug_lpaths    += ./../../../Lib/android9
SnippetContactReport_debug_defines   := $(SnippetContactReport_custom_defines)
SnippetContactReport_debug_defines   += ANDROID
SnippetContactReport_debug_defines   += GLES2
SnippetContactReport_debug_defines   += __ARM_ARCH_5__
SnippetContactReport_debug_defines   += __ARM_ARCH_5T__
SnippetContactReport_debug_defines   += __ARM_ARCH_5E__
SnippetContactReport_debug_defines   += __ARM_ARCH_5TE__
SnippetContactReport_debug_defines   += _DEBUG
SnippetContactReport_debug_defines   += PX_DEBUG
SnippetContactReport_debug_defines   += PX_CHECKED
SnippetContactReport_debug_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetContactReport_debug_defines   += PX_NVTX
SnippetContactReport_debug_defines   += PHYSX_PROFILE_SDK
SnippetContactReport_debug_libraries := 
SnippetContactReport_debug_libraries += log
SnippetContactReport_debug_libraries += gnustl_static
SnippetContactReport_debug_libraries += supc++
SnippetContactReport_debug_libraries += m
SnippetContactReport_debug_libraries += c
SnippetContactReport_debug_libraries += nvToolsExt
SnippetContactReport_debug_libraries += PhysX3CommonCHECKED
SnippetContactReport_debug_libraries += PvdRuntimeCHECKED
SnippetContactReport_debug_libraries += SimulationControllerCHECKED
SnippetContactReport_debug_libraries += SceneQueryCHECKED
SnippetContactReport_debug_libraries += LowLevelCHECKED
SnippetContactReport_debug_libraries += LowLevelClothCHECKED
SnippetContactReport_debug_libraries += PhysX3CHECKED
SnippetContactReport_debug_libraries += PhysX3VehicleCHECKED
SnippetContactReport_debug_libraries += PhysX3CookingCHECKED
SnippetContactReport_debug_libraries += PhysX3ExtensionsCHECKED
SnippetContactReport_debug_libraries += PhysX3CharacterKinematicCHECKED
SnippetContactReport_debug_libraries += PhysXProfileSDKCHECKED
SnippetContactReport_debug_libraries += PxTaskCHECKED
SnippetContactReport_debug_libraries += PhysXVisualDebuggerSDKCHECKED
SnippetContactReport_debug_common_cflags	:= $(SnippetContactReport_custom_cflags)
SnippetContactReport_debug_common_cflags    += -MMD
SnippetContactReport_debug_common_cflags    += $(addprefix -D, $(SnippetContactReport_debug_defines))
SnippetContactReport_debug_common_cflags    += $(addprefix -I, $(SnippetContactReport_debug_hpaths))
SnippetContactReport_debug_cflags	:= $(SnippetContactReport_debug_common_cflags)
SnippetContactReport_debug_cflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetContactReport_debug_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetContactReport_debug_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetContactReport_debug_cflags  += -g3 -gdwarf-2
SnippetContactReport_debug_cppflags	:= $(SnippetContactReport_debug_common_cflags)
SnippetContactReport_debug_cppflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetContactReport_debug_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetContactReport_debug_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetContactReport_debug_cppflags  += -g3 -gdwarf-2
SnippetContactReport_debug_lflags    := $(SnippetContactReport_custom_lflags)
SnippetContactReport_debug_lflags    += $(addprefix -L, $(SnippetContactReport_debug_lpaths))
SnippetContactReport_debug_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetContactReport_debug_libraries)) -Wl,--end-group
SnippetContactReport_debug_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetContactReport_debug_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetContactReport_debug_objsdir  = $(OBJS_DIR)/SnippetContactReport_debug
SnippetContactReport_debug_cpp_o    = $(addprefix $(SnippetContactReport_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetContactReport_cppfiles)))))
SnippetContactReport_debug_c_o      = $(addprefix $(SnippetContactReport_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetContactReport_cfiles)))))
SnippetContactReport_debug_cc_o      = $(addprefix $(SnippetContactReport_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetContactReport_ccfiles)))))
SnippetContactReport_debug_obj      = $(SnippetContactReport_debug_cpp_o) $(SnippetContactReport_debug_cc_o) $(SnippetContactReport_debug_c_o)
SnippetContactReport_debug_bin      := ./../../../Bin/android9/SnippetContactReportDEBUG

clean_SnippetContactReport_debug: 
	@$(ECHO) clean SnippetContactReport debug
	@$(RMDIR) $(SnippetContactReport_debug_objsdir)
	@$(RMDIR) $(SnippetContactReport_debug_bin)

build_SnippetContactReport_debug: postbuild_SnippetContactReport_debug
postbuild_SnippetContactReport_debug: mainbuild_SnippetContactReport_debug
mainbuild_SnippetContactReport_debug: prebuild_SnippetContactReport_debug $(SnippetContactReport_debug_bin)
prebuild_SnippetContactReport_debug:

$(SnippetContactReport_debug_bin): $(SnippetContactReport_debug_obj) 
	@mkdir -p `dirname ./../../../Bin/android9/SnippetContactReportDEBUG`
	@$(CCLD) $(SnippetContactReport_debug_obj) $(SnippetContactReport_debug_lflags) -o $(SnippetContactReport_debug_bin) 
	@$(ECHO) building $@ complete!

SnippetContactReport_debug_DEPDIR = $(dir $(@))/$(*F)
$(SnippetContactReport_debug_cpp_o): $(SnippetContactReport_debug_objsdir)/%.o:
	@$(ECHO) SnippetContactReport: compiling debug $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetContactReport_debug_objsdir),, $@))), $(SnippetContactReport_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetContactReport_debug_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetContactReport_debug_objsdir),, $@))), $(SnippetContactReport_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetContactReport_debug_objsdir),, $@))), $(SnippetContactReport_cppfiles))))))
	@cp $(SnippetContactReport_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetContactReport_debug_objsdir),, $@))), $(SnippetContactReport_cppfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetContactReport_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetContactReport_debug_objsdir),, $@))), $(SnippetContactReport_cppfiles))))).debug.P; \
	  rm -f $(SnippetContactReport_debug_DEPDIR).d

$(SnippetContactReport_debug_c_o): $(SnippetContactReport_debug_objsdir)/%.o:
	@$(ECHO) SnippetContactReport: compiling debug $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetContactReport_debug_objsdir),, $@))), $(SnippetContactReport_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetContactReport_debug_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetContactReport_debug_objsdir),, $@))), $(SnippetContactReport_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetContactReport_debug_objsdir),, $@))), $(SnippetContactReport_cfiles))))))
	@cp $(SnippetContactReport_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetContactReport_debug_objsdir),, $@))), $(SnippetContactReport_cfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetContactReport_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetContactReport_debug_objsdir),, $@))), $(SnippetContactReport_cfiles))))).debug.P; \
	  rm -f $(SnippetContactReport_debug_DEPDIR).d

$(SnippetContactReport_debug_cc_o): $(SnippetContactReport_debug_objsdir)/%.o:
	@$(ECHO) SnippetContactReport: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetContactReport_debug_objsdir),, $@))), $(SnippetContactReport_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetContactReport_debug_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetContactReport_debug_objsdir),, $@))), $(SnippetContactReport_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetContactReport_debug_objsdir),, $@))), $(SnippetContactReport_ccfiles)))
	@cp $(SnippetContactReport_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetContactReport_debug_objsdir),, $@))), $(SnippetContactReport_ccfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetContactReport_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetContactReport_debug_objsdir),, $@))), $(SnippetContactReport_ccfiles))))).debug.P; \
	  rm -f $(SnippetContactReport_debug_DEPDIR).d

SnippetContactReport_checked_hpaths    := 
SnippetContactReport_checked_hpaths    += ./../../../Source/shared/general/shared
SnippetContactReport_checked_hpaths    += ./../../../Include
SnippetContactReport_checked_hpaths    += ./../../../Source/foundation/include
SnippetContactReport_checked_hpaths    += ./../../../Source/Common/src
SnippetContactReport_checked_hpaths    += ./../../../Source/GeomUtils/src
SnippetContactReport_checked_hpaths    += ./../../../Source/GeomUtils/headers
SnippetContactReport_checked_hpaths    += ./../../../Source/GeomUtils/include
SnippetContactReport_checked_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetContactReport_checked_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetContactReport_checked_lpaths    := 
SnippetContactReport_checked_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetContactReport_checked_lpaths    += ./../../../Lib/android9
SnippetContactReport_checked_defines   := $(SnippetContactReport_custom_defines)
SnippetContactReport_checked_defines   += ANDROID
SnippetContactReport_checked_defines   += GLES2
SnippetContactReport_checked_defines   += __ARM_ARCH_5__
SnippetContactReport_checked_defines   += __ARM_ARCH_5T__
SnippetContactReport_checked_defines   += __ARM_ARCH_5E__
SnippetContactReport_checked_defines   += __ARM_ARCH_5TE__
SnippetContactReport_checked_defines   += NDEBUG
SnippetContactReport_checked_defines   += PX_CHECKED
SnippetContactReport_checked_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetContactReport_checked_defines   += PX_NVTX
SnippetContactReport_checked_defines   += PHYSX_PROFILE_SDK
SnippetContactReport_checked_libraries := 
SnippetContactReport_checked_libraries += log
SnippetContactReport_checked_libraries += gnustl_static
SnippetContactReport_checked_libraries += supc++
SnippetContactReport_checked_libraries += m
SnippetContactReport_checked_libraries += c
SnippetContactReport_checked_libraries += nvToolsExt
SnippetContactReport_checked_libraries += PhysX3CommonCHECKED
SnippetContactReport_checked_libraries += PvdRuntimeCHECKED
SnippetContactReport_checked_libraries += SimulationControllerCHECKED
SnippetContactReport_checked_libraries += SceneQueryCHECKED
SnippetContactReport_checked_libraries += LowLevelCHECKED
SnippetContactReport_checked_libraries += LowLevelClothCHECKED
SnippetContactReport_checked_libraries += PhysX3CHECKED
SnippetContactReport_checked_libraries += PhysX3VehicleCHECKED
SnippetContactReport_checked_libraries += PhysX3CookingCHECKED
SnippetContactReport_checked_libraries += PhysX3ExtensionsCHECKED
SnippetContactReport_checked_libraries += PhysX3CharacterKinematicCHECKED
SnippetContactReport_checked_libraries += PhysXProfileSDKCHECKED
SnippetContactReport_checked_libraries += PxTaskCHECKED
SnippetContactReport_checked_libraries += PhysXVisualDebuggerSDKCHECKED
SnippetContactReport_checked_common_cflags	:= $(SnippetContactReport_custom_cflags)
SnippetContactReport_checked_common_cflags    += -MMD
SnippetContactReport_checked_common_cflags    += $(addprefix -D, $(SnippetContactReport_checked_defines))
SnippetContactReport_checked_common_cflags    += $(addprefix -I, $(SnippetContactReport_checked_hpaths))
SnippetContactReport_checked_cflags	:= $(SnippetContactReport_checked_common_cflags)
SnippetContactReport_checked_cflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetContactReport_checked_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetContactReport_checked_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetContactReport_checked_cflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
SnippetContactReport_checked_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetContactReport_checked_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetContactReport_checked_cppflags	:= $(SnippetContactReport_checked_common_cflags)
SnippetContactReport_checked_cppflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetContactReport_checked_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetContactReport_checked_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetContactReport_checked_cppflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
SnippetContactReport_checked_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetContactReport_checked_cppflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetContactReport_checked_lflags    := $(SnippetContactReport_custom_lflags)
SnippetContactReport_checked_lflags    += $(addprefix -L, $(SnippetContactReport_checked_lpaths))
SnippetContactReport_checked_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetContactReport_checked_libraries)) -Wl,--end-group
SnippetContactReport_checked_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetContactReport_checked_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetContactReport_checked_objsdir  = $(OBJS_DIR)/SnippetContactReport_checked
SnippetContactReport_checked_cpp_o    = $(addprefix $(SnippetContactReport_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetContactReport_cppfiles)))))
SnippetContactReport_checked_c_o      = $(addprefix $(SnippetContactReport_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetContactReport_cfiles)))))
SnippetContactReport_checked_cc_o      = $(addprefix $(SnippetContactReport_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetContactReport_ccfiles)))))
SnippetContactReport_checked_obj      = $(SnippetContactReport_checked_cpp_o) $(SnippetContactReport_checked_cc_o) $(SnippetContactReport_checked_c_o)
SnippetContactReport_checked_bin      := ./../../../Bin/android9/SnippetContactReportCHECKED

clean_SnippetContactReport_checked: 
	@$(ECHO) clean SnippetContactReport checked
	@$(RMDIR) $(SnippetContactReport_checked_objsdir)
	@$(RMDIR) $(SnippetContactReport_checked_bin)

build_SnippetContactReport_checked: postbuild_SnippetContactReport_checked
postbuild_SnippetContactReport_checked: mainbuild_SnippetContactReport_checked
mainbuild_SnippetContactReport_checked: prebuild_SnippetContactReport_checked $(SnippetContactReport_checked_bin)
prebuild_SnippetContactReport_checked:

$(SnippetContactReport_checked_bin): $(SnippetContactReport_checked_obj) 
	@mkdir -p `dirname ./../../../Bin/android9/SnippetContactReportCHECKED`
	@$(CCLD) $(SnippetContactReport_checked_obj) $(SnippetContactReport_checked_lflags) -o $(SnippetContactReport_checked_bin) 
	@$(ECHO) building $@ complete!

SnippetContactReport_checked_DEPDIR = $(dir $(@))/$(*F)
$(SnippetContactReport_checked_cpp_o): $(SnippetContactReport_checked_objsdir)/%.o:
	@$(ECHO) SnippetContactReport: compiling checked $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetContactReport_checked_objsdir),, $@))), $(SnippetContactReport_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetContactReport_checked_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetContactReport_checked_objsdir),, $@))), $(SnippetContactReport_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetContactReport_checked_objsdir),, $@))), $(SnippetContactReport_cppfiles))))))
	@cp $(SnippetContactReport_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetContactReport_checked_objsdir),, $@))), $(SnippetContactReport_cppfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetContactReport_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetContactReport_checked_objsdir),, $@))), $(SnippetContactReport_cppfiles))))).checked.P; \
	  rm -f $(SnippetContactReport_checked_DEPDIR).d

$(SnippetContactReport_checked_c_o): $(SnippetContactReport_checked_objsdir)/%.o:
	@$(ECHO) SnippetContactReport: compiling checked $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetContactReport_checked_objsdir),, $@))), $(SnippetContactReport_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetContactReport_checked_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetContactReport_checked_objsdir),, $@))), $(SnippetContactReport_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetContactReport_checked_objsdir),, $@))), $(SnippetContactReport_cfiles))))))
	@cp $(SnippetContactReport_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetContactReport_checked_objsdir),, $@))), $(SnippetContactReport_cfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetContactReport_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetContactReport_checked_objsdir),, $@))), $(SnippetContactReport_cfiles))))).checked.P; \
	  rm -f $(SnippetContactReport_checked_DEPDIR).d

$(SnippetContactReport_checked_cc_o): $(SnippetContactReport_checked_objsdir)/%.o:
	@$(ECHO) SnippetContactReport: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetContactReport_checked_objsdir),, $@))), $(SnippetContactReport_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetContactReport_checked_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetContactReport_checked_objsdir),, $@))), $(SnippetContactReport_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetContactReport_checked_objsdir),, $@))), $(SnippetContactReport_ccfiles)))
	@cp $(SnippetContactReport_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetContactReport_checked_objsdir),, $@))), $(SnippetContactReport_ccfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetContactReport_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetContactReport_checked_objsdir),, $@))), $(SnippetContactReport_ccfiles))))).checked.P; \
	  rm -f $(SnippetContactReport_checked_DEPDIR).d

SnippetContactReport_profile_hpaths    := 
SnippetContactReport_profile_hpaths    += ./../../../Source/shared/general/shared
SnippetContactReport_profile_hpaths    += ./../../../Include
SnippetContactReport_profile_hpaths    += ./../../../Source/foundation/include
SnippetContactReport_profile_hpaths    += ./../../../Source/Common/src
SnippetContactReport_profile_hpaths    += ./../../../Source/GeomUtils/src
SnippetContactReport_profile_hpaths    += ./../../../Source/GeomUtils/headers
SnippetContactReport_profile_hpaths    += ./../../../Source/GeomUtils/include
SnippetContactReport_profile_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetContactReport_profile_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetContactReport_profile_lpaths    := 
SnippetContactReport_profile_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetContactReport_profile_lpaths    += ./../../../Lib/android9
SnippetContactReport_profile_defines   := $(SnippetContactReport_custom_defines)
SnippetContactReport_profile_defines   += ANDROID
SnippetContactReport_profile_defines   += GLES2
SnippetContactReport_profile_defines   += __ARM_ARCH_5__
SnippetContactReport_profile_defines   += __ARM_ARCH_5T__
SnippetContactReport_profile_defines   += __ARM_ARCH_5E__
SnippetContactReport_profile_defines   += __ARM_ARCH_5TE__
SnippetContactReport_profile_defines   += NDEBUG
SnippetContactReport_profile_defines   += PX_PROFILE
SnippetContactReport_profile_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetContactReport_profile_defines   += PX_NVTX
SnippetContactReport_profile_defines   += PHYSX_PROFILE_SDK
SnippetContactReport_profile_libraries := 
SnippetContactReport_profile_libraries += log
SnippetContactReport_profile_libraries += gnustl_static
SnippetContactReport_profile_libraries += supc++
SnippetContactReport_profile_libraries += m
SnippetContactReport_profile_libraries += c
SnippetContactReport_profile_libraries += nvToolsExt
SnippetContactReport_profile_libraries += PhysX3CommonPROFILE
SnippetContactReport_profile_libraries += PvdRuntimePROFILE
SnippetContactReport_profile_libraries += SimulationControllerPROFILE
SnippetContactReport_profile_libraries += SceneQueryPROFILE
SnippetContactReport_profile_libraries += LowLevelPROFILE
SnippetContactReport_profile_libraries += LowLevelClothPROFILE
SnippetContactReport_profile_libraries += PhysX3PROFILE
SnippetContactReport_profile_libraries += PhysX3VehiclePROFILE
SnippetContactReport_profile_libraries += PhysX3CookingPROFILE
SnippetContactReport_profile_libraries += PhysX3ExtensionsPROFILE
SnippetContactReport_profile_libraries += PhysX3CharacterKinematicPROFILE
SnippetContactReport_profile_libraries += PhysXProfileSDKPROFILE
SnippetContactReport_profile_libraries += PxTaskPROFILE
SnippetContactReport_profile_libraries += PhysXVisualDebuggerSDKPROFILE
SnippetContactReport_profile_common_cflags	:= $(SnippetContactReport_custom_cflags)
SnippetContactReport_profile_common_cflags    += -MMD
SnippetContactReport_profile_common_cflags    += $(addprefix -D, $(SnippetContactReport_profile_defines))
SnippetContactReport_profile_common_cflags    += $(addprefix -I, $(SnippetContactReport_profile_hpaths))
SnippetContactReport_profile_cflags	:= $(SnippetContactReport_profile_common_cflags)
SnippetContactReport_profile_cflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetContactReport_profile_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetContactReport_profile_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetContactReport_profile_cflags  += -O3 -fno-strict-aliasing
SnippetContactReport_profile_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetContactReport_profile_cflags  += -fno-omit-frame-pointer -marm -funswitch-loops -finline-limit=300
SnippetContactReport_profile_cppflags	:= $(SnippetContactReport_profile_common_cflags)
SnippetContactReport_profile_cppflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetContactReport_profile_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetContactReport_profile_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetContactReport_profile_cppflags  += -O3 -fno-strict-aliasing
SnippetContactReport_profile_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetContactReport_profile_cppflags  += -fno-omit-frame-pointer -marm -funswitch-loops -finline-limit=300
SnippetContactReport_profile_lflags    := $(SnippetContactReport_custom_lflags)
SnippetContactReport_profile_lflags    += $(addprefix -L, $(SnippetContactReport_profile_lpaths))
SnippetContactReport_profile_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetContactReport_profile_libraries)) -Wl,--end-group
SnippetContactReport_profile_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetContactReport_profile_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetContactReport_profile_objsdir  = $(OBJS_DIR)/SnippetContactReport_profile
SnippetContactReport_profile_cpp_o    = $(addprefix $(SnippetContactReport_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetContactReport_cppfiles)))))
SnippetContactReport_profile_c_o      = $(addprefix $(SnippetContactReport_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetContactReport_cfiles)))))
SnippetContactReport_profile_cc_o      = $(addprefix $(SnippetContactReport_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetContactReport_ccfiles)))))
SnippetContactReport_profile_obj      = $(SnippetContactReport_profile_cpp_o) $(SnippetContactReport_profile_cc_o) $(SnippetContactReport_profile_c_o)
SnippetContactReport_profile_bin      := ./../../../Bin/android9/SnippetContactReportPROFILE

clean_SnippetContactReport_profile: 
	@$(ECHO) clean SnippetContactReport profile
	@$(RMDIR) $(SnippetContactReport_profile_objsdir)
	@$(RMDIR) $(SnippetContactReport_profile_bin)

build_SnippetContactReport_profile: postbuild_SnippetContactReport_profile
postbuild_SnippetContactReport_profile: mainbuild_SnippetContactReport_profile
mainbuild_SnippetContactReport_profile: prebuild_SnippetContactReport_profile $(SnippetContactReport_profile_bin)
prebuild_SnippetContactReport_profile:

$(SnippetContactReport_profile_bin): $(SnippetContactReport_profile_obj) 
	@mkdir -p `dirname ./../../../Bin/android9/SnippetContactReportPROFILE`
	@$(CCLD) $(SnippetContactReport_profile_obj) $(SnippetContactReport_profile_lflags) -o $(SnippetContactReport_profile_bin) 
	@$(ECHO) building $@ complete!

SnippetContactReport_profile_DEPDIR = $(dir $(@))/$(*F)
$(SnippetContactReport_profile_cpp_o): $(SnippetContactReport_profile_objsdir)/%.o:
	@$(ECHO) SnippetContactReport: compiling profile $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetContactReport_profile_objsdir),, $@))), $(SnippetContactReport_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetContactReport_profile_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetContactReport_profile_objsdir),, $@))), $(SnippetContactReport_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetContactReport_profile_objsdir),, $@))), $(SnippetContactReport_cppfiles))))))
	@cp $(SnippetContactReport_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetContactReport_profile_objsdir),, $@))), $(SnippetContactReport_cppfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetContactReport_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetContactReport_profile_objsdir),, $@))), $(SnippetContactReport_cppfiles))))).profile.P; \
	  rm -f $(SnippetContactReport_profile_DEPDIR).d

$(SnippetContactReport_profile_c_o): $(SnippetContactReport_profile_objsdir)/%.o:
	@$(ECHO) SnippetContactReport: compiling profile $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetContactReport_profile_objsdir),, $@))), $(SnippetContactReport_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetContactReport_profile_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetContactReport_profile_objsdir),, $@))), $(SnippetContactReport_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetContactReport_profile_objsdir),, $@))), $(SnippetContactReport_cfiles))))))
	@cp $(SnippetContactReport_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetContactReport_profile_objsdir),, $@))), $(SnippetContactReport_cfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetContactReport_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetContactReport_profile_objsdir),, $@))), $(SnippetContactReport_cfiles))))).profile.P; \
	  rm -f $(SnippetContactReport_profile_DEPDIR).d

$(SnippetContactReport_profile_cc_o): $(SnippetContactReport_profile_objsdir)/%.o:
	@$(ECHO) SnippetContactReport: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetContactReport_profile_objsdir),, $@))), $(SnippetContactReport_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetContactReport_profile_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetContactReport_profile_objsdir),, $@))), $(SnippetContactReport_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetContactReport_profile_objsdir),, $@))), $(SnippetContactReport_ccfiles)))
	@cp $(SnippetContactReport_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetContactReport_profile_objsdir),, $@))), $(SnippetContactReport_ccfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetContactReport_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetContactReport_profile_objsdir),, $@))), $(SnippetContactReport_ccfiles))))).profile.P; \
	  rm -f $(SnippetContactReport_profile_DEPDIR).d

SnippetContactReport_release_hpaths    := 
SnippetContactReport_release_hpaths    += ./../../../Source/shared/general/shared
SnippetContactReport_release_hpaths    += ./../../../Include
SnippetContactReport_release_hpaths    += ./../../../Source/foundation/include
SnippetContactReport_release_hpaths    += ./../../../Source/Common/src
SnippetContactReport_release_hpaths    += ./../../../Source/GeomUtils/src
SnippetContactReport_release_hpaths    += ./../../../Source/GeomUtils/headers
SnippetContactReport_release_hpaths    += ./../../../Source/GeomUtils/include
SnippetContactReport_release_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
SnippetContactReport_release_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
SnippetContactReport_release_lpaths    := 
SnippetContactReport_release_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetContactReport_release_lpaths    += ./../../../Lib/android9
SnippetContactReport_release_defines   := $(SnippetContactReport_custom_defines)
SnippetContactReport_release_defines   += ANDROID
SnippetContactReport_release_defines   += GLES2
SnippetContactReport_release_defines   += __ARM_ARCH_5__
SnippetContactReport_release_defines   += __ARM_ARCH_5T__
SnippetContactReport_release_defines   += __ARM_ARCH_5E__
SnippetContactReport_release_defines   += __ARM_ARCH_5TE__
SnippetContactReport_release_defines   += NDEBUG
SnippetContactReport_release_defines   += PHYSX_PROFILE_SDK
SnippetContactReport_release_libraries := 
SnippetContactReport_release_libraries += log
SnippetContactReport_release_libraries += gnustl_static
SnippetContactReport_release_libraries += supc++
SnippetContactReport_release_libraries += m
SnippetContactReport_release_libraries += c
SnippetContactReport_release_libraries += nvToolsExt
SnippetContactReport_release_libraries += PhysX3Common
SnippetContactReport_release_libraries += PvdRuntime
SnippetContactReport_release_libraries += SimulationController
SnippetContactReport_release_libraries += SceneQuery
SnippetContactReport_release_libraries += LowLevel
SnippetContactReport_release_libraries += LowLevelCloth
SnippetContactReport_release_libraries += PhysX3
SnippetContactReport_release_libraries += PhysX3Vehicle
SnippetContactReport_release_libraries += PhysX3Cooking
SnippetContactReport_release_libraries += PhysX3Extensions
SnippetContactReport_release_libraries += PhysX3CharacterKinematic
SnippetContactReport_release_libraries += PhysXProfileSDK
SnippetContactReport_release_libraries += PxTask
SnippetContactReport_release_libraries += PhysXVisualDebuggerSDK
SnippetContactReport_release_common_cflags	:= $(SnippetContactReport_custom_cflags)
SnippetContactReport_release_common_cflags    += -MMD
SnippetContactReport_release_common_cflags    += $(addprefix -D, $(SnippetContactReport_release_defines))
SnippetContactReport_release_common_cflags    += $(addprefix -I, $(SnippetContactReport_release_hpaths))
SnippetContactReport_release_cflags	:= $(SnippetContactReport_release_common_cflags)
SnippetContactReport_release_cflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetContactReport_release_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetContactReport_release_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetContactReport_release_cflags  += -O3 -fno-strict-aliasing
SnippetContactReport_release_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetContactReport_release_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetContactReport_release_cppflags	:= $(SnippetContactReport_release_common_cflags)
SnippetContactReport_release_cppflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
SnippetContactReport_release_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
SnippetContactReport_release_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetContactReport_release_cppflags  += -O3 -fno-strict-aliasing
SnippetContactReport_release_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetContactReport_release_cppflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetContactReport_release_lflags    := $(SnippetContactReport_custom_lflags)
SnippetContactReport_release_lflags    += $(addprefix -L, $(SnippetContactReport_release_lpaths))
SnippetContactReport_release_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetContactReport_release_libraries)) -Wl,--end-group
SnippetContactReport_release_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
SnippetContactReport_release_lflags  += -Wl,--no-undefined -Wl,-z,noexecstack -L../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm/usr/lib
SnippetContactReport_release_objsdir  = $(OBJS_DIR)/SnippetContactReport_release
SnippetContactReport_release_cpp_o    = $(addprefix $(SnippetContactReport_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetContactReport_cppfiles)))))
SnippetContactReport_release_c_o      = $(addprefix $(SnippetContactReport_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetContactReport_cfiles)))))
SnippetContactReport_release_cc_o      = $(addprefix $(SnippetContactReport_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetContactReport_ccfiles)))))
SnippetContactReport_release_obj      = $(SnippetContactReport_release_cpp_o) $(SnippetContactReport_release_cc_o) $(SnippetContactReport_release_c_o)
SnippetContactReport_release_bin      := ./../../../Bin/android9/SnippetContactReport

clean_SnippetContactReport_release: 
	@$(ECHO) clean SnippetContactReport release
	@$(RMDIR) $(SnippetContactReport_release_objsdir)
	@$(RMDIR) $(SnippetContactReport_release_bin)

build_SnippetContactReport_release: postbuild_SnippetContactReport_release
postbuild_SnippetContactReport_release: mainbuild_SnippetContactReport_release
mainbuild_SnippetContactReport_release: prebuild_SnippetContactReport_release $(SnippetContactReport_release_bin)
prebuild_SnippetContactReport_release:

$(SnippetContactReport_release_bin): $(SnippetContactReport_release_obj) 
	@mkdir -p `dirname ./../../../Bin/android9/SnippetContactReport`
	@$(CCLD) $(SnippetContactReport_release_obj) $(SnippetContactReport_release_lflags) -o $(SnippetContactReport_release_bin) 
	@$(ECHO) building $@ complete!

SnippetContactReport_release_DEPDIR = $(dir $(@))/$(*F)
$(SnippetContactReport_release_cpp_o): $(SnippetContactReport_release_objsdir)/%.o:
	@$(ECHO) SnippetContactReport: compiling release $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetContactReport_release_objsdir),, $@))), $(SnippetContactReport_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetContactReport_release_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetContactReport_release_objsdir),, $@))), $(SnippetContactReport_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetContactReport_release_objsdir),, $@))), $(SnippetContactReport_cppfiles))))))
	@cp $(SnippetContactReport_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetContactReport_release_objsdir),, $@))), $(SnippetContactReport_cppfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetContactReport_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetContactReport_release_objsdir),, $@))), $(SnippetContactReport_cppfiles))))).release.P; \
	  rm -f $(SnippetContactReport_release_DEPDIR).d

$(SnippetContactReport_release_c_o): $(SnippetContactReport_release_objsdir)/%.o:
	@$(ECHO) SnippetContactReport: compiling release $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetContactReport_release_objsdir),, $@))), $(SnippetContactReport_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(SnippetContactReport_release_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetContactReport_release_objsdir),, $@))), $(SnippetContactReport_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetContactReport_release_objsdir),, $@))), $(SnippetContactReport_cfiles))))))
	@cp $(SnippetContactReport_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetContactReport_release_objsdir),, $@))), $(SnippetContactReport_cfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetContactReport_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetContactReport_release_objsdir),, $@))), $(SnippetContactReport_cfiles))))).release.P; \
	  rm -f $(SnippetContactReport_release_DEPDIR).d

$(SnippetContactReport_release_cc_o): $(SnippetContactReport_release_objsdir)/%.o:
	@$(ECHO) SnippetContactReport: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetContactReport_release_objsdir),, $@))), $(SnippetContactReport_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(SnippetContactReport_release_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetContactReport_release_objsdir),, $@))), $(SnippetContactReport_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetContactReport_release_objsdir),, $@))), $(SnippetContactReport_ccfiles)))
	@cp $(SnippetContactReport_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetContactReport_release_objsdir),, $@))), $(SnippetContactReport_ccfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetContactReport_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetContactReport_release_objsdir),, $@))), $(SnippetContactReport_ccfiles))))).release.P; \
	  rm -f $(SnippetContactReport_release_DEPDIR).d

clean_SnippetContactReport:  clean_SnippetContactReport_debug clean_SnippetContactReport_checked clean_SnippetContactReport_profile clean_SnippetContactReport_release
	@rm -rf $(DEPSDIR)
