# Makefile generated by XPJ for ANDROID
-include Makefile.custom
ProjectName = PhysXExtensions
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtBroadPhase.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtClothFabricCooker.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtClothGeodesicTetherCooker.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtClothMeshQuadifier.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtClothSimpleTetherCooker.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtCollection.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtCpuWorkerThread.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtD6Joint.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtD6JointSolverPrep.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtDefaultCpuDispatcher.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtDefaultErrorCallback.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtDefaultSimulationFilterShader.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtDefaultStreams.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtDistanceJoint.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtDistanceJointSolverPrep.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtExtensions.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtFixedJoint.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtFixedJointSolverPrep.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtJoint.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtMetaData.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtParticleExt.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtPrismaticJoint.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtPrismaticJointSolverPrep.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtPvdClientImpl.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtPxStringTable.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtRevoluteJoint.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtRevoluteJointSolverPrep.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtRigidBodyExt.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtSimpleFactory.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtSmoothNormals.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtSphericalJoint.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtSphericalJointSolverPrep.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtTriangleMeshExt.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/ExtVisualDebugger.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/serialization/SnSerialization.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/serialization/SnSerializationRegistry.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/serialization/SnSerialUtils.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/serialization/Binary/SnBinaryDeserialization.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/serialization/Binary/SnBinarySerialization.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/serialization/Binary/SnConvX.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/serialization/Binary/SnConvX_Align.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/serialization/Binary/SnConvX_Convert.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/serialization/Binary/SnConvX_Error.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/serialization/Binary/SnConvX_MetaData.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/serialization/Binary/SnConvX_Output.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/serialization/Binary/SnConvX_Union.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/serialization/Binary/SnSerializationContext.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/serialization/Xml/SnJointRepXSerializer.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/serialization/Xml/SnRepXCoreSerializer.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/serialization/Xml/SnRepXUpgrader.cpp
PhysXExtensions_cppfiles   += ./../../PhysXExtensions/src/serialization/Xml/SnXmlSerialization.cpp
PhysXExtensions_cppfiles   += ./../../PhysXMetaData/extensions/src/PxExtensionAutoGeneratedMetaDataObjects.cpp
PhysXExtensions_cppfiles   += ./../../shared/general/string_parsing/src/FastXml.cpp

PhysXExtensions_cpp_checked_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.checked.P, $(PhysXExtensions_cppfiles)))))
PhysXExtensions_c_checked_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.checked.P, $(PhysXExtensions_cfiles)))))
PhysXExtensions_cc_checked_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.checked.P, $(PhysXExtensions_ccfiles)))))
PhysXExtensions_checked_dep      = $(PhysXExtensions_cpp_checked_dep) $(PhysXExtensions_cc_checked_dep) $(PhysXExtensions_c_checked_dep)
-include $(PhysXExtensions_checked_dep)
PhysXExtensions_cpp_profile_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.profile.P, $(PhysXExtensions_cppfiles)))))
PhysXExtensions_c_profile_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.profile.P, $(PhysXExtensions_cfiles)))))
PhysXExtensions_cc_profile_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.profile.P, $(PhysXExtensions_ccfiles)))))
PhysXExtensions_profile_dep      = $(PhysXExtensions_cpp_profile_dep) $(PhysXExtensions_cc_profile_dep) $(PhysXExtensions_c_profile_dep)
-include $(PhysXExtensions_profile_dep)
PhysXExtensions_cpp_release_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.release.P, $(PhysXExtensions_cppfiles)))))
PhysXExtensions_c_release_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.release.P, $(PhysXExtensions_cfiles)))))
PhysXExtensions_cc_release_dep      = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.release.P, $(PhysXExtensions_ccfiles)))))
PhysXExtensions_release_dep      = $(PhysXExtensions_cpp_release_dep) $(PhysXExtensions_cc_release_dep) $(PhysXExtensions_c_release_dep)
-include $(PhysXExtensions_release_dep)
PhysXExtensions_checked_hpaths    := 
PhysXExtensions_checked_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
PhysXExtensions_checked_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
PhysXExtensions_checked_hpaths    += ./../../../Include/foundation
PhysXExtensions_checked_hpaths    += ./../../foundation/include
PhysXExtensions_checked_hpaths    += ./../../../Include/physxprofilesdk
PhysXExtensions_checked_hpaths    += ./../../../Include/physxvisualdebuggersdk
PhysXExtensions_checked_hpaths    += ./../../../Include/common
PhysXExtensions_checked_hpaths    += ./../../../Include/geometry
PhysXExtensions_checked_hpaths    += ./../../../Include/pvd
PhysXExtensions_checked_hpaths    += ./../../../Include/cooking
PhysXExtensions_checked_hpaths    += ./../../../Include/extensions
PhysXExtensions_checked_hpaths    += ./../../../Include/vehicle
PhysXExtensions_checked_hpaths    += ./../../../Include/pxtask
PhysXExtensions_checked_hpaths    += ./../../../Include/cloth
PhysXExtensions_checked_hpaths    += ./../../../Include
PhysXExtensions_checked_hpaths    += ./../../Common/src
PhysXExtensions_checked_hpaths    += ./../../GeomUtils/headers
PhysXExtensions_checked_hpaths    += ./../../PhysXMetaData/core/include
PhysXExtensions_checked_hpaths    += ./../../PhysXMetaData/extensions/include
PhysXExtensions_checked_hpaths    += ./../../PhysXProfileSDK
PhysXExtensions_checked_hpaths    += ./../../PhysXExtensions/src
PhysXExtensions_checked_hpaths    += ./../../PhysXExtensions/src/serialization/Xml
PhysXExtensions_checked_hpaths    += ./../../PhysXExtensions/src/serialization/Binary
PhysXExtensions_checked_hpaths    += ./../../PvdRuntime/src
PhysXExtensions_checked_hpaths    += ./../../shared/general/string_parsing/include
PhysXExtensions_checked_hpaths    += ./../../shared/general/shared
PhysXExtensions_checked_hpaths    += ./../../shared/general/PxIOStream/include
PhysXExtensions_checked_hpaths    += ./../../shared/general/PxIOStream/public
PhysXExtensions_checked_lpaths    := 
PhysXExtensions_checked_defines   := $(PhysXExtensions_custom_defines)
PhysXExtensions_checked_defines   += PX_BUILD_NUMBER=0
PhysXExtensions_checked_defines   += ANDROID
PhysXExtensions_checked_defines   += GLES2
PhysXExtensions_checked_defines   += __ARM_ARCH_5__
PhysXExtensions_checked_defines   += __ARM_ARCH_5T__
PhysXExtensions_checked_defines   += __ARM_ARCH_5E__
PhysXExtensions_checked_defines   += __ARM_ARCH_5TE__
PhysXExtensions_checked_defines   += PX_PHYSX_STATIC_LIB
PhysXExtensions_checked_defines   += NDEBUG
PhysXExtensions_checked_defines   += PX_CHECKED
PhysXExtensions_checked_defines   += PX_SUPPORT_VISUAL_DEBUGGER
PhysXExtensions_checked_defines   += PX_NVTX
PhysXExtensions_checked_libraries := 
PhysXExtensions_checked_common_cflags	:= $(PhysXExtensions_custom_cflags)
PhysXExtensions_checked_common_cflags    += -MMD
PhysXExtensions_checked_common_cflags    += $(addprefix -D, $(PhysXExtensions_checked_defines))
PhysXExtensions_checked_common_cflags    += $(addprefix -I, $(PhysXExtensions_checked_hpaths))
PhysXExtensions_checked_cflags	:= $(PhysXExtensions_checked_common_cflags)
PhysXExtensions_checked_cflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
PhysXExtensions_checked_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
PhysXExtensions_checked_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
PhysXExtensions_checked_cflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
PhysXExtensions_checked_cflags  += -ffunction-sections -funwind-tables -fstack-protector
PhysXExtensions_checked_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
PhysXExtensions_checked_cppflags	:= $(PhysXExtensions_checked_common_cflags)
PhysXExtensions_checked_cppflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
PhysXExtensions_checked_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
PhysXExtensions_checked_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
PhysXExtensions_checked_cppflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
PhysXExtensions_checked_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
PhysXExtensions_checked_cppflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
PhysXExtensions_checked_lflags    := $(PhysXExtensions_custom_lflags)
PhysXExtensions_checked_lflags    += $(addprefix -L, $(PhysXExtensions_checked_lpaths))
PhysXExtensions_checked_lflags    += -Wl,--start-group $(addprefix -l, $(PhysXExtensions_checked_libraries)) -Wl,--end-group
PhysXExtensions_checked_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
PhysXExtensions_checked_objsdir  = $(OBJS_DIR)/PhysXExtensions_checked
PhysXExtensions_checked_cpp_o    = $(addprefix $(PhysXExtensions_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(PhysXExtensions_cppfiles)))))
PhysXExtensions_checked_c_o      = $(addprefix $(PhysXExtensions_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(PhysXExtensions_cfiles)))))
PhysXExtensions_checked_cc_o      = $(addprefix $(PhysXExtensions_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(PhysXExtensions_ccfiles)))))
PhysXExtensions_checked_obj      = $(PhysXExtensions_checked_cpp_o) $(PhysXExtensions_checked_cc_o) $(PhysXExtensions_checked_c_o)
PhysXExtensions_checked_bin      := ./../../../Lib/android9/libPhysX3ExtensionsCHECKED.a

clean_PhysXExtensions_checked: 
	@$(ECHO) clean PhysXExtensions checked
	@$(RMDIR) $(PhysXExtensions_checked_objsdir)
	@$(RMDIR) $(PhysXExtensions_checked_bin)

build_PhysXExtensions_checked: postbuild_PhysXExtensions_checked
postbuild_PhysXExtensions_checked: mainbuild_PhysXExtensions_checked
mainbuild_PhysXExtensions_checked: prebuild_PhysXExtensions_checked $(PhysXExtensions_checked_bin)
prebuild_PhysXExtensions_checked:

$(PhysXExtensions_checked_bin): $(PhysXExtensions_checked_obj) 
	@mkdir -p `dirname ./../../../Lib/android9/libPhysX3ExtensionsCHECKED.a`
	@$(AR) rcs $(PhysXExtensions_checked_bin) $(PhysXExtensions_checked_obj)
	@$(ECHO) building $@ complete!

PhysXExtensions_checked_DEPDIR = $(dir $(@))/$(*F)
$(PhysXExtensions_checked_cpp_o): $(PhysXExtensions_checked_objsdir)/%.o:
	@$(ECHO) PhysXExtensions: compiling checked $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXExtensions_checked_objsdir),, $@))), $(PhysXExtensions_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(PhysXExtensions_checked_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXExtensions_checked_objsdir),, $@))), $(PhysXExtensions_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXExtensions_checked_objsdir),, $@))), $(PhysXExtensions_cppfiles))))))
	@cp $(PhysXExtensions_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXExtensions_checked_objsdir),, $@))), $(PhysXExtensions_cppfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXExtensions_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXExtensions_checked_objsdir),, $@))), $(PhysXExtensions_cppfiles))))).checked.P; \
	  rm -f $(PhysXExtensions_checked_DEPDIR).d

$(PhysXExtensions_checked_c_o): $(PhysXExtensions_checked_objsdir)/%.o:
	@$(ECHO) PhysXExtensions: compiling checked $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXExtensions_checked_objsdir),, $@))), $(PhysXExtensions_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(PhysXExtensions_checked_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXExtensions_checked_objsdir),, $@))), $(PhysXExtensions_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXExtensions_checked_objsdir),, $@))), $(PhysXExtensions_cfiles))))))
	@cp $(PhysXExtensions_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXExtensions_checked_objsdir),, $@))), $(PhysXExtensions_cfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXExtensions_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXExtensions_checked_objsdir),, $@))), $(PhysXExtensions_cfiles))))).checked.P; \
	  rm -f $(PhysXExtensions_checked_DEPDIR).d

$(PhysXExtensions_checked_cc_o): $(PhysXExtensions_checked_objsdir)/%.o:
	@$(ECHO) PhysXExtensions: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXExtensions_checked_objsdir),, $@))), $(PhysXExtensions_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(PhysXExtensions_checked_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXExtensions_checked_objsdir),, $@))), $(PhysXExtensions_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXExtensions_checked_objsdir),, $@))), $(PhysXExtensions_ccfiles)))
	@cp $(PhysXExtensions_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXExtensions_checked_objsdir),, $@))), $(PhysXExtensions_ccfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXExtensions_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXExtensions_checked_objsdir),, $@))), $(PhysXExtensions_ccfiles))))).checked.P; \
	  rm -f $(PhysXExtensions_checked_DEPDIR).d

PhysXExtensions_profile_hpaths    := 
PhysXExtensions_profile_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
PhysXExtensions_profile_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
PhysXExtensions_profile_hpaths    += ./../../../Include/foundation
PhysXExtensions_profile_hpaths    += ./../../foundation/include
PhysXExtensions_profile_hpaths    += ./../../../Include/physxprofilesdk
PhysXExtensions_profile_hpaths    += ./../../../Include/physxvisualdebuggersdk
PhysXExtensions_profile_hpaths    += ./../../../Include/common
PhysXExtensions_profile_hpaths    += ./../../../Include/geometry
PhysXExtensions_profile_hpaths    += ./../../../Include/pvd
PhysXExtensions_profile_hpaths    += ./../../../Include/cooking
PhysXExtensions_profile_hpaths    += ./../../../Include/extensions
PhysXExtensions_profile_hpaths    += ./../../../Include/vehicle
PhysXExtensions_profile_hpaths    += ./../../../Include/pxtask
PhysXExtensions_profile_hpaths    += ./../../../Include/cloth
PhysXExtensions_profile_hpaths    += ./../../../Include
PhysXExtensions_profile_hpaths    += ./../../Common/src
PhysXExtensions_profile_hpaths    += ./../../GeomUtils/headers
PhysXExtensions_profile_hpaths    += ./../../PhysXMetaData/core/include
PhysXExtensions_profile_hpaths    += ./../../PhysXMetaData/extensions/include
PhysXExtensions_profile_hpaths    += ./../../PhysXProfileSDK
PhysXExtensions_profile_hpaths    += ./../../PhysXExtensions/src
PhysXExtensions_profile_hpaths    += ./../../PhysXExtensions/src/serialization/Xml
PhysXExtensions_profile_hpaths    += ./../../PhysXExtensions/src/serialization/Binary
PhysXExtensions_profile_hpaths    += ./../../PvdRuntime/src
PhysXExtensions_profile_hpaths    += ./../../shared/general/string_parsing/include
PhysXExtensions_profile_hpaths    += ./../../shared/general/shared
PhysXExtensions_profile_hpaths    += ./../../shared/general/PxIOStream/include
PhysXExtensions_profile_hpaths    += ./../../shared/general/PxIOStream/public
PhysXExtensions_profile_lpaths    := 
PhysXExtensions_profile_defines   := $(PhysXExtensions_custom_defines)
PhysXExtensions_profile_defines   += PX_BUILD_NUMBER=0
PhysXExtensions_profile_defines   += ANDROID
PhysXExtensions_profile_defines   += GLES2
PhysXExtensions_profile_defines   += __ARM_ARCH_5__
PhysXExtensions_profile_defines   += __ARM_ARCH_5T__
PhysXExtensions_profile_defines   += __ARM_ARCH_5E__
PhysXExtensions_profile_defines   += __ARM_ARCH_5TE__
PhysXExtensions_profile_defines   += PX_PHYSX_STATIC_LIB
PhysXExtensions_profile_defines   += NDEBUG
PhysXExtensions_profile_defines   += PX_PROFILE
PhysXExtensions_profile_defines   += PX_SUPPORT_VISUAL_DEBUGGER
PhysXExtensions_profile_defines   += PX_NVTX
PhysXExtensions_profile_libraries := 
PhysXExtensions_profile_common_cflags	:= $(PhysXExtensions_custom_cflags)
PhysXExtensions_profile_common_cflags    += -MMD
PhysXExtensions_profile_common_cflags    += $(addprefix -D, $(PhysXExtensions_profile_defines))
PhysXExtensions_profile_common_cflags    += $(addprefix -I, $(PhysXExtensions_profile_hpaths))
PhysXExtensions_profile_cflags	:= $(PhysXExtensions_profile_common_cflags)
PhysXExtensions_profile_cflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
PhysXExtensions_profile_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
PhysXExtensions_profile_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
PhysXExtensions_profile_cflags  += -O3 -fno-strict-aliasing
PhysXExtensions_profile_cflags  += -ffunction-sections -funwind-tables -fstack-protector
PhysXExtensions_profile_cflags  += -fno-omit-frame-pointer -marm -funswitch-loops -finline-limit=300
PhysXExtensions_profile_cppflags	:= $(PhysXExtensions_profile_common_cflags)
PhysXExtensions_profile_cppflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
PhysXExtensions_profile_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
PhysXExtensions_profile_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
PhysXExtensions_profile_cppflags  += -O3 -fno-strict-aliasing
PhysXExtensions_profile_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
PhysXExtensions_profile_cppflags  += -fno-omit-frame-pointer -marm -funswitch-loops -finline-limit=300
PhysXExtensions_profile_lflags    := $(PhysXExtensions_custom_lflags)
PhysXExtensions_profile_lflags    += $(addprefix -L, $(PhysXExtensions_profile_lpaths))
PhysXExtensions_profile_lflags    += -Wl,--start-group $(addprefix -l, $(PhysXExtensions_profile_libraries)) -Wl,--end-group
PhysXExtensions_profile_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
PhysXExtensions_profile_objsdir  = $(OBJS_DIR)/PhysXExtensions_profile
PhysXExtensions_profile_cpp_o    = $(addprefix $(PhysXExtensions_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(PhysXExtensions_cppfiles)))))
PhysXExtensions_profile_c_o      = $(addprefix $(PhysXExtensions_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(PhysXExtensions_cfiles)))))
PhysXExtensions_profile_cc_o      = $(addprefix $(PhysXExtensions_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(PhysXExtensions_ccfiles)))))
PhysXExtensions_profile_obj      = $(PhysXExtensions_profile_cpp_o) $(PhysXExtensions_profile_cc_o) $(PhysXExtensions_profile_c_o)
PhysXExtensions_profile_bin      := ./../../../Lib/android9/libPhysX3ExtensionsPROFILE.a

clean_PhysXExtensions_profile: 
	@$(ECHO) clean PhysXExtensions profile
	@$(RMDIR) $(PhysXExtensions_profile_objsdir)
	@$(RMDIR) $(PhysXExtensions_profile_bin)

build_PhysXExtensions_profile: postbuild_PhysXExtensions_profile
postbuild_PhysXExtensions_profile: mainbuild_PhysXExtensions_profile
mainbuild_PhysXExtensions_profile: prebuild_PhysXExtensions_profile $(PhysXExtensions_profile_bin)
prebuild_PhysXExtensions_profile:

$(PhysXExtensions_profile_bin): $(PhysXExtensions_profile_obj) 
	@mkdir -p `dirname ./../../../Lib/android9/libPhysX3ExtensionsPROFILE.a`
	@$(AR) rcs $(PhysXExtensions_profile_bin) $(PhysXExtensions_profile_obj)
	@$(ECHO) building $@ complete!

PhysXExtensions_profile_DEPDIR = $(dir $(@))/$(*F)
$(PhysXExtensions_profile_cpp_o): $(PhysXExtensions_profile_objsdir)/%.o:
	@$(ECHO) PhysXExtensions: compiling profile $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXExtensions_profile_objsdir),, $@))), $(PhysXExtensions_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(PhysXExtensions_profile_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXExtensions_profile_objsdir),, $@))), $(PhysXExtensions_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXExtensions_profile_objsdir),, $@))), $(PhysXExtensions_cppfiles))))))
	@cp $(PhysXExtensions_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXExtensions_profile_objsdir),, $@))), $(PhysXExtensions_cppfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXExtensions_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXExtensions_profile_objsdir),, $@))), $(PhysXExtensions_cppfiles))))).profile.P; \
	  rm -f $(PhysXExtensions_profile_DEPDIR).d

$(PhysXExtensions_profile_c_o): $(PhysXExtensions_profile_objsdir)/%.o:
	@$(ECHO) PhysXExtensions: compiling profile $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXExtensions_profile_objsdir),, $@))), $(PhysXExtensions_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(PhysXExtensions_profile_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXExtensions_profile_objsdir),, $@))), $(PhysXExtensions_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXExtensions_profile_objsdir),, $@))), $(PhysXExtensions_cfiles))))))
	@cp $(PhysXExtensions_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXExtensions_profile_objsdir),, $@))), $(PhysXExtensions_cfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXExtensions_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXExtensions_profile_objsdir),, $@))), $(PhysXExtensions_cfiles))))).profile.P; \
	  rm -f $(PhysXExtensions_profile_DEPDIR).d

$(PhysXExtensions_profile_cc_o): $(PhysXExtensions_profile_objsdir)/%.o:
	@$(ECHO) PhysXExtensions: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXExtensions_profile_objsdir),, $@))), $(PhysXExtensions_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(PhysXExtensions_profile_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXExtensions_profile_objsdir),, $@))), $(PhysXExtensions_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXExtensions_profile_objsdir),, $@))), $(PhysXExtensions_ccfiles)))
	@cp $(PhysXExtensions_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXExtensions_profile_objsdir),, $@))), $(PhysXExtensions_ccfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXExtensions_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXExtensions_profile_objsdir),, $@))), $(PhysXExtensions_ccfiles))))).profile.P; \
	  rm -f $(PhysXExtensions_profile_DEPDIR).d

PhysXExtensions_release_hpaths    := 
PhysXExtensions_release_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/include
PhysXExtensions_release_hpaths    += ./../../../externals/android-ndk-r8e/sources/cxx-stl/gnu-libstdc++/4.7/libs/armeabi-v7a/include
PhysXExtensions_release_hpaths    += ./../../../Include/foundation
PhysXExtensions_release_hpaths    += ./../../foundation/include
PhysXExtensions_release_hpaths    += ./../../../Include/physxprofilesdk
PhysXExtensions_release_hpaths    += ./../../../Include/physxvisualdebuggersdk
PhysXExtensions_release_hpaths    += ./../../../Include/common
PhysXExtensions_release_hpaths    += ./../../../Include/geometry
PhysXExtensions_release_hpaths    += ./../../../Include/pvd
PhysXExtensions_release_hpaths    += ./../../../Include/cooking
PhysXExtensions_release_hpaths    += ./../../../Include/extensions
PhysXExtensions_release_hpaths    += ./../../../Include/vehicle
PhysXExtensions_release_hpaths    += ./../../../Include/pxtask
PhysXExtensions_release_hpaths    += ./../../../Include/cloth
PhysXExtensions_release_hpaths    += ./../../../Include
PhysXExtensions_release_hpaths    += ./../../Common/src
PhysXExtensions_release_hpaths    += ./../../GeomUtils/headers
PhysXExtensions_release_hpaths    += ./../../PhysXMetaData/core/include
PhysXExtensions_release_hpaths    += ./../../PhysXMetaData/extensions/include
PhysXExtensions_release_hpaths    += ./../../PhysXProfileSDK
PhysXExtensions_release_hpaths    += ./../../PhysXExtensions/src
PhysXExtensions_release_hpaths    += ./../../PhysXExtensions/src/serialization/Xml
PhysXExtensions_release_hpaths    += ./../../PhysXExtensions/src/serialization/Binary
PhysXExtensions_release_hpaths    += ./../../PvdRuntime/src
PhysXExtensions_release_hpaths    += ./../../shared/general/string_parsing/include
PhysXExtensions_release_hpaths    += ./../../shared/general/shared
PhysXExtensions_release_hpaths    += ./../../shared/general/PxIOStream/include
PhysXExtensions_release_hpaths    += ./../../shared/general/PxIOStream/public
PhysXExtensions_release_lpaths    := 
PhysXExtensions_release_defines   := $(PhysXExtensions_custom_defines)
PhysXExtensions_release_defines   += PX_BUILD_NUMBER=0
PhysXExtensions_release_defines   += ANDROID
PhysXExtensions_release_defines   += GLES2
PhysXExtensions_release_defines   += __ARM_ARCH_5__
PhysXExtensions_release_defines   += __ARM_ARCH_5T__
PhysXExtensions_release_defines   += __ARM_ARCH_5E__
PhysXExtensions_release_defines   += __ARM_ARCH_5TE__
PhysXExtensions_release_defines   += PX_PHYSX_STATIC_LIB
PhysXExtensions_release_defines   += NDEBUG
PhysXExtensions_release_libraries := 
PhysXExtensions_release_common_cflags	:= $(PhysXExtensions_custom_cflags)
PhysXExtensions_release_common_cflags    += -MMD
PhysXExtensions_release_common_cflags    += $(addprefix -D, $(PhysXExtensions_release_defines))
PhysXExtensions_release_common_cflags    += $(addprefix -I, $(PhysXExtensions_release_hpaths))
PhysXExtensions_release_cflags	:= $(PhysXExtensions_release_common_cflags)
PhysXExtensions_release_cflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
PhysXExtensions_release_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
PhysXExtensions_release_cflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
PhysXExtensions_release_cflags  += -O3 -fno-strict-aliasing
PhysXExtensions_release_cflags  += -ffunction-sections -funwind-tables -fstack-protector
PhysXExtensions_release_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
PhysXExtensions_release_cppflags	:= $(PhysXExtensions_release_common_cflags)
PhysXExtensions_release_cppflags  += -fpic -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb-interwork -fno-exceptions -fno-rtti
PhysXExtensions_release_cppflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-psabi
PhysXExtensions_release_cppflags  += -isysroot ../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
PhysXExtensions_release_cppflags  += -O3 -fno-strict-aliasing
PhysXExtensions_release_cppflags  += -ffunction-sections -funwind-tables -fstack-protector
PhysXExtensions_release_cppflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
PhysXExtensions_release_lflags    := $(PhysXExtensions_custom_lflags)
PhysXExtensions_release_lflags    += $(addprefix -L, $(PhysXExtensions_release_lpaths))
PhysXExtensions_release_lflags    += -Wl,--start-group $(addprefix -l, $(PhysXExtensions_release_libraries)) -Wl,--end-group
PhysXExtensions_release_lflags  += --sysroot=../../../externals/android-ndk-r8e/platforms/android-9/arch-arm
PhysXExtensions_release_objsdir  = $(OBJS_DIR)/PhysXExtensions_release
PhysXExtensions_release_cpp_o    = $(addprefix $(PhysXExtensions_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(PhysXExtensions_cppfiles)))))
PhysXExtensions_release_c_o      = $(addprefix $(PhysXExtensions_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(PhysXExtensions_cfiles)))))
PhysXExtensions_release_cc_o      = $(addprefix $(PhysXExtensions_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(PhysXExtensions_ccfiles)))))
PhysXExtensions_release_obj      = $(PhysXExtensions_release_cpp_o) $(PhysXExtensions_release_cc_o) $(PhysXExtensions_release_c_o)
PhysXExtensions_release_bin      := ./../../../Lib/android9/libPhysX3Extensions.a

clean_PhysXExtensions_release: 
	@$(ECHO) clean PhysXExtensions release
	@$(RMDIR) $(PhysXExtensions_release_objsdir)
	@$(RMDIR) $(PhysXExtensions_release_bin)

build_PhysXExtensions_release: postbuild_PhysXExtensions_release
postbuild_PhysXExtensions_release: mainbuild_PhysXExtensions_release
mainbuild_PhysXExtensions_release: prebuild_PhysXExtensions_release $(PhysXExtensions_release_bin)
prebuild_PhysXExtensions_release:

$(PhysXExtensions_release_bin): $(PhysXExtensions_release_obj) 
	@mkdir -p `dirname ./../../../Lib/android9/libPhysX3Extensions.a`
	@$(AR) rcs $(PhysXExtensions_release_bin) $(PhysXExtensions_release_obj)
	@$(ECHO) building $@ complete!

PhysXExtensions_release_DEPDIR = $(dir $(@))/$(*F)
$(PhysXExtensions_release_cpp_o): $(PhysXExtensions_release_objsdir)/%.o:
	@$(ECHO) PhysXExtensions: compiling release $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXExtensions_release_objsdir),, $@))), $(PhysXExtensions_cppfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(PhysXExtensions_release_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXExtensions_release_objsdir),, $@))), $(PhysXExtensions_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXExtensions_release_objsdir),, $@))), $(PhysXExtensions_cppfiles))))))
	@cp $(PhysXExtensions_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXExtensions_release_objsdir),, $@))), $(PhysXExtensions_cppfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXExtensions_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXExtensions_release_objsdir),, $@))), $(PhysXExtensions_cppfiles))))).release.P; \
	  rm -f $(PhysXExtensions_release_DEPDIR).d

$(PhysXExtensions_release_c_o): $(PhysXExtensions_release_objsdir)/%.o:
	@$(ECHO) PhysXExtensions: compiling release $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXExtensions_release_objsdir),, $@))), $(PhysXExtensions_cfiles))...
	@mkdir -p $(dir $(@))
	@$(CC) $(PhysXExtensions_release_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXExtensions_release_objsdir),, $@))), $(PhysXExtensions_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXExtensions_release_objsdir),, $@))), $(PhysXExtensions_cfiles))))))
	@cp $(PhysXExtensions_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXExtensions_release_objsdir),, $@))), $(PhysXExtensions_cfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXExtensions_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXExtensions_release_objsdir),, $@))), $(PhysXExtensions_cfiles))))).release.P; \
	  rm -f $(PhysXExtensions_release_DEPDIR).d

$(PhysXExtensions_release_cc_o): $(PhysXExtensions_release_objsdir)/%.o:
	@$(ECHO) PhysXExtensions: compiling  $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXExtensions_release_objsdir),, $@))), $(PhysXExtensions_ccfiles))...
	@mkdir -p $(dir $(@))
	@$(CXX) $(PhysXExtensions_release_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXExtensions_release_objsdir),, $@))), $(PhysXExtensions_ccfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXExtensions_release_objsdir),, $@))), $(PhysXExtensions_ccfiles)))
	@cp $(PhysXExtensions_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXExtensions_release_objsdir),, $@))), $(PhysXExtensions_ccfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXExtensions_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXExtensions_release_objsdir),, $@))), $(PhysXExtensions_ccfiles))))).release.P; \
	  rm -f $(PhysXExtensions_release_DEPDIR).d

clean_PhysXExtensions:  clean_PhysXExtensions_checked clean_PhysXExtensions_profile clean_PhysXExtensions_release
	@rm -rf $(DEPSDIR)
