#! /bin/sh -x
set -e

ANDROID_SDK=../../externals/android-sdk/
pushd $ANDROID_SDK/platform-tools > /dev/null
ADB=`pwd`/adb
popd > /dev/null

case $1 in
  debug) suffix=DEBUG;;
  checked) suffix=CHECKED;;
  profile) suffix=PROFILE;;
  release) suffix=;;
  *) echo Must have a config!; exit 1;;
esac

snippetName=$2

if [ -z $snippetName ]; then
	echo Must have a snippet name!;	
	exit 1;
fi

executable=Snippet$snippetName$suffix

# wait until device is ready
$ADB wait-for-device

# delete all in tmp folder (exe)
$ADB shell "if [ -d data/tmp ]; then su -c rm -r data/tmp; fi"

# create folder hierarchy
$ADB shell "su -c mkdir -p data/tmp"

$ADB push ../../Bin/$ANDROID_CONFIG/$executable data/tmp

$ADB shell "su -c chmod 777 data/tmp/$executable"
